duckdb/duckdb-web

css/docu.scss
Unordered lists didn't have enough space below them due to `margin: 0`.
=> Drop zero margin from unordered lists

docs/sql/data_types/overview.md, docs/sql/indexes.md, docs/sql/pragmas.md, js/statements/indexes.js
This PR aims to improve the documentation of indexes including [their current lack of persistence](https://github.com/cwida/duckdb/issues/1110).
A couple of questions:
1. The current grammar `CREATE [ UNIQUE ] INDEX [ name ] ON table ({ column | ( expression )})` is not 100% accurate as it does not allow for compound indexes.
2. The current [Indexes page](https://duckdb.org/docs/sql/indexes) in the documentation contains an incomplete table with the supported data types. I'm not sure whether it's worth putting this table here, particularly because all general-purpose types seem to be supported by `create index`:
```sql
create table t(
my_bigint bigint,
my_boolean boolean,
my_blob blob,
my_date date,
my_double double,
my_integer integer,
my_real real,
my_smallint smallint,
my_timestamp …
```
=> Document indexes

css/docu.scss
As a followup of #13, I spun off the discussion on `<em>` to a separate PR.
=> Render <em> with italic and non-monospace by default

docs/sql/data_types/numeric.md, docs/sql/data_types/overview.md
While working on https://github.com/cwida/duckdb/pull/1256, I encountered a few inconsistencies in the docs. This PR amends them.
Even the tables in the PR omit a few typenames such as `INT16` (=`INT2`), `INT32` (=`INT4`), and `INT64` (=`INT8`). Should we include them or keep them omitted (as they can be confusing for newcomers).
=> Add numeric type aliases

docs/sql/functions/numeric.md
It appears that the proper escaping varies from implementation, but since we before this change _didn't_ escape the first occurrence under "Operator", but escaped the one under "Example" it doesn't make sense either way. This makes it even worse in the GitHub Markdown, but will fix the one in jekyll
=> Fix escaping of `|`

docs/sql/data_types/date.md, docs/sql/data_types/numeric.md, docs/sql/data_types/timestamp.md, docs/sql/functions/date.md, docs/sql/functions/numeric.md, docs/sql/functions/timestamp.md, docs/sql/introduction.md, docs/sql/pragmas.md
I fixed a bunch of formatting/typesetting errors and the example call of `setseed`.
I also updated the profiling example to use the new prettyprinting syntax:
=> Formatting and setseed example

docs/data/csv.md, docs/data/overview.md
Add clarification that gzip compressed CSV files are supported. This is related to the following discussion: https://github.com/duckdb/duckdb/discussions/1645.
=> Add clarification that gzip compressed CSV files are supported

docs/sql/statements/select.md
@Mytherin Here's my attempt at documenting the `rowid` pseudocolumn in the `select.md` page:
PS: please also take a look at #44
=> Document rowid

docs/data/parquet.md
As per https://github.com/duckdb/duckdb/pull/936#issuecomment-841608805. I figured that multi-file reading is actually documented, but hard to find for me (because after reading single files, it goes on with non-reading topics). 
* `Reading` is now named `Single-File Reads` instead of no title (as a hint that there is multi-file reading to come further down the page), 
* `Querying Parquet Files` was renamed to `Inserts and Views`.
* Re-ordered the paragraphs such that all content regarding reading shows up first, then view and inserts, then all writes. 
I admit this re-shuffling is opinionated to some degree.
=> Restructure page on parquet files

docs/sql/aggregates.md
@pdet I was looking into the `max_by` function. I wanted to extend the documentation as well but I'm uncertain about whether `max_by` is supposed to be an exact alias for `arg_max` or it is a statistical function that should always return floating-point values? (Currently, it returns floating-point values.)
```sql
create table args (a integer, b integer);
insert into args values (1,1), (2,2), (8,8), (10,10);
select arg_min(a,b), arg_max(a,b) from args;
select min_by(a,b), max_by(a,b) from args;
```
```console
D create table args (a integer, b integer);
D insert into args values (1,1), (2,2), (8,8), (10,10);
D select arg_min(a,b), arg_max(a,b) from args;
┌───────────────┬───────────────┐
│ arg_min(a, b) │ arg_max(a, b) │
├───────────────┼───────────────┤
│ 1             │ 10            │ …
```
=> Document aliases of aggregate functions

docs/sql/functions/timestamp.md
@Mytherin I fixed some example outputs of the datetime functions and added some formatting:
GitHub's word-diff is not great so here's a list of the main changes:
* `age` now returns a timestamp and not a date (!)
* `mons` is now `months`.
* `TIMESTAMP '1992-03-27' - TIMESTAMP '1992-03-22'`: previously was `INTERVAL 5 DAY`, changed to `5 days`
* `dayofyear(TIMESTAMP '1992-03-22')`: previously was `81`, changed to `82`
* `monthname(TIMESTAMP '1992-09-20')`: previously was `March`, changed to `September`
There were some missing/extra apostrophes and `generate_series` was mixed up with `range`.
=> Fix some datetime functions examples, formatting

docs/sql/full_text_search.md, docs/sql/functions/char.md
@Mytherin Two changes:
1. string concat operators looked off as the escape chars were rendered in the HTML:
2. the defaults of create_fts_index were not in sync. (cc @lnkuiper)
=> String concat and create_fts_index

docs/sql/pragmas.md
I fixed a few nits, removed the obsolete info that `profiling_output` can be a directory, and documented that both `profiling_output` and `profile_output` are available. Let me know if there are any plans to deprecate one.
```
PRAGMA profiling_output='/path/to/file.json';
PRAGMA profile_output='/path/to/file.json';
```
=> Update profiling info in PRAGMAs page

docs/why_duckdb.md
I was interested in using DuckDB in a personal Elixir project, and there didn't seem to be much support for it. I adapted the existing SQLite3 driver and Ecto (Elixir's ORM) adapter for DuckDB. _Most_ of the test suite passes at the moment, planning on doing more cleanup.
=> Adding Elixir driver to docs

docs/data/parquet.md, docs/sql/data_types/nested.md, docs/sql/functions/nested.md
Sorry for the branch name! I decided to knock out a few quick wins first.
This documents the list of filenames and the list of globs options for the parquet_scan function. I also included the Export statement as there is an option to export as parquet. A few other minor parquet docs tweaks are included.
I also beefed up the nested types docs quite a bit.
@mattico, do you have anything you would like to add or edit on the nested data types documentation? Thanks for your feedback in #110!
=> Docs: parquet_scan lists, Nested Types improvements

docs/sql/data_types/nested.md
Got Jekyll working locally and found the bug... Markdown tables render correctly now!
=> Fix markdown tables with a newline before them

docs/api/python.md, docs/api/r.md
The existing examples did not show how to connect to a file and were somewhat confusing (as using a memory database implies read-only = false so it was unnecessary).
=> Rework Python and R connection examples

_data/menu.json, docs/api/nodejs.md, docs/api/overview.md
We should have some kind of page for this! I just grabbed the Readme contents as a starting point. We can revise it more later, if that's ok!
(Fixes #138 )
=> Add NodeJS Readme as Node.js Client API page

docs/dev/profiling.md
Also matching usage in the site's own scripts
https://github.com/duckdb/duckdb-web/blob/4eeb2673256ac95bfe5f38cc43df3be56bb900f8/scripts/benchmark_html.py#L5
https://github.com/duckdb/duckdb-web/blob/4eeb2673256ac95bfe5f38cc43df3be56bb900f8/scripts/benchmark_html.py#L208
=> docs: correct import for query graph generator in profiling docs

_data/supporters.yml
With the previous `supporters.yml` file, `jekyll serve` failed for me with the following error message:
```console
------------------------------------------------
Jekyll 4.2.1   Please append `--trace` to the `serve` command 
for any additional information or backtrace. 
------------------------------------------------
/usr/local/share/gems/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:143:in `parse': (/home/szarnyasg/git/duck/duckdb-web/_data/supporters.yml): did not find expected key while parsing a block mapping at line 1 column 1 (Psych::SyntaxError)
from /usr/local/share/gems/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:143:in `load'
from /usr/local/share/gems/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `block in load_file'
from …
```
=> Fix indentation in supporters.yml file

docs/sql/data_types/list.md, docs/sql/functions/nested.md
Now all of the list examples use list_ functions. The array_ functions are still included on the functions page, but are not in any examples on the data types page. The list functions were also reordered for clarity.
=> list_slice vs array. array_pre/append. Reorder fns

docs/sql/query_syntax/with.md
Ensure that the 'end node' of the graph traversal is included even if the rows are reordered.
For details, see the discussion in issue #158.
=> Fix window function range in graph traversal example

_data/menu_docs_current.json, docs/sql/catalog_functions.md, docs/sql/configuration.md, docs/sql/data_types/overview.md, docs/sql/functions/blob.md, docs/sql/functions/char.md, docs/sql/functions/date.md, docs/sql/functions/datepart.md, docs/sql/functions/nested.md, docs/sql/functions/numeric.md, docs/sql/functions/patternmatching.md, docs/sql/functions/utility.md, docs/sql/statements/create_sequence.md, js/expressions/like.js
This documents many additional scalar functions. Let me know what feedback you have! Some other changes to how functions are documented include:
- Added a Utility Functions page
- Exposed the Catalog Functions page already made by @hawkfish (and made slight tweaks)
- Added a Text Similarity Functions section to the text functions page (open to feedback here!)
- Added alternative syntax to pattern matching docs (Ex: ~~ instead of LIKE)
Remaining TODOs include:
=> Scalar Functions Docs Improvements

docs/sql/data_types/overview.md
Just a tiny patch to an inconsistency in SQL documentation. Hope this is helpful and not just noise!
=> Added timezonetz type to SQL types overview page

docs/guides/python/import_arrow.md
pyarrow is used as `pa` in code, but there was not `pa` alias defined.
All other imports of pyarrow are fine:
=> Add module alias for pyarrow

docs/guides/python/import_arrow.md
The comments in the [Import from Arrow](https://duckdb.org/docs/guides/python/import_arrow) guide referenced a `my_df` variable (as in the [pandas example](https://duckdb.org/docs/guides/python/import_pandas)), but here `my_arrow` is used.
=> Fix arrow variable name in comment

js/statements/createtable.js
On sql/statements/create_table there was a parenthese missing to close the list of columns
=> added missing closing parenthese in foreign key railroad diagram

.gitignore
Small annoyance removed, every time jekyll does anything, it creates/alters .jekyll-metadata and it shows up in the untracked files list.
If this shouldn't be ignored, let me know and please also tell me how to stop it from showing up in the untracked files 👍
=> '.jekyll-metadata' folder added to gitignore

docs/sql/query_syntax/with.md
Fixes a small typo on the WITH clause documentation page
=> small typo: 'hiearchy -> hierarchy

docs/sql/statements/create_table.md, js/statements/createtable.js
This PR adds documentation for generated columns to the duckdb docs.
Syntax for it is added to the Syntax railroad diagram of `create_table`, this portion is made expandable under the name `generated-column`.  
This is what it looks like before it's expanded:
And this is after:
I've also added a brief description of generated columns to `create_table`. We might want to move this description to its own page later, but I felt this was the best place for it, since generated columns are only supported in `CREATE TABLE` statement for now.
PS:
I've had some issues with a bug where the VIRTUAL|GENERATED options were clipping through the options below, which almost magically disappeared, so please verify that this also works for you by running the site locally with jekyll
=> Generated column doc

.github/workflows/LinkChecker.yml
Currently this only runs on pushes in the master. Ideally we would run the dead-link check on every PR to check for dead links resulting from changes made to the website, but that is significantly more complex to setup.
=> Add a dead link-checker CI job

.github/workflows/LinkChecker.yml, index.html
Update the LinkChecker to check external links as well - everything passes now locally for me (i.e. no more dead links on the website, yay)
=> Check external links with LinkChecker as well

docs/archive/0.2.8/sql/aggregates.md, docs/archive/0.2.9/sql/aggregates.md, docs/archive/0.3.0/sql/aggregates.md, docs/archive/0.3.0/sql/functions/numeric.md, docs/archive/0.3.1/sql/aggregates.md, docs/archive/0.3.1/sql/functions/numeric.md, docs/archive/0.3.2/sql/aggregates.md, docs/archive/0.3.2/sql/functions/numeric.md, docs/archive/0.3.3/sql/aggregates.md, docs/archive/0.3.3/sql/functions/numeric.md, docs/archive/0.3.4/sql/aggregates.md, docs/archive/0.3.4/sql/functions/descriptions.txt, docs/archive/0.3.4/sql/functions/numeric.md, docs/archive/0.4.0/sql/aggregates.md, docs/archive/0.4.0/sql/functions/descriptions.txt, docs/archive/0.4.0/sql/functions/numeric.md, docs/sql/aggregates.md, docs/sql/functions/numeric.md
Hi 👋 - I noticed two functions described in the docs that result in errors in the terminal.
Firstly `atan2` is listed twice in [Numeric Functions](https://duckdb.org/docs/sql/functions/numeric#numeric-functions), with both one and two arguments. I believe the first listing should be changed to `atan`.
``` bash
duckdb> select atan2(0.5);
Error: Binder Error: No function matches the given name and argument types 'atan2(DECIMAL(2,1))'. You might need to add explicit type casts.
Candidate functions:
atan2(DOUBLE, DOUBLE) -> DOUBLE
LINE 1: select atan2(0.5);
^
duckdb> select atan(0.5);
┌─────────────────────┐
│      atan(0.5)      │
├─────────────────────┤
│ 0.46364760900080615 │
└─────────────────────┘
```
Secondly, `stddev_pop` is mentioned twice in [Statistical …
=> Documentation fix for atan and stddev_pop aggregate.

_posts/2022-07-27-art-storage.md
I think there is a typo. 
2-bit-trie.png show the index 7,10,12  , but the article write 7,10,14
=> Fix an typo in art-storage

_data/menu_docs_current.json, docs/extensions/postgres_scanner.md, docs/extensions/sqlite_scanner.md
Not sure if we want to inline these docs, or just leave them in the readme?
=> feat: link to out-of-tree scanner usage docs

docs/api/r.md
As per [Issue 3451](https://github.com/duckdb/duckdb/issues/3451) in the main duckdb repo, the default behaviour of dbDisconnect may not be what users expect. Describing this in the docs may make it clearer for users, until a decision is made on whether to change the default.
=> Mention disconnect/shutdown behaviour

_data/menu_docs_current.json
This PR adds an entry "Data Viewers" to the sidebar tree under "Guides", so that all top-level sections and sub-sections in "Guides" are now included in the sidebar tree.
Omitting this was an unfortunate oversight from my previous PR #251
=> Add Guides / Data Viewers to sidebar tree

docs/api/r.md, docs/archive/0.2.8/api/r.md, docs/archive/0.2.9/api/r.md, docs/archive/0.3.0/api/r.md, docs/archive/0.3.1/api/r.md, docs/archive/0.3.2/api/r.md, docs/archive/0.3.3/api/r.md, docs/archive/0.3.4/api/r.md, docs/archive/0.4.0/api/r.md
The [old DBI link](https://db.rstudio.com/dbi/) appears to be dead, this PR moves that link to [here](https://solutions.rstudio.com/db/r-packages/DBI/)
=> Fix dead link

docs/guides/python/sql_on_arrow.md
Fix small typo in the guide [SQL on Arrow](https://duckdb.org/docs/guides/python/sql_on_arrow).
=> Fix code example in Guides>Python>SQL on Arrow guide

css/search.css, js/search.js
Love the search! Super fast, super easy, nice search suggestions. 2 small tweaks:
The autocomplete is covering up the main list, so I changed it to relative position. I also made it so that if you hit enter and you haven't picked anything in the autocomplete list, it will still close the autocomplete list (so that you can see the main list).
NOTE: I am not sure how this would work on mobile. I did test with a very small browser window, so maybe that triggered the mobile layout? What's the best way to test that?
=> autocomplete relative pos and close on enter

docs/archive/0.4.0/api/python.md, docs/guides/python/import_pandas.md
This PR fixes my old attempt at documenting this setting
Previously I added it to the archive ..
And the placement of it was not great either, so now I've moved it to the "import from pandas" documentation page, which feels like a more suitable place for this information.
=> Pandas Analyze sample size documentation

docs/api/overview.md
I'd like to include a mention of these bindings for people who are interested in using DuckDB from Common Lisp. I hope this is acceptable. Thanks!
=> Add mention and link to third-party Common Lisp bindings

docs/sql/pragmas.md
Updated the documentation by renaming the outdated names of these pragma to the up-to-date ones
=> Renamed 'force_parallelism' to 'verify_parallelism'

docs/api/cpp.md
Using the C++ API docs I noticed a missing closing parenthesis in the example INSERT query. This super tiny PR fixes this typo.
=> Add missing closing parenthesis in C++ API docs

docs/data/csv.md
If you use auto, duckdb does not read the column definition
=> Change read_csv_auto with read_csv

docs/data/parquet.md
Added documentation for `file_row_number` argument of `parquet_scan` function in docs/data/parquet page.
=> Add file_row_number argument of parquet_scan

docs/sql/functions/char.md
The example listed for the `strlen` function incorrectly shows an example for `length` instead.
=> Fix `strlen` example

docs/sql/functions/numeric.md
[#408](https://github.com/duckdb/duckdb-web/issues/408)
Fixed cast in `isinf` and `isnan` examples.
=> Fix infinity and nan cast

docs/sql/data_types/text.md
This is ignored and not turned into a CHECK constraint currently
=> Update VARCHAR(n) docs

docs/guides/python/execute_sql.md
Addresses #424 to clarify which type of Python dataframe is returned from `.df()` when using the Python API.
=> Add pandas dataframe specificity

docs/sql/functions/nested.md
Partly fixes #438  Just listing the existence of the function and a brief description how it works, probably needs a more extensive documentation describing all the intricacies
=> `map_from_entries` added to the list of nested map functions

docs/api/python/overview.md
This PR comes in the spirit of stepping towards addressing #429 with what I understand so far about how this syntax operates for DuckDB API's. Something I wasn't sure about was whether prepared statements work for all API's or only some. In the meantime I thought it might be important to cover that it is supported by the Python API.
Thanks in advance for any thoughts or feedback you may have!
=> Add dollar symbol prepared statement notes for Python API

docs/sql/window_functions.md
This change adds to two clarifications to the window function docs:
1. How to specify multiple windows in the same `WINDOW` clause.
2. Where to find `WINDOW` in the canonical order of a select statement.
---
This was on my to-do list and I'm just getting around to it. I expressed some confusion in Discord a week or two ago and @Alex-Monahan suggested I updated the docs.
I generated the docs and tested the link -- it works.
Happy to make any changes -- just let me know!
=> Update window function documentation.

docs/sql/functions/datepart.md
Added documentation about [date part specifier synonyms that have been merged into duckdb master branch](https://github.com/duckdb/duckdb/pull/5845).
=> Add date part specifier synonym docs

docs/guides/python/jupyter.md
Adding jupysql into the Jupyter guide.
Additional example for plotting on top of DuckDB.
=> Jupysql integration

docs/sql/aggregates.md
Document current behaviour of `ORDER BY` for order-insensitive aggregate functions.
=> Order-insensitive ORDER BY

docs/sql/pragmas.md
The current docs make an impression that `PRAGMA database_size` is the way to get individual table sizes. Obviously it is not ;-( . Also, the `database_name` column was missing from the documentation.
=> Improve PRAGMA database_size docs

docs/guides/python/relational_api_pandas.md
Using `from rel = con.df(input_df)` results in a `TypeError` error. Changed to `rel = con.from_df(input_df)`.  
In reference to [Issue #525](https://github.com/duckdb/duckdb-web/issues/525).  
Thanks!
=> Fix relational_api_pandas.md

docs/archive/0.6.1/guides/python/ibis.md, docs/guides/python/ibis.md
Broken again in https://github.com/ibis-project/ibis/pull/5473
@cpcloud can we think about adding redirects in the future?
=> fix: update ibis tutorial links again

_layouts/default.html, _layouts/docu.html, _layouts/page.html, _layouts/post.html
Fixes #510 
This also seems to be standard in other projects - e.g. Spark, Presto and ClickHouse all follow this same convention.
=> Fix #510: move DuckDB to after the page title instead of before

_data/menu_docs_dev.json, docs/api/python/data_ingestion.md, docs/api/python/dbapi.md, docs/api/python/overview.md, docs/api/python/result_conversion.md, docs/guides/python/execute_sql.md, docs/guides/python/export_arrow.md, docs/guides/python/export_pandas.md, docs/guides/python/filesystems.md, docs/guides/python/import_arrow.md, docs/guides/python/import_pandas.md, docs/guides/python/polars.md, docs/guides/python/sql_on_pandas.md
This PR improves the Python docs in various aspects:
* Use `duckdb.sql` in examples, instead of creating a connection first
* Greatly simplify the "DuckDB and Polars" guide to make use of the new Polars <> DuckDB integration
* Split the Python API overview into separate pages (overview, data ingestion, result conversion and DB API)
* Add (limited) documentation for the new ingestion functions (`.read_csv`, `.read_json` , `.read_parquet`)
Please take a look, there's a bunch of new text + restructuring here.
=> Python API docs - add duckdb.sql, read_csv methods, and split the Python API docs into multiple (hopefully more clear) pages

_posts/2023-02-13-announcing-duckdb-070.md
`DataFrame._from_dict` is private. Adapted so we use the default constructor.
=> fix: Don't use private method for polars df init

docs/extensions/httpfs.md
This PR add the new COPY TO PARTITION BY syntax to the docs, according to the original description in the PR (https://github.com/duckdb/duckdb/pull/5964#issue-1552796444).
=> Add COPY TO PARTITION BY details

docs/extensions/httpfs.md
Saw someone having issues figuring out they had to INSTALL/LOAD the extension, figured this might help make it more obvious
=> Add mention of LOAD/INSTALL to httpfs documentation page

why_duckdb.md
I would like to add data load tool (dlt) - DuckDB destination as a project mentioned under [Other Projects](https://duckdb.org/why_duckdb#other-projects). I'm opening a PR since I thought it would be easier for everyone, but I can open an issue if necessary. Thanks!
=> adding data load tool (dlt) - DuckDB destination

docs/sql/configuration.md
The default calendar for ICU is actually not `gregorian` - e.g., if you are in China it will use one of the Chinese calendars.
=> Clarify default Calendar setting.

docs/guides/import/s3_import.md
This change shows how to import Parquet data from Cloudflare's R2 object storage via its S3 compatibility API.
Working example: https://twitter.com/elithrar/status/1631985701918048256?s=20
Disclaimer: I work for CF, and had a few users ask how to wire this up, hence the PR!
=> docs: show how to import from Cloudflare R2

_data/menu_docs_dev.json, _data/menu_side.json
As per issue here: https://github.com/duckdb/duckdb-web/issues/469
I think this should improve navigation, adding a reachable Sitemap top-level + having only leaves having content (this is more visible on mobile, whether a click means both open sub-menu AND go to page)
I personally think this makes sense, but would be nice to have someone (@Alex-Monahan, @Mause, ?) taking a proper look at this.
=> Fix #469 updating sidebar interaction model

_config.yml, docs/data/csv/overview.md
This adds the `jekyll-redirect-from` plugin as well, we might need to add that somewhere in the requirements
=> Add redirect of old CSV link to new CSV link

docs/sql/functions/timestamptz.md
This PR adds docs about table functions `generate_series` and `range` for `TIMESTAMPTZ` in ICU extension.
They have been merged into the duckdb master branch in [PR#6285](https://github.com/duckdb/duckdb/pull/6285).
=> Add docs about table functions generate_series and range for TIMESTAMPTZ

docs/sql/functions/char.md, docs/sql/functions/utility.md
Looks like `hash` function (https://github.com/duckdb/duckdb/pull/3077) is not documented. I added a short description for it. 
Not sure if it's in the right section (since it doesn't apply just to strings), but concluded that the proximity of `md5` makes it a good fit
=> Document hash() SQL function

docs/api/java.md
In the first example, we have named the table as `items`, in the second code example its name is `test`.  This resolves that, making it frictionless for users (like me) who like to copy-paste the entire code.
=> Use same table name in java code examples

docs/sql/expressions/case.md
The current documentation for `CASE` statement does not emebed the `AS` alias, which makes queries easier to use by putting alias (to create VIEWs or TABLEs on top of the `case` statement)
Merging this PR would make code sample even easier to use.
=> :student:  Update CASE statement > Add AS keyword

_data/menu_docs_dev.json, docs/sql/query_syntax/from.md
A new user wasn't able to quickly find the info on joins that they were looking for, and I have run into the same thing myself where it takes me an extra bit to remember that the join railroad diagram is in the from page!
=> Change FROM menu item to FROM & JOIN

docs/sql/expressions/case.md
Currenlty, we cannot run the examples out of the box.
For example on `CASE` statement, if I dumb run the tutorial I get this:
... where as is we provide the following code:
```sql
-- Create & feed example table 
CREATE OR REPLACE TABLE INTEGERS as SELECT UNNEST([1, 2, 3]) as i;
-- CASE example
SELECT i, CASE WHEN i>2 THEN 1 ELSE 0 END AS test FROM integers;
```
- :heavy_check_mark: Make code samples runnable
- :heavy_check_mark: Help people discover other `duckdb` functiions... and help improve people knowldge (cf  my [discussion](https://github.com/duckdb/duckdb/discussions/6674#discussioncomment-5272110))
- https://github.com/duckdb/duckdb/discussions/6674#discussioncomment-5272110
- [`UNNEST`](https://duckdb.org/docs/sql/query_syntax/unnest.html)
- …
=> :student:  Update case.md > create real table with real data

_data/menu_docs_dev.json, docs/data/json/overview.md, docs/data/overview.md, docs/extensions/json.md, docs/guides/import/json_export.md, docs/guides/import/json_import.md, docs/guides/index.md
I used the CSV import/export docs as an example. I will revisit this when I do more development on the JSON extension.
=> Add JSON import/export docs/guides

docs/extensions/full_text_search.md
The FTS documentation show the full call signature for the PRAGMA  `create_fts_index` with defaults. Although some named parameters are defined as `BOOL`, you cannot pass `TRUE` or `FALSE` when invoking the PRAGMA. The full example does not use non-default values for the named parameters `strip_accents`, `lower` or `overwrite`, so there is no issue there. However, when adapting the full example to set `overwrite` to a non-default value (`TRUE`) an error occurs:
`Error: Parser Error: Named parameter requires a constant on the RHS`
This error does not occur when passing `1` instead of `TRUE` and `0` instead of `FALSE`, which should be reflected in the documentation. I'm unsure whether this is something that can also be addressed upstream such that you _can_ pass `TRUE` or `FALSE`.
=> Replace TRUE with 1 and FALSE with 0 in FTS docs

_includes/installation.html
There is a nice duckdb [homebrew formula](https://formulae.brew.sh/formula/duckdb#default) but it's not referenced anywhere in the documentation.
I believe this could be the default way for any macos user, it's added to the `PATH`, and managing upgrade is straightforward.
Not sure about the location where to put it through, happy to hear your thoughts
=> Add homebrew installation doc

docs/data/parquet/overview.md
=> Add function list, to explicitly add `parquet_scan` as alias

.github/workflows/stackoverflow.yml, scripts/stackoverflow_bot.py
The bot has been designed to find all questions that have been posted within the last 3 days on StackOverflow with the "duckdb" tag. It will then post those questions to a designated discord channel.
The bot that will trigger every UTC 11:00 using Github Actions, while the time is 13:00 in Amsterdam(?).
We can also trigger the bot manually
Since we launch the bot daily to search for questions posted within the last 3 days, there may be instances of duplicate questions. However, we can easily address this issue by modifying the search to only include questions posted within the last 24 hours. This can be done by updating the `new_duckdb_questions` variable in the `stackoverflow_bot.py` file to `create_time > NOW() - INTERVAL 1 DAY`.
Thanks, @Alex-Monahan for helping with this
=> stackoverflow bot

_includes/iframe.html, docs/api/wasm.md
Use it in docs/api/wasm.md.
Note that I am not able to build docs locally, so while the change seems simple there are non negligible changes of it being borked, if someone touches this try to reproduce locally first.
Moving this to component so can be reused more easily (eg. @Tmonster!).
Currently it's pretty minimal, filling the parent width + having a fixed ratio, but if this work we could add optional parameters as it seems needed.
=> Add a jekyll component: iframe

docs/sql/aggregates.md
The function `kurtosis` applies a bias correction to the calculation according to the sample size similarly to what it does in `var_samp`, which is not obvious from the docs and is not always the default in other software (e.g. in SciPy the default is to not apply this correction).
This PR adds a small clarification about the kurtosis calculation to the docs.
=> Clarify details about kurtosis calculation

docs/archive/0.7.1/sql/data_types/bitstring.md, docs/archive/0.7.1/sql/functions/bitstring.md
See duckdb/duckdb#7232
These functions are not supported in v0.7.1, but were only added later. These accidentally got added to the v0.7.1 docs because they were merged into the feature branch prior to the release of v0.7.1 (but not included as part of the release).
=> Remove unsupported functions from archived docs

css/normalize.css
Pre 1ccf82cd ::markers on summary were non visible, after there was some unneded spacing on titles, both cases on Chrome-based browsers
=> Fix hasty 1ccf82cda [::marker]

docs/extensions/json.md
Fixes #662
We no longer throw an error, but default to `JSON` instead if we find inconsistent types in a JSON array.
=> Update outdated json_structure docs

README.md
The current bundler command doesn't include the main `_config.yml` file (only the `_config_exclude_archive.yml` file).
This prevents jekyll from starting properly.
The previous command (`bundler exec jekyll serve`) included `_config.yml` by default.
=> Fix bundler command in README

docs/api/python/dbapi.md, docs/guides/python/jupyter.md
This PR fixes #643 
Mention `':default:'` and mention that the methods on `duckdb` use this connection by default.
=> Improve Python docs for Connection

_config.yml, internals/storage.md
Happy if someone take it further, because probably there are also other places that needs to be updated.
One open thing is if we want to take a snapshot of docs and put that on v0.8.0 folder, or given that v0.8.1 will have basically the same features and there is work in progress in the docs, we just wait and fork them in a few weeks.
=> currentduckdbversion: 0.8.0

docs/sql/data_types/map.md
Also use varchar keys as examples as that is more intuitive/more in-line with what most people will use maps for
=> Move map documentation to new map syntax

docs/api/python/overview.md
This adds an explicit `con.close()` to the Persistent Storage example in the Python API Overview page.
As described in #808, readers may come away not being aware that an explicit connection close is required in some situations. A notable context is in a Jupyter notebook, where it is common for everything to be in the global scope, so no implicit close will occur (as was my context when it took me some time to work out why expected tables weren't available in my previously saved database).
=> Add con.close() to Persistent Storage example in Python Overview

docs/sql/data_types/enum.md
Hello,
I am submitting what I believe to be a valid correction to the section of your docs describing the `ENUM` data type.
I also confess I may not completely understand your intended meaning and how it relates to the distinction between high- and low-cardinality I found in [Wikipedia](https://en.wikipedia.org/wiki/Cardinality_(SQL_statements)#Values_of_cardinality).
Thank you for your amazing project. I use DuckDb everyday and evangelize about it whenever I have the opportunity.
=> Replace "high" with "low" in claim about ENUM data types and string column cardinality.

docs/sql/statements/alter_table.md
I can remove the whitespace fixes that my editor added but wrote a quick note based on the commentary in https://github.com/duckdb/duckdb/discussions/4639 since it took me some time to figure this out.
=> Add warning about altering table dependency error

_config.yml
Subset of https://github.com/duckdb/duckdb-web/pull/829, only moving duckdb version in _config.yml so that Installation and other pages will correctly show 0.8.1 as latest release.
=> DuckDB v0.8.1 in _config.yml

docs/sql/information_schema.md
Originally noted in https://github.com/tconbeer/harlequin/issues/89
=> chore: update information_schema to note catalog is now supported

_data/menu_docs_dev.json
I was testing the PR that merged: https://github.com/duckdb/duckdb-web/pull/838/
and found I had accidentally added a capital letter which broke the link.
=> Fix qstudio URL - link was broken

_data/menu_side.json, dev/building.md
This PR fixes #756 
It doesn't contain every option, a lot of the debug / miscellaneous flags are not documented as they seemed too esoteric.
=> Add docs for Building DuckDB

docs/extensions/spatial.md
Added one example in the spatial extension, did it to be the same form as the spatial copy, where there was a helpful example. 
As a user I struggled with coming up with the exact right syntax from scratch, thankfully I found the info on https://tech.marksblogg.com/duckdb-gis-spatial-extension.html
So hoping to contribute this back to make things a bit easier for others.
=> Added example SQL statement for ST_Read for the spatial extension

docs/sql/statements/drop.md
In the code example for `CASCADE`, the table name is "t1", not "1".
=> Fix typo in drop.md

docs/sql/data_types/interval.md
Rounding is expected for the cast of decimal to int. [5288](https://github.com/duckdb/duckdb/issues/5288)
According to the [interval docs](https://duckdb.org/docs/sql/data_types/interval), casting 1.5 to an integer is expected to truncate.
Documentation:
```
-- WARNING: If a decimal value is specified, it will be automatically truncated to an integer
-- To use more precise values, simply use a more granular date part 
-- (In this example use 18 MONTHS instead of 1.5 YEARS)
-- The statement below is equivalent to to_years(CAST(1.5 AS INTEGER))
-- 1 year
SELECT INTERVAL '1.5' YEARS; --WARNING! This returns 1 year!
```
Actual Results duckdb 0.8.1:
```
D SELECT INTERVAL '1.5' YEARS;
┌──────────────────────────────────┐
│ to_years(CAST('1.5' AS INTEGER)) │
│             interval             │ …
```
=> update intervale docs for rounding decimals instead of truncating them.

docs/sql/query_syntax/from.md
AsOf now supports all inequality operators
but `USING` will still generate >=
=> AsOf Inequalities

docs/sql/functions/date.md
Super small change! This is just to help folks find the date part functions more easily. An expert user had trouble finding them, so I imagine that other users may need a little bit more description as well!
=> Clarify what date subfields means (examples)

docs/api/r.md
Related to duckdb/duckdb#7865
Close #826
Clarify that DuckDB functions (e.g. read_parquet) can be used within the `dplyr::tbl` R function.
=> docs(r): add an example of use read_parquet function with dplyr

docs/extensions/spatial.md
Update docs to properly describe the signature of the `ST_AsGeoJSON(GEOMETRY) -> VARCHAR` function. 
It should reflect that a `GEOMETRY` input yields a `VARCHAR` output, instead of the current `VARCHAR -> VARCHAR`.
Also sorts `ST_AsGeoJSON` alphabetically along with the other `ST_As....` functions and formats the table.
=> docs: fix signature of `ST_AsGeoJSON`

docs/extensions/spatial.md
=> Fix typo in spatial extension docs

index.html
This PR changes the main site's "Documentation" link to point to the stable version's documentation.
This helps avoid confusion with newly introduced features that are only available in the `dev` build, e.g. https://github.com/duckdb/duckdb-web/issues/360#issuecomment-1661395421
=> Change documentation link to point to the stable version's documentation

docs/api/c/api.md, docs/api/c/appender.md, docs/api/c/config.md, docs/api/c/connect.md, docs/api/c/data_chunk.md, docs/api/c/prepared.md, docs/api/c/query.md, docs/api/c/replacement_scans.md, docs/api/c/table_functions.md, docs/api/c/types.md, docs/api/c/value.md, scripts/generate_docs.py
Wrapping in `` makes Vale treat them as code, rather than trying to spell check them
=> fix: wrap C API function names in code blocks

.dockerignore, Dockerfile, README.md, scripts/docker-build.sh, scripts/docker-serve-full.sh, scripts/docker-serve.sh, scripts/docker-stop.sh, scripts/docker-vars.sh
This PR add scripts to run run `jekyll serve` through Docker. It's a multi-arch image so it also runs fast on Apple Silicon.
There is no `builder` version (with Linux and Ruby packages pre-baked into the image), and I did not want to roll out a Docker image for this...
So currently the Docker script installs a few packages.
Here are the times required to deploy the `dev` version on my laptop (after a full `git clean -xdf .`):
- native `jekyll`: no setup time + 6.3 s deployment time
- Docker `jekyll`: 13.4 s setup time + 8.0 s deployment time
So the difference is noticeable but the Docker setup is perfectly usable.
Fixes #951
=> Add multi-arch Jekyll Docker image

CONTRIBUTING.md
=> Update the contributor guide

docs/api/cli.md, docs/data/overview.md, docs/extensions/httpfs.md, docs/extensions/json.md, docs/extensions/overview.md, docs/guides/import/excel_export.md, docs/guides/import/excel_import.md, docs/sql/data_types/map.md, docs/sql/expressions/star.md, docs/sql/functions/timestamptz.md
It turns out finding instances of lowercase SQL instructions is difficult – SQL is English language after all, and the term `from` appears everywhere in the documentation. So we need to restrict out scope to code blocks.
We can so so using my `agid` (`ag` + `ignore directory` + `docs/`) macro:
```bash
function agid() {
if [ ${#} -ge 1 ]; then
ag --ignore-dir=archive/ $@ docs/
else
echo "missing search argument"
return 1
fi
}
KEYWORD=from
agid --md -s "\`\`\`[a-zA-Z0-9+]+\n.+${KEYWORD}.+\n\`\`\`"
```
=> nit: Use uppercase keywords

.github/workflows/vale.yml
I propose to configure CI so that it doesn't fail on Vale errors for the time being. It will take some time to get the `e.g.`s and `i.e.`s fixed in the main repo.
=> CI: Do not fail on Vale errors

_data/menu_docs_dev.json
I noticed that the SQL menu is always open even if we are browsing something different (see secreenshot). I assume this is not on purpose, is it? In any case, this PR fixes it.
=> Close SQL in side menu

docs/api/cli.md
Making a start on https://github.com/duckdb/duckdb-web/issues/893 to document the CLI options.
=> Adding initial CLI options, with a link to the CLI Configuration section

_config_exclude_archive.yml
Jekyll seems to choke on the files in here sometimes, and this list overrides the main one in _config.yml
=> Update _config_exclude_archive.yml to exclude vendor

docs/guides/python/multiple_threads.md
There is currently a bug that pandas must be imported before `.df()` can be used in multiple threads.
=> Python multithreading guide: import pandas in main thread

docs/sql/statements/create_macro.md
Clarifying that default parameters must be named, which is different than some other languages.
=> Noting that default parameters must be named.

docs/data/csv/overview.md
Fixes #1039
Should be merged after - https://github.com/duckdb/duckdb/pull/8253
=> Document the CSV reader's buffer_size option

docs/api/adbc.md
As mentioned in #962, we should add more examples for ADBC. This PR adds docs for using Python with ADBC and duckdb.
=> Add python ADBC examples

docs/api/nodejs/overview.md
Added simplified example of how to use Apache Arrow together with the Node.js API to get data into DuckDB efficiently without copying it to a file first, or using INSERT statements.
I saw that https://github.com/duckdb/duckdb-web/blob/5cc1993f870a9d38a00bb0d748b68a5b00422f31/CONTRIBUTING.md states not to include guides on how to use external tools, but i think Apache Arrow is now so close to DuckDB that it would fit here.
Also, the existing Node.js API is not clear on how `register_buffer` method should/can be used.
This example makes that clear.
This PR is based on development i did for https://github.com/duckdb/duckdb/discussions/8466.
=> Add Apache Arrow example to overview.md for Node.js

docs/api/cpp.md
Resolves #1140.
I am not sure whether my change to
> The high-level ("SQL type") types of the result set columns are in `sql_types` and the low-level data representation types are in `types`. 
is sensible.
A quick look at `MaterializedQueryResult` made me assume that the low-level data types are not exposed anymore and the high-level type vector is now called `types` instead.
=> Rename SQLType to LogicalType in C++ API documentation

_includes/installation.html, index.html
Followup of a discussion with Mark & Hannes to make the front page and the installation page less cluttered.
=> Remove a few platforms from the front page, adjust installation page

docs/api/nodejs/overview.md
See https://github.com/duckdb/duckdb-web/issues/1136.
This PR updates the Node.js examples on the possible options that can be supplied to the Database constructor.
Updated all `var` occurences to `const`, as that's good practice in JavaScript.
=> [Node.js] code example for the options to the Database constructor

_data/menu_docs_dev.json, docs/api/python/known_issues.md
Start of this page, hopefully it stays mostly empty
We felt it was worth documenting this issue because we can't always prevent it if threads are manually created by the user.
=> Python known issues

single-file-document/concatenate_to_single_file.py
=> Require '##' for header to be labeled to avoid labeling comments in Bash/Python

_data/menu_docs_dev.json, css/main.scss, docs/api/wasm/extensions.md, docs/extensions/autocomplete.md, docs/extensions/full_text_search.md, docs/extensions/httpfs.md, docs/extensions/iceberg.md, docs/extensions/json.md, docs/extensions/official_extensions.md, docs/extensions/overview.md, docs/extensions/postgres_scanner.md, docs/extensions/spatial.md, docs/extensions/sqlite_scanner.md, docs/extensions/substrait.md
* Spin out official extension table to a separate document (it was way too far down in the overview)
* Use consistent placing/visual notation for GH links
* Lots of small formatting adjustments (formatting as code, uppercase vs. lowercase)
* Rework Wasm page (lots of small adjustments to the text)
=> Rework extension pages

single-file-document/pandoc-configuration.yaml, single-file-document/sql-duckdb.xml
This PR implements what the title says using Pandoc's custom syntax highlighting mechanism that accepts an XML file with the keywords: https://pandoc.org/chunkedhtml-demo/13-syntax-highlighting.html
Our XML is currently a copy of the Postgres syntax (with only the name/some comments changed). Later, this should be updated to match the complete set of keywords (`<list name="keywords">`) and function (`<list name="functions">`) but this is not a huge priority.
As the images below show, it's not perfect but it's a good start and we can work from here later.
=> Single-PDF document: Use custom syntax highlighter

docs/extensions/aws.md, docs/extensions/azure.md, docs/extensions/iceberg.md
=> Remove 'unreleased' notice from extensions that are released with v0.9.0

internals/storage.md
I'm adding the new storage version, 64, to the table.
@Maxxen @Mytherin is it okay to skip versions 60..63? These were bumped by the following commits (although I cannot seem to find version 60):
https://github.com/duckdb/duckdb/commit/72f6b3880b05faf6540f971b3169e9a2ab0a8aa8
https://github.com/duckdb/duckdb/commit/d8d26a8c599ebef2b45862333835355dfc509b90
https://github.com/duckdb/duckdb/commit/61b7edfb618c31aeb810842f264b0747a1f97640
https://github.com/duckdb/duckdb/commit/e3af76c8af91764be8f48a92ffc494080832a589
It seems a lot of things were flux, and it's unlikely that someone will use e.g. version 61. WDYT?
=> Add new storage version

dev/building.md
It turns out that CentOS 7, where people actually have to [build DuckDB from source](https://github.com/duckdb/duckdb/issues/1708), has yum instead of dnf.
=> Use YUM for CentOS build instructions

docs/data/csv/overview.md, docs/data/parquet/overview.md, docs/data/partitioning/partitioned_writes.md, docs/guides/import/csv_import.md, docs/guides/import/json_export.md, docs/guides/import/json_import.md, docs/sql/functions/dateformat.md, docs/sql/statements/export.md
It turns out there are many ways to spell COPY statement. This PR tries to use a single one and also link the page.
=> COPY statement

_config.yml, css/docu.scss
This PR makes two changes.
Using the customized [Rouge syntax highlighter](https://github.com/duckdb/rouge/tree/duckdb) allows highlighting function names (e.g. `enum_code(...)`) in code blocks. This PR adds function names so they are highlighted.
This PR sets SQL as the default language for inline code blocks. This is necessary as there is no way to manually change the language for an inline code block. In the docs, this looks as follows:
This is a substantial change compared to our current more muted look (see https://duckdb.org/docs/sql/functions/enum):
I edited the CSS to allow highlighting the code style classes outside of code blocks and adjusted the function (`.nf`) class to have a purple color:
https://github.com/duckdb/duckdb-web/pull/1174/files#diff-5c0b662767b3be5256eeb61ac6ad3a …
=> Highlight function names

docs/archive/0.9.0/sql/statements/copy.md, docs/sql/statements/copy.md
Fixes https://github.com/duckdb/duckdb/issues/9135
=> Document new 'header' default for CSV COPY statement

index.html
The colors on the front page are alternating shades of gray. Removing the Discord banner inadvertently caused this to start from a different shade of gray, which makes the installation box and features (simple, etc.) no longer stand out. 
Illustrations below.
=> Add dummy div to fix front page colors

docs/extensions/iceberg.md
I noticed `SELECT * FROM iceberg_snapshots('data/iceberg/lineitem_iceberg', ALLOW_MOVED_PATHS=true);` didn't work and since I toyed a bit with the function, I thought about adding a bit of documentation wouldn't hurt.
=> Fix iceberg snapshot doc and add metadata doc

css/docu.scss
I originally asked for the code blocks to be wider (1000px) but after looking at the docs with this for ~3 weeks, I still couldn't get used to it. Curiously, I find that this looks okay for tables. I think the key difference is that there are *many* code blocks and only a few tables.
So I propose reverting it back to the width of the text (720px).
=> Reduce code block width back to the text width

docs/api/r.md
I use `library(duckdb)` in the R docs which allowed me to remove `duckdb::` from a few places.
@Tmonster @hannes WDYT?
=> Simplify R docs by using library(duckdb)

.github/linkchecker/linkchecker.conf
It turns out sending a million requests to `github.com` causes Link Checker to fail... which was the likely cause of #1346.
=> Link Checker: Ignore links of the 'Report Issue' button

index.html
This eliminate the un-necessary redirect. 
However, it seems maintainer that have access to CloudFlare for dubckdb.org account should configure http -> https redirect to avoid folks accessing straight http protocol for the domain.
=> Avoid redirect by appending "/" for docs link

docs/api/python/overview.md, docs/archive/0.9.1/api/python/overview.md
Reverts duckdb/duckdb-web#1304
This was incorrectly bumped, we support >=3.7, see https://github.com/duckdb/duckdb/blob/main/tools/pythonpkg/setup.py#L351
=> Revert "Increase required Python version from 3.7 to 3.8"

docs/sql/data_types/timezones.md
Greenland (or at least parts of it) [has changed its timezone](https://www.timeanddate.com/news/time/greenland-change-timezone.html) from UTC-3 to UTC-2. This is reflected now when using `pg_timezone_names`. This PR updates the reference list.
America/Nuuk and America/Godthab are synonymous as Godthab is the old name of Nuuk.
=> Update timezone of Greenland

_posts/2023-11-03-db-benchmark-update.md
polars join at 500mb they are technically faster
=> fix all -> almost every

docs/api/python/overview.md
The information that the `connect()` method opens an in-memory database was not explicitly stated on the Python overview page. It is mentioned on other pages and can be deduced from the overview but I think it's worth stating it explicitly.
=> Clarify in-memory/persistent connections in Python

docs/archive/0.9.0/sql/data_types/struct.md, docs/archive/0.9.1/sql/data_types/struct.md, docs/sql/data_types/struct.md
In <https://github.com/duckdb/duckdb/pull/8942> we changed the behavior surrounding struct casting and the `row` function.
This PR updates the docs to reflect this.
=> Update `row` function docs

docs/archive/0.9.0/index.md, docs/archive/0.9.1/index.md
From now on, we'll store the documentation PDFs in AWS S3, exposed to blobs.duckdb.org
This resolves #1053
=> Link PDF documentation in S3

docs/extensions/overview.md
The sentence 
> This allows users to extend the functionaly of DuckDB such to suit their domain the best.
was not very clear.
Changed it to
> This allows users to extend the functionality of DuckDB such that it suits their domain the best.
=> docs: fix grammar in `extensions/overview.md`

docs/api/nodejs/overview.md, docs/api/python/data_ingestion.md, docs/api/python/dbapi.md, docs/api/python/function.md, docs/api/python/overview.md, docs/api/python/relational_api.md, docs/guides/python/execute_sql.md, docs/guides/python/polars.md
This PR introduces a consistent style for strings in Python. My original motivation for doing this was #1538 but it's something we should do regardless.
Why double quotes?
* This is the style [preferred by Black](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#strings).
* If single quotes are used in SQL, then we can write e.g. `duckdb.sql("FROM 'my.csv'")` without escaping or using triple quotes/triple apostrophes.
=> Use double quotes for Python examples

single-file-document/sql-duckdb.xml
=> Single-file PDF: Make keyword highlighting case-sensitive

docs/api/wasm/data_ingestion.md, docs/archive/0.8.1/api/wasm/data_ingestion.md, docs/archive/0.9.0/api/wasm/data_ingestion.md, docs/archive/0.9.1/api/wasm/data_ingestion.md, docs/archive/0.9.2/api/wasm/data_ingestion.md
insertCSVFromPath() is a function of the connection and not the database. Error message:
TypeError: Cannot read properties of undefined (reading 'columns')
=> fix insertCSVFromPath in docs

_data/menu_docs_dev.json, docs/api/nodejs/reference.md, docs/guides/data_viewers/youplot.md, docs/guides/import/query_parquet.md, docs/guides/import/s3_import.md, docs/guides/meta/explain.md, docs/guides/python/datafusion.md, docs/guides/python/execute_sql.md, docs/guides/python/filesystems.md, docs/guides/python/ibis.md, docs/guides/python/install.md, docs/guides/python/polars.md, docs/guides/python/vaex.md, docs/guides/sql_features/asof_join.md, docs/sql/data_types/timestamp.md, docs/sql/functions/dateformat.md, docs/sql/functions/datepart.md, internals/repositories.md, scripts/find_misaligned_titles.py
Adds a script and fixes #1551
I dropped "DuckDB" from most titles. Jekyll adds "- DuckDB" anyways and there's a DuckDB logo in the top left, so the users know that they are reading a DuckDB page.
=> Add script to find misaligned titles

_data/menu_docs_dev.json, docs/sql/data_types/array.md, docs/sql/data_types/list.md, docs/sql/data_types/overview.md
DuckDB PR https://github.com/duckdb/duckdb/pull/8983 by @Maxxen introduces fixed-size lists. This PR documents them. WIP.
Will eventually fix #1521
=> Documentation for fixed size lists

_data/menu_docs_dev.json, docs/guides/import/s3_iceberg_import.md, docs/guides/index.md
Adds a new guide to better explain how to retrieve an iceberg table from S3. Up until now all examples were for local files.
=> Add s3 iceberg import guide

docs/sql/data_types/list.md
After hearing a talk yesterday about DuckDB's list functions, I started playing with it. However, it took me a very long time to figure out how to create a list from a table column since I tried to somehow do it using the `list_value` function. Only by chance I stumbled across the `list` aggregate function which does the job.
To help people like myself in the future, I added a short note to the _Creating Lists_ section that refers to the `list` aggregate function.
=> Add note about using the list aggregate function to create lists from columns

docs/data/csv/auto_detection.md, docs/data/csv/overview.md
This is a partial fix towards #1417. When this is released in the stable version, we should update all pages that are talking about this:
```bash
$ ag --md --ignore-dir=archive/ --files-with-matches read_csv_auto docs/
docs/guides/python/filesystems.md
docs/guides/import/csv_import.md
docs/api/cli.md
docs/api/python/data_ingestion.md
docs/data/overview.md
docs/data/csv/overview.md
docs/data/csv/tips.md
docs/data/csv/auto_detection.md
docs/data/multiple_files/overview.md
docs/data/multiple_files/combining_schemas.md
docs/sql/statements/create_table.md
```
The reason I'm not updating those now is that users often browse the latest (dev) documentation while they are using the stable version. Such a big change would be potentially confusing to them.
=> Document change to CSV reader: sniffer (auto-detection) is run automatically

docs/sql/introduction.md
I find it a bit strange that the SQL intro starts with a run-down of the CLI client, it prompt, and how it handles persistence. I'd say that these are hardly relevant – and presumably many readers of the SQL intro will have a different setup (e.g. DBeaver).
=> Remove CLI example for the SQL intro

docs/api/cli.md, docs/extensions/autocomplete.md
This part of the CLI page is a waste of screen real estate. I moved it to the autocomplete extension's page.
=> Move shell autocomplete rules to the autocomplete extension's page

Gemfile.lock, docs/extensions/full_text_search.md, docs/guides/sql_features/full_text_search.md
I'm not sure what I had in mind when I opened #1446, where I complained that there's a big overlap between the FTS extension's documentation page and its guide. The overlap is minimal (and perfeclty in line with how we use the documentation vs the guides). Still, I revised both pages, so this PR fixes #1446.
=> Rework FTS pages

Gemfile.lock, _data/menu_docs_dev.json, code_of_conduct.md, docs/sql/data_types/enum.md, docs/sql/data_types/overview.md, docs/sql/data_types/struct.md, docs/sql/expressions/case.md, docs/sql/expressions/star.md, docs/sql/functions/blob.md, docs/sql/functions/date.md, docs/sql/functions/datepart.md, docs/sql/functions/interval.md, docs/sql/functions/numeric.md, docs/sql/functions/time.md, docs/sql/query_syntax/select.md, docs/sql/statements/unpivot.md
This PR has lots of minor fixes but also a more visible fix: it bumps to a new Rouge version which will match function names to strings ending in an opening paren, i.e.,`function_name(`, but will not match them to `function_name[^(]`.
As a consequence, terms like `month`, `year`, `version`, etc. will be picked up as functions when they have arguments but they will not be picked up when they are column/table names.
=> Nits 2023 11 26

docs/guides/sql_features/asof_join.md
Fixes #1439. The new guide has a slightly more interesting data set and also discusses the `USING` keyword.
=> Replace AsOf join tutorial with the one in the recent blog post

docs/extensions/json.md
It's not obvious which parts of jsonpath are supported from the current docs, but it turns out list wildcards are. This adds one example.
=> json_extract_string list wildcard example

docs/csv_import.md
Zero-length delimiter is fine but >1 delimiter strings are no longer allowed, see:
```sql
⚪◗ create table t(x int);
⚪◗ copy t to 't.csv' (delimiter '');
⚪◗ copy t to 't.csv' (delimiter 'hello');
Error: Invalid Input Error: The delimiter option cannot exceed a size of 1 byte.
```
=> Add note on CSV delimiter length

js/railroad.js
OFFSET works just fine without LIMIT. This should be reflected in the railroad diagrams.
```sql
SELECT unnest([42, 43, 44]) AS x
OFFSET 2;
```
```
┌───────┐
│   x   │
│ int32 │
├───────┤
│    44 │
└───────┘
```
=> Allow OFFSET clause without LIMIT

docs/sql/statements/insert.md
Fixes #1342
One remark – The previous page said:
> If a conflict does not meet this condition, an error will be thrown instead, and the entire operation is aborted.
This seem to be incorrect. Given a sample data set:
```sql
CREATE TABLE tbl (i INT PRIMARY KEY, j INT UNIQUE, k INT);
INSERT INTO tbl VALUES (1, 20, 300);
```
All of these queries finish successfully:
```sql
INSERT INTO tbl VALUES (1, 40, 700) ON CONFLICT (i) DO UPDATE SET k = 3 * EXCLUDED.k WHERE k < 100;
INSERT INTO tbl VALUES (1, 40, 700) ON CONFLICT (i) DO UPDATE SET k = 5 * EXCLUDED.k WHERE EXCLUDED.k < 100;
INSERT INTO tbl VALUES (1, 40, 700) ON CONFLICT (i) DO UPDATE SET k = 7 * EXCLUDED.k WHERE false;
```
As part of working on this PR, I created https://github.com/duckdb/duckdb/pull/9862 into mainline.
=> Rework INSERT INTO page

docs/archive/0.9.2/extensions/mysql.md, docs/extensions/mysql.md
And prefer to use `mysql` over `mysql_scanner` as the extension name
=> MySQL extension is also available for v0.9.2

docs/sql/configuration.md, docs/sql/expressions/collations.md, docs/sql/pragmas.md, docs/sql/query_syntax/orderby.md, docs/sql/samples.md
Fixes #1753
@Mytherin we discussed deprecating `PRAGMA` in the documentation where possible. This is what you had in mind?
=> Deprecate PRAGMA x=y in favor of SET x=y

dev/profiling.md
The original instructions at the bottom of [this page](https://duckdb.org/dev/profiling.html) don't work for me.
I'm getting error saying that generate_querygraph.py doesn't exist.
I looked into my local installation of duckdb within 
/home/jhrcek/.local/lib/python3.10/site-packages/duckdb and I didn't find any file named `generate_querygraph.py `
Instead there's this (running ls in the above folder):
```
├── query_graph
│   ├── __main__.py
│   └── __pycache__
│       └── __main__.cpython-310.pyc
```
When executed using `python -m duckdb.query_graph /path/to/file.json` it works for me (generates html file and opens it in my browser).
=> Fix instructions for generating query graph

docs/extensions/arrow.md, docs/extensions/autocomplete.md, docs/extensions/excel.md, docs/extensions/full_text_search.md, docs/extensions/httpfs.md, docs/extensions/icu.md, docs/extensions/inet.md, docs/extensions/jemalloc.md, docs/extensions/json.md, docs/extensions/tpcds.md, docs/extensions/tpch.md
This includes extensions that are in the main DuckDB repository.
=> Add GitHub links for all extensions

single-file-document/pandoc-configuration.yaml, single-file-document/templates/eisvogel2.tex
This reduces the page count from 985 pages to 855 pages, i.e., by approx. 13%.
More importantly, this removes from of the overlaps in large tables that describe functions.
=> Reduce font size in pdf

docs/extensions/working_with_extensions.md, docs/sql/functions/patternmatching.md, docs/sql/query_syntax/filter.md
SQL commens without a space after `--`? Not under my watch.
=> Nit: Add missing spaces for comments

docs/sql/functions/lambda.md
Without wrapping, the copy button's icon overlaps with the SQL code.
=> Wrap lambda code

docs/extensions/working_with_extensions.md
Before:
> Using remote paths or compressed files is currently not possible.
After:
> Using remote paths for compressed files is currently not possible.
=> docs: fix typo in  `working_with_extensions.md`

_layouts/docu.html
Recently we have received questions (e.g. #1867, #1780) via the "Report Issue" button on our documentation pages. I extended the issue template, which now explains options for asking questions.
=> Add warning to issue template

docs/api/wasm/instantiation.md, docs/archive/0.8.1/api/wasm/instantiation.md, docs/archive/0.9.0/api/wasm/instantiation.md, docs/archive/0.9.1/api/wasm/instantiation.md, docs/archive/0.9.2/api/wasm/instantiation.md
This is to be reverted after publishing v1.29, plus some more though should be put on this page as a whole.
=> Fix broken link to jsdelivr

docs/guides/performance/overview.md, docs/guides/performance/schema.md, microbenchmarks/README.md, microbenchmarks/load-comments.sql, microbenchmarks/prepare.sql, microbenchmarks/process-pk-results.sql, microbenchmarks/process-row-group-size-results.sql, microbenchmarks/schema-with-pk.sql, microbenchmarks/schema-without-pk.sql, microbenchmarks/ub-comments.sh, microbenchmarks/ub-load-csv.sh, microbenchmarks/ub-pk.sh, microbenchmarks/ub-row-group-size.sh, microbenchmarks/ub-string-joins-1.py, microbenchmarks/ub-string-joins-2.py, microbenchmarks/ub-string-joins.sh
The claim could use a microbenchmark on e.g. the SF300 data set – "look how much slower it is to join when it's loaded with the CSV reader's `all_varchar` setting set to `true`".
Fixes #1804
=> Performance guide: add note to avoid joining on strings

docs/guides/performance/schema.md, microbenchmarks/ub-join-type-2.py, microbenchmarks/ub-join-type-3.py, microbenchmarks/ub-join-type-4.py, microbenchmarks/ub-join-type.sh
Joining on UUIDs and VARCHARs are bad for performance but joining on UUIDs _as_ VARCHARs is even worse.
=> Perf guide: Add a new UUID experiment

docs/api/wasm/instantiation.md, docs/archive/0.8.1/api/wasm/instantiation.md, docs/archive/0.9.0/api/wasm/instantiation.md, docs/archive/0.9.1/api/wasm/instantiation.md, docs/archive/0.9.2/api/wasm/instantiation.md
This reverts commit 0804ddb1e65327c7e0879a2e335158159f833acd.
This change was not needed after latest changes in duckdb-wasm, so going back
=> Revert "Fix broken link to jsdelivr"

docs/sql/statements/checkpoint.md, docs/sql/statements/vacuum.md
=> Clarify why memory is not reclaimed in in-memory setup when checkpointing/vacuuming

docs/archive/0.9.2/extensions/mysql.md, docs/archive/0.9.2/extensions/postgres.md, docs/extensions/mysql.md, docs/extensions/postgres.md
* Add settings info to MySQL docs
* Add clear cache info to both MySQL/Postgres docs
* Add new `pg_connection_cache` setting
* Remove documentation for deprecated `postgres_scan` function
=> Update postgres/mysql docs

docs/extensions/postgres.md
Very useful if you are running in a container or other environment where you don't want to manage the connection specification in the application.
=> Postgres connection can be specified in environment variables.

docs/sql/configuration.md
It is in the examples below, but not stated explicitly.
=> Noting configuration is in duckdb_configuration().

scripts/lint.sh
`black scripts --skip-string-normalization` runs the fix, the `--check` flag avoids running the fix.
See `tldr black`:
```
- Output whether a file or a directory would have changes made to them if they were to be formatted:
black --check path/to/file_or_directory
```
=> Adjust lint.sh's -f flag to fix Python scripts with black

docs/api/cli/arguments.md, docs/data/csv/auto_detection.md, docs/extensions/full_text_search.md, docs/sql/functions/bitstring.md, docs/sql/functions/blob.md, docs/sql/functions/char.md, docs/sql/functions/numeric.md
Use markdownlint-enable/-disable blocks instead of markdownlint-disable-next-line
The latter breaks the formatting of tables in Jekyll
=> Use markdownlint-enable/-disable blocks instead of markdownlint-disable-next-line

docs/archive/0.9.2/sql/functions/utility.md, docs/archive/0.9.2/sql/information_schema.md, docs/sql/functions/utility.md, docs/sql/information_schema.md
I only backported it to 0.9.2, but I think the function got added earlier.
=> Document current_catalog()

docs/guides/import/s3_import.md
Some Cloudflare URLs broke: https://github.com/duckdb/duckdb-web/actions/runs/7730883454, this PR points them to new (working) ones
=> Update URLs pointing to the Cloudflare R2 documentation

index.html
If you land on the website, 'Live Demo' button points to "#".
This PR duplicate the href of the first demo, since I was lazy and didn't want to look for a more proper solution.
=> Duplicate href for Live Demo

_includes/landing-page/r/sql-query.r
I don't think escaping double quotes or the `paste` function are necessary here.
=> use raw string for R example

docs/data/json/overview.md
there currently aren't any other pages in this section.  I left it hidden to prompt people to add to it if any additional JSON pages are added to the documentation.
The blank section looks a little funny at the bottom of the page.
=> temporarily hide JSON's "Pages in This Section"

docs/api/c/config.md, docs/api/java.md
The functionality exists in the [JNI code](https://github.com/duckdb/duckdb/blob/main/tools/jdbc/src/jni/duckdb_java.cpp#L407) but is not documented.
Wording copied from the [C documentation](https://duckdb.org/docs/api/c/config)
=> Document that config options functionality exists in JDBC

docs/guides/performance/how_to_tune_workloads.md, docs/sql/pragmas.md
Should the wording of "By default, DuckDB uses the `.tmp` directory to spill to disk" also be updated?
The other documentation leads me to believe that this is outdated info:
1. The default on the [configuration page](https://duckdb.org/docs/sql/configuration) is null 
2. The [tuning workloads](https://duckdb.org/docs/guides/performance/how_to_tune_workloads.html#prerequisites) page implies it's set automatically IFF the database is persistent (to where?, a new file in the same location as the DB file i would guess?)
3. The [pragma](https://duckdb.org/docs/sql/pragmas#temp-directory-for-spilling-data-to-disk) documentation implies it's always set to /tmp
=> Clarify temp_directory is a dir and not a file

docs/sql/statements/export.md, js/railroad.js, js/statements/alter.js, js/statements/attach.js, js/statements/comment.js, js/statements/createschema.js, js/statements/createsequence.js, js/statements/createtable.js, js/statements/createtype.js, js/statements/delete.js, js/statements/drop.js, js/statements/export.js, js/statements/indexes.js, js/statements/insert.js, js/statements/secrets.js, js/statements/unpivot.js
Merge subsequent keywords to one term (e.g. `IF` `NOT` `EXISTS` => `IF NOT EXISTS`), remove redundant entities, add syntax for `IMPORT DATABASE` statement.
=> Streamline railroad diagrams

docs/api/python/expression.md
=> Python expressions: Add syntax for selecting multiple columns

docs/guides/python/jupyter.md
fix error as follows
```
Using hyphens will be deprecated soon, please use short_trips instead for the save argument.
----- stderr -----
UsageError: Using hyphens (-) in save argument isn't allowed. Please use underscores (_) instead
If you need help solving this issue, send us a message: https://ploomber.io/community
------------------
```
=> fix: replace - with _

docs/api/adbc.md
According to the [release notes for DuckDB 0.10.0](https://github.com/duckdb/duckdb/releases/tag/v0.10.0), the ADBC driver has been updated to version 0.7. The ADBC documentation `docs/api/adbc.md` hasn't been updated to reflect this ADBC version bump, and still references ADBC 0.5.1.
This PR includes:
1. Statement that DuckDB 0.10.0 now uses ADBC version 0.7.0
1. Updated link to ADBC version 0.7.0 documentation
=> DuckDB 0.10.0 release uses ADBC version 0.7 

_posts/2024-01-26-multi-database-support-in-duckdb.md
This was true only on v0.9.2 for the moment the post went out. I think going forward we don't need this.
=> Remove outdated note

css/syntax_highlighting.scss
=> CSS: Resolve ambiguous definition for property (.py)

docs/sql/aggregates.md
Fixes #2342
`any_value` follows the semantics of Google BigQuery, see https://github.com/duckdb/duckdb/issues/4092
=> Explain the difference between the any_value and first/arbitary aggregate functions

_posts/2021-10-29-duckdb-wasm.md
Changes are happening in DuckDB-WASM that will make the COI conversation and this blog post more visible to users. If a user tries to implement the COI headers referencing the headers in the example here it would fail to enable COI and `SharedArrayBuffer` needed for DuckDB-WASM to leverage POSIX threads in the browser. The typo is subtle for a user that is new to these concepts, and they might fail to find the issue even when referring to the web.dev documentation linked.
I'm not sure what the process is for updating a block post that has been published for a while now, but it seems prudent to update this for the users who find and try to use this as a reference in the future.
Besides the web.dev article, I also verified the change after reviewing …
=> Fix typo in COI headers example

css/syntax_highlighting.scss
Should we add an extra color, brown, for properties? I've been going back-and-forth on this formatting detail for a week but ultimately I think it does not make the code more readable or look better.
It's also difficult to differentiate reliable between properties and keywords, e.g. currently the secrets manager's `REGION S3` property is two keywords but the Parquet writer's `COMPRESSION ZSTD` is a property-keyword pair. Let's just color everything as a keyword.
=> CSS: Use the same color for property names and keywords

404.html, _includes/quick_installation.html, css/docu.scss, index.html
- added quick installation to 404 and moved to quick installation snippet to _includes
- made a little and important css fix because of missing margins on docs pages.
=> quick install on 404 page and css fix

docs/extensions/iceberg.md
Added a couple of examples just to highlight other options which can be used to access an iceberg table if you know the manifest path/url to help resolve questions like this. https://github.com/duckdb/duckdb_iceberg/issues/25
=> docs: add examples of addressing a tables manifest directly

docs/sql/statements/attach.md
Small fix in the `ATTACH` docs: The inferred database name for 'file.db' is "file", not "file_db".
=> Correct inferred database name in `ATTACH` query

docs/api/wasm/data_ingestion.md, docs/extensions/httpfs/s3api.md
Sometimes, even after correctly setting up all the credentials for an S3 bucket, a browser may not send requests to the S3 bucket. This issue often arises if you haven't set the correct CORS (Cross-Origin Resource Sharing) headers.
Open the [DuckDB WASM Shell](https://shell.duckdb.org/)
```sql
FROM 'https://ducket-with-cors-header.s3.ap-northeast-1.amazonaws.com/d1.parquet';
```
```sql
FROM 'https://ducket-without-cors-header.s3.ap-northeast-1.amazonaws.com/d1.parquet';
```
You can download the parquet file directly from both URLs. However, only the bucket with the proper CORS header settings can be queried in the DuckDB WASM.
**We should add tips for setting the CORS header in an S3 bucket.**
=> Add CORS tips in s3api

README.md, docs/guides/import/read_file.md, docs/sql/functions/bitstring.md, docs/sql/functions/blob.md, docs/sql/functions/char.md, docs/sql/functions/date.md, docs/sql/functions/datepart.md, docs/sql/functions/enum.md, docs/sql/functions/interval.md, docs/sql/functions/lambda.md, docs/sql/functions/nested.md, docs/sql/functions/numeric.md, docs/sql/functions/regular_expressions.md, docs/sql/functions/time.md, docs/sql/functions/timestamp.md, docs/sql/functions/timestamptz.md, docs/sql/functions/utility.md, single-file-document/concatenate_to_single_file.py
Reformat function tables to only have two columns (name/description) and link to individual function section which have more information (example code, example result, alias(es)).
This PR builds on the style introduced by PR #2529  and using code in #2488.
=> Reformat function tables

docs/api/go.md
I navigated to go.md, and was expecting in some form to find the link to the repository. Unsure if that's the correct spot, or even if the phrase should be turned around, unsure.
=> go.md: link to repository

_posts/2024-03-22-dependency-management.md
Draft PR for a blogpost on dependency management in DuckDB.
TODOs
=> add dependency management blogpost

docs/sql/constraints.md
There was no example on how to set a primary key as an composite of several columns, even though it was mentioned in the text. In my opinion it helps greatly with clarity to give an example outright, as there is no other example (that I could find) that clearly shows a composite key.
I reused the example for a single column primary key to outline the difference when a composite key is used.
Old example:
```sql
CREATE TABLE students(id INTEGER PRIMARY KEY, name VARCHAR);
INSERT INTO students VALUES (1, 'Student 1');
INSERT INTO students VALUES (1, 'Student 2');
-- Constraint Error: Duplicate key "id: 1" violates primary key constraint'
```
New example added after the old example, showing a composite primary key:
```sql
CREATE TABLE students (id INTEGER, name VARCHAR, PRIMARY KEY (id, …
```
=> Update constraints.md with composite key example

docs/sql/constraints.md
Seems like I had duplicated an example in my previous commit:
```sql
CREATE TABLE students (id INTEGER, name VARCHAR, PRIMARY KEY (id, name));
INSERT INTO students VALUES (1, 'Student 1');
INSERT INTO students VALUES (1, 'Student 2');
INSERT INTO students VALUES (1, 'Student 1');
-- Constraint Error: Duplicate key "id: 1, name: Student 1" violates primary key constraint
```
Removed the duplicate.
=> Update constraints.md - removed duplicate of example

_posts/2023-08-04-adbc.md, docs/data/json/overview.md
Just a stray SQL comment that fled to a nearby Bash block.
I took a look at every other Bash annotation in the code base and it seems that this is the only place where the `--` escaped to. For reference:
```bash
rg --multiline ' *```bash(?:.*\n)*? *```' .
```
=> Fix Bash comment in JSON Data Import page

_data/menu_docs_dev.json, _includes/breadcrumbs.html, docs/guides/overview.md, single-file-document/concatenate_to_single_file.py
Guides are under Documentation in terms of URL (`/docs/guides`) but they have a separate place in the left sidebar. This PR moves them under Documentation to make their handling (highlighting the active one, etc.) simpler. URLs do not change.
The next step is moving the Developer Pages under documentation, and the next-next step is disentangling the new `/docs` a bit, may following [Diátaxis](https://diataxis.fr/).
Supersedes #2565
=> Move Guides under Documentation

docs/extensions/httpfs/s3api-legacy-authentication.md
The original AWS S3 documentation, including the virtual host and path information, has been relocated to a new AWS documentation page.
path    https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-bucket-intro.html#path-style-url-ex
vhost   https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-bucket-intro.html#virtual-host-style-url-ex
path    https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#path-style-access
vhost  https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#virtual-hosted-style-access
=> Update AWS S3 doc link

docs/dev/sqllogictest/result_verification.md
document  https://github.com/duckdb/duckdb/pull/11353
=> Doc DuckDB have deprecated the usage of types in the sqllogictest

docs/extensions/mysql.md, docs/extensions/postgres.md
They are rendered incorrectly by Jekyll, making the output unreadable
=> Remove empty Markdown tables

docs/sql/functions/char.md
I believe this is a typo in the description. It said uppercase characters are "smaller" than UPPERCASE characters. I believe its supposed to be uppercase character are "smaller" than LOWERCASE characters. 
p.s. I love DuckDB, thank you all so much for your work.
=> Update char.md corrected typo

_config.yml
Reverts duckdb/duckdb-web#2538 – merge once the JARs deployed successfully to https://mvnrepository.com/artifact/org.duckdb/duckdb_jdbc
=> Revert "Set current Java version to v0.10.0"

why_duckdb.md
The current link has some spurious failures, e.g. https://github.com/duckdb/duckdb-web/actions/runs/8541426715
=> Change link for Chimp paper

index.html
This reverts commit acbc1188497d65b44b0a077190828e84018f103e.
Demo was not functional due to wrong extensions compilation, should be working now.
=> Revert "Spatial: Link to docs from landing page"

_includes/installation.html
There is an issue when installing the duckdb R package on aarch64 systems. For example, on Apple Silicon this:
```bash
docker run --rm -it debian:latest
```
```bash
apt update && apt install -y r-base build-essential
R -e "install.packages('duckdb')"
```
fails with this error:
```
database.o: in function `cpp11::._anon_102::get_preserve_list()':
/tmp/Rtmp2GQPNE/R.INSTALL1b663a54c21c/duckdb/src/../inst/include/cpp11/protect.hpp:397:(.text+0x78): relocation truncated to fit: R_AARCH64_LD64_GOTPAGE_LO15 against symbol `R_NilValue' defined in .bss section in /usr/lib/R/lib/libR.so
/usr/bin/ld: database.o: in function `get_preserve_xptr_addr':
/tmp/Rtmp2GQPNE/R.INSTALL1b663a54c21c/duckdb/src/../inst/include/cpp11/protect.hpp:397: warning: too many GOT entries for -fpic, please recompile with …
```
=> Add aarch64 R package installation warning

docs/sql/functions/nested.md
In fix #[10537](https://github.com/duckdb/duckdb/pull/10537), the output for `list_zip` has changed. I added those changes to the docs and also add information about the `truncate` flag.
=> Update list_zip docs with changes in fix #10537 and add information about truncate flag

docs/sql/functions/nested.md
`&&` aliases to `list_has_any` per https://github.com/duckdb/duckdb/pull/7518
=> Correct the alias for && to reference `list_has_any`

docs/sql/window_functions.md
This change is required... headerless tables current must start with a "Description" field to be rendered correctly in the documentation, see https://github.com/duckdb/duckdb-web/blob/1f6f81d189ddb6d779fe4b6280dff169c6f40be5/single-file-document/concatenate_to_single_file.py#L181-L184
Since starting the tables with the "Description" field makes perfect sense for one that give details window functions, it's easier to make this change than to adjust the script.
=> Reshuffle rows in tables detailing window function

docs/api/java.md
Remove `DuckDBConnection` as it's not used in the example.
=> Simplify JDBC example

docs/api/odbc/windows.md
When updating the ODBC driver, the registry is not always correctly updated, so this PR adds a section on how to check/ adjust it.
Related issue: https://github.com/duckdb/duckdb/issues/11241
=> Add Info on Updating ODBC on Windows

css/syntax_highlighting.scss, js/copy_button.js
- will add $ before all bash code blocks via css. 
- remove copy button on error code blocks.
@szarnyasg important: you need to remove the manually added "$" from the codes.
=> add $ before bash code blocks

docs/api/cpp.md
I tried running the C++ example in the docs, and it gives errors using the current version of the QueryResult class. I have updated the basic example to use the current version of the class and added a simple print for the output.
=> Fix cpp example to conform to current version QueryResult class.

docs/dev/building/troubleshooting.md
The docs suggest adding a flag in the R `Makevars` file to parallelize compilation of the R package of DuckDB.
The line it suggest to add fixes it at 8 threads, but one would usually want to use as many threads as possible. This PR adds such a suggestion for linux systems using `nproc` instead.
=> Suggest using all threads for compilation in R

Gemfile.lock
Makes the repo work with the latest Ruby/Bundler in brew, and also fixes the Docker image (fixes #2937)
=> Bump Bundler version and concurrent-ruby

index.html
This PR disables the spatial demo linked from the landing page for the time being. This PR should be reverted once the demo works again.
cc @carlopi
=> Disable spatial demo

docs/archive/0.10/configuration/secrets_manager.md, docs/configuration/secrets_manager.md
Fixing a small error in the example for `which_secret`
=> which_secret should include a `FROM` as it's a table function

docs/sql/functions/nested.md
Hi,
the example of `list_position` contained a copy paste error. In the example it said `list_contains` instead of `list_position`.
=> Fix small copy-paste error (list_position example)

docs/data/json/overview.md, docs/extensions/json.md
Restructure doc to follow a more "natural" reading experience such that the sections on 'Creation', 'Extraction', 'Scalar Functions' follow that scheme and not the other way round.
=> Restructure json documentation

docs/extensions/azure.md
Title says it all - this is just a minor grammar/spelling fix.
=> Spelling: add missing ⟩ to azure.md

_data/menu_docs_dev.json, docs/guides/offline-copy.md, docs/index.md
The current implementation is taking up too much prime real-estate, let's move it to a guide.
=> Move offline section to a separate guide page

.github/workflows/build-stable-documentation.yml
As we are now specifying links with {% link ... %} Jekyll tags, which fail the site build if the link is incorrect, it makes sense to actually check these for PRs. This will prevent broken internal links to be merged in the repository and will save time in the long run.
=> CI: Add site build step for PRs

_includes/installation.html
The download link showed the "odbc" download for the combination of: _Nightly + CLI + Linux + Direct + x86_64._
See screenshot (highlight from me):
=> Fixed download link for: Nightly + CLI + Linux + Direct + x86_64

.github/workflows/update-docs.yml
The current [C API Reference](https://duckdb.org/docs/api/c/api) documents the v1.0.0 page, therefore, it should not be updated with functions from the latest build (v1.1.0-dev).
=> CI: Disable update docs job

docs/archive/0.10/internals/storage.md
Found this conflicting redirect manually. Issue #3252 documents how automatic conflict finding is broken at the moment.
=> Remove conflicting redirect

docs/api/cli/arguments.md
`~./duckdbrc` → `~/.duckdbrc`.
The former is not a valid path (I believe):
```
$ touch ~./duckdbrc
touch: cannot touch '~./duckdbrc': No such file or directory
```
=> Fixed typo in `-init` argument description

docs/extensions/azure.md
This documents the discussion in https://github.com/duckdb/duckdb_azure/issues/63 about enabling Azure SDK logs in the Azure extension.
=> Document logging in the Azure extension

docs/sql/statements/insert.md
Fix a small typo on the inserts page: `confict_target` to `conflict_target`
=> Docs: sql/statements/insert.md: Fix typo

docs/sql/data_types/array.md
I noticed the link is leading to the wrong page.
=> docs: Array Type: fix link to list functions

docs/archive/0.10/sql/functions/char.md
Statements about case (in)sensitivity were reversed.
=> fix typo in descriptions 'not_like_escape' and 'not_ilike_escape'

docs/sql/functions/numeric.md
`xor` takes 2 arguments. It's probably a typo to introduce it as `xor(x)`.
=> change `xor(x)` to `xor(x, y)`

docs/operations_manual/limits.md
Clarifies limit discussed in [#2859](https://github.com/duckdb/duckdb-web/issues/2859#issuecomment-2326825319)
=> Clarify memory allocation limit

docs/operations_manual/securing_duckdb/securing_extensions.md
These are important security configuration flags that were so far omitted from the "Securing DuckDB" part of the docs – they were only mentioned in the blog and in the configuration flags overview.
=> Add section on disabling autoinstalling/autoloading

docs/dev/repositories.md
Link was erroneously to duckdb-node repo. This PR corrects the link
=> fix link to duckdb-node-neo

docs/sql/statements/copy.md, js/railroad.js, js/statements/copy.js
I've updated both the documentation detailing the list of generic `COPY ... TO` options as well as update the railroad diagram displaying the `COPY ... TO` + `FROM` options, removing ones that are not generic.
Fixes the following issues:
- [APPEND](https://github.com/duckdb/duckdb-web/issues/2910)
- [OVERWRITE / OVERWRITE_OR_IGNORE](https://github.com/duckdb/duckdb-web/issues/2901)
- [FILENAME_PATTERN](https://github.com/duckdb/duckdb-web/issues/2053) (previously fixed but `FILENAME_PATTERN` was not added yet)
- [RETURN_FILES](https://github.com/duckdb/duckdb-web/issues/2924)
=> [Copy] Update the `copy.md` page

docs/api/java.md
The statement was close()'d very late.
Apply try-with-resources to release the statement; this is easier on the eyes and improves code flow.
=> Consistent code style for Appender sample

docs/extensions/spatial/gdal.md
Change
"The spatial extension does not only enable _imporintg_ geospatial file formats (through the ST_Read function), it also enables _exporing_ DuckDB tables to different geospatial vector formats through a GDAL based COPY function."
to
"The spatial extension does not only enable _importing_ geospatial file formats (through the ST_Read function), it also enables _exporting_ DuckDB tables to different geospatial vector formats through a GDAL based COPY function."
=> Update gdal.md to correct typos

docs/sql/introduction.md
DuckDB's documentation right now points to Postgres version 11 instead of Postgres "current".
=> Update introduction.md to point to "current" version of Postgres

docs/dev/building/building_extensions.md
I want to remove the introduction of `BUILD_INET` flag because INET now is a out source tree extension and  in fact  `BUILD_INET` now is not exist.
=> remove BUILD_INET

_posts/2024-02-13-announcing-duckdb-0100.md, _posts/2024-06-20-cli-data-processing-using-duckdb-as-a-unix-tool.md, _posts/2024-09-09-announcing-duckdb-110.md
We have a built-in table of contents ("in this article") now, so these ToCs are redundant.
=> Remove hard-coded ToCs from blog posts

docs/sql/query_syntax/from.md
The documentation says an ANTI JOIN and WHERE NOT IN (...) are equivalent. This is not true when the right table of the ANTI JOIN / subquery of the NOT IN (...) does contain NULL values. 
```sql
create table t1 (id1 integer);
create table t2 (id1 integer);
insert into t1 select id1 from generate_series(1, 1000) tmp1(id1);
insert into t2 select id1 from generate_series(1, 100) tmp1(id1);
insert into t2 values(null);  -- a null value on the right side is the key here
```
```sql
select count(*) as q1 from t1 where id1 not in (select id1 from t2);  
--> q1: 0
```
```sql
select count(*) as q2 from t1 anti join t2 using (id1);
--> q2: 900
--> i.e. WHERE id1 NOT IN (...) is not equivalent to ANTI JOIN
```
```sql
select count(*) as q3 from t1 where id1 not in (select id1 from t2 where id1 is not …
```
=> Describe null handling in anti join

docs/extensions/json.md
The original text, "These functions supports the same two location notations as the previous functions.", seems to have outdated, as there are no JSON location notations referenced in the text above.
=> Fix an ambiguous anaphoric reference

docs/data/csv/overview.md
Describes the current fact that the read_csv function and the COPY statement support different parameters.
=> Describes the current fact that the read_csv function and the COPY statement support different parameters.

docs/sql/expressions/subqueries.md
1.1 throws on scalar subqueries that return multiple rows.
=> Correct statements that are no longer true in 1.1

docs/api/overview.md
add an entry for dart to the third-party duckdb api section.
=> Add Dart wrapper for DuckDB to API overview documentation.

css/docu.scss
We use table headers with left-aligned text.
However, the Markdown to HTML used by Jekyll renders the `text-align` attributes inline. So the following Markdown
```markdown
|  a   | b  |
|-----:|---:|
| 32   | 42 |
| NULL | 22 |
```
gets translated to:c
```html
<table>
<thead>
<tr>
<th style="text-align: right">a</th>
<th style="text-align: right">b</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: right">32</td>
<td style="text-align: right">42</td>
</tr>
<tr>
<td style="text-align: right">NULL</td>
<td style="text-align: right">22</td>
</tr>
</tbody>
</table>
```
This is rendered as follows:
This PR forces left-align for all table headers, resulting in:
=> CSS: Force table headers to be left-aligned

js/statements/load_and_install.js
Looking at the current page it's not clear that we can load extensions from a specified path. This fixes that.
=> Add extension path example to LOAD

docs/data/data_sources.md
The previous Excel link incorrectly led to the MySQL documentation page. It has now been updated to include three distinct links:
* one for the spatial extension
* one for importing Excel files
* and another for exporting Excel files.
=> Fix excel link in data_sources.md

docs/sql/statements/update_extensions.md
Informations are already available at https://duckdb.org/docs/extensions/versioning_of_extensions#updating-extensions, but I think feature might use it's own page.
To be considered adding an explanation of the various return-code, and merging both versions / linking this from INSTALL/LOAD page and possibly elsewhere.
=> Add UPDATE EXTENSIONS page

docs/dev/benchmark.md, docs/dev/building/build_configuration.md, docs/dev/building/build_instructions.md, docs/dev/building/building_extensions.md, docs/dev/building/troubleshooting.md
Connected to this PR https://github.com/duckdb/duckdb/pull/14531 (and other that might follow).
Since already 1.1.0 the `CORE_EXTENSIONS='a;b;c'` is the suggested way to build extensions, and the older BUILD_TPCD & co should be phased out going to 1.2.x. I think it's safe to just remove mentions of `BUILD_`, moving to the new methods. Possibly to be considered a warning tab saying:
> BUILD_HTTPFS=1 & co are being discontinued (although they will still might work).
=> Remove BUILD_ from the documented options

docs/sql/functions/char.md, docs/sql/functions/list.md
Followup to https://github.com/duckdb/duckdb-web/pull/4011, particulary this comment thread https://github.com/duckdb/duckdb-web/pull/4011#discussion_r1828028459
eg `concat_ws(', ', 'Banana', 'Apple', NULL, 'Melon')` results in 'Banana, Apple, Melon', not 'Banana, Apple, , Melon',
=> Clarify that NULLs are skipped, not treated as '', in concat_ws

docs/sql/expressions/star.md
Mentioned how the COLUMNS expression can accept a list of column names. It is already implicitly covered when documenting the expansion of columns expressions, but having it at the top-level examples is more visible.
=> Add column selection via list to star expression page

docs/extensions/spatial/functions.md
Fixes issue https://github.com/duckdb/duckdb-web/issues/4126
=> Fix for Issue #416 (example for ST_Distance_Spheroid)

docs/extensions/iceberg.md
Update the duckdb_iceberg documentation to better describe some of the optional version resolution functionality and document the version guessing behavior provided by https://github.com/duckdb/duckdb_iceberg/pull/79. Also add a table of common parameters at the top of the document for easier reference.
=> Update iceberg.md to reflect new version handling

docs/sql/constraints.md
Hi dear duckdb team, 
I felt that for the example `student_id` is more intuitive than `exams_id`, but maybe I am missing something. 
Best regards,
Paul
=> Changed exams_id to student_id

docs/api/rust.md
I noticed a bit of funky grammar here, so I took a moment to improve it.
=> Clarify Rust shutdown documentation

docs/api/c/vector.md, docs/api/cli/syntax_highlighting.md, docs/extensions/spatial/r-tree_indexes.md, docs/guides/performance/file_formats.md
But table headers are not! Amending this critical issue
=> Most things are headline-capitalized

_layouts/community_extension_doc.html, _layouts/default.html, _layouts/docu.html, _layouts/post.html, _layouts/postarchive.html, js/determine_color_scheme.js
This PR fixes #4269 
It seems the core issue is this piece of code present in the various HTML templates in the [_layouts](https://github.com/duckdb/duckdb-web/tree/main/_layouts) folder:
```html
<script>
var userPrefersDark = localStorage.getItem('mode') === 'dark';
var systemPrefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
if (userPrefersDark || systemPrefersDark) {
document.documentElement.classList.add('darkmode');
document.documentElement.classList.add('disable-transitions');
}
</script>
```
It checks if the user prefers the dark theme, and even if they don't (with the light theme set explicitly), it stills ends up using the dark theme if the system is set to the dark color scheme. 
I have updated this bit of code to check the user …
=> Prefer user selected theme over system theme

docs/sql/statements/set.md
Search path does not support being set globally:
```
D set global search_path = 'foo';
Catalog Error: option "search_path" cannot be set globally
```
See https://github.com/duckdb/duckdb/blob/aa3787b0/src/main/config.cpp#L154.
=> docs: replace broken `SET GLOBAL` example

css/blog.scss
- set iframes to 100% on mobile devices
=> iFrame (YouTube) in Blog Posts too wide for mobile

_includes/landing-page/sql/s3-parquet.sql
Hi dear DuckDB team,
I discovered that the s3 query on the landing page returned a Binder Error, as one column name was incorrect. I am not 100% sure if my change affects the landing page query, but I could not fine the query elsewhere. 
Best regards,
Paul
=> Fixed s3-parquet.sql Binder Error

docs/sql/statements/copy.md
* Adds examples of file extensions for writing with ZSTD for compression
* Wraps instance of gzip with "`"'s so the formatting is consistent among examples
=> add documentation for using zstd for compression for writes

.devcontainer/devcontainer.json
Updated the post-create command in `devcontainer.json` to start Jekyll server, aligning it with our standard Docker run method.
Here I am making it [identical to the docker run method](https://github.com/duckdb/duckdb-web/blob/main/scripts/docker-serve.sh#L21-L24).
The current implementation does not work anyway.
=> Standardize Jekyll Server Startup when using Dev Containers method

docs/api/node_neo/overview.md
Just a one-line typo fix in the Node Neo docs. @szarnyasg
=> node neo typo fix

docs/extensions/vss.md
The examples fail if the extension is not loaded.
=> Update vss.md. add INSTALL and LOAD to example.

docs/api/node_neo/overview.md
Chunks can be null as of this commit:
https://github.com/duckdb/duckdb-node-neo/commit/09d2dddf839fe753552bda3d10012f0a7fb343f2
This PR updates a snippet on the node neo page to match the API changes.
=> Update node-neo API doc snippet with null chunk API change

docs/sql/query_syntax/with.md
1, 2 and 5 doesn't form a directed cycle
1, 8 and 5 does
or 1, 5 and 3.
=> Update with.md with correct example for directed cycles

docs/operations_manual/securing_duckdb/securing_extensions.md
Checks are performed at load time, I think it's somewhat confusing to say install.
=> Update securing_extensions.md: change install to load

docs/data/json/loading_json.md
Right now it's missing from the table: https://duckdb.org/docs/data/json/loading_json#parameters-1
=> Add field_appearance_threshold type

docs/data/json/loading_json.md
`read_json` results in a different output and is discussed later in the document
=> Use read_json_objects in read_json_objects docs

docs/guides/performance/environment.md, docs/guides/performance/how_to_tune_workloads.md
=> Elaborate more on memory requirements

docs/sql/statements/insert.md
This issue tripped me up, and I thought composite primary keys were not supported, until I stumbled upon https://github.com/duckdb/duckdb/pull/9730 which made me realize this limitation had been fixed.
Please let me know if this should go to a different section of the docs, or any other content or formatting changes.
Thanks for maintaining this great project!
=> Clarify DDL syntax to upsert into a composite PK table

docs/data/csv/overview.md
- Remove bloat words "Option to [...]", "Enables [...]", "This option [...]", "This option allows you to specify the [...]", "Specifies the [...]", "Whether or not to [...]", "Set the [...]", "Boolean value that specifies whether or not [...]", "If this option is enabled, [...]", "If set to true, [...]", "It is important to note that [...]"
- Fix and add links to "rejects_scan" and "rejects_table" descriptions
- Fix `filename` description to say that it returns absolute or relative paths depending on the input
- Consistently use `line` to refer to lines of a CSV file, and `row` to refer to records in a DuckDB table
- Mention that `encoding` is not supported by the `COPY` statement
- More precision in `comment` description
- Separate out some aliases that are supported by writer but not …
=> Improve CSV parameter descriptions

data/installation-data-1.1.yml
I don't have arm64 windows machine, but it seems that winget supports arm64 windows.
https://github.com/microsoft/winget-pkgs/blob/bf1b86f08d099af60d0f5ec6c59425b86b87e894/manifests/d/DuckDB/cli/1.1.3/DuckDB.cli.installer.yaml#L22-L27
(Please update #4567 too.)
=> docs: `winget install` supports arm64 windows

docs/sql/data_types/numeric.md
This PR fixes <https://github.com/duckdb/duckdb-web/issues/4521>
I've cherry-picked some interesting information from the PR, focusing on the storage aspect, as that's the most relevant difference between the other integer types (that and the incredibly high amount of digits of course)
Because of that, I've also added `Size in Bytes` to the existing table of integer types.
=> Add docs for VARINT

docs/guides/performance/indexing.md
Fix https://github.com/duckdb/duckdb-web/issues/4522.
=> Improve indexing page

docs/extensions/inet.md
Address https://github.com/duckdb/duckdb-web/issues/3130
=> Implement #3130 Update docs on new INET functions

docs/sql/functions/aggregates.md
Fixes https://github.com/duckdb/duckdb-web/issues/4504.
I added documentation for the `weighted_avg(arg, weight)` function in the `General Aggregate Functions` table, let me know if you think this is a good place, I am also happy to move it.
=> Added Documentation for `weighted_avg(arg, weight)`

_data/menu_docs_dev.json, docs/guides/file_formats/file_access.md, docs/guides/overview.md
=> Document file: protocol

docs/guides/snippets/sharing_macros.md
> duckdb test.duckdb
```sql
CREATE MACRO static_table() AS TABLE
SELECT 'Hello' AS column1, 'World' AS column2;
```
> duckdb
```
attach 'test.duckdb' as test;
select * from test.static_table();
```
The above works as intended.
=> ATTACH support for table macros is available in 1.2

community_extensions/documentation.md
There is a little problem with this query in the [community extensions documentation](https://duckdb.org/community_extensions/documentation)
```sql
SELECT * FROM functions_pre EXCEPT (FROM functions_post) ORDER BY ...;
```
This query does not return new functions because the table names are misspelled. The correct query is:
```sql
SELECT * FROM functions_post EXCEPT (FROM functions_pre) ORDER BY ...;
```
Check https://github.com/duckdb/community-extensions/issues/290
=> Fix new functions detection query

docs/extensions/sqlite.md
PR https://github.com/duckdb/duckdb-sqlite/pull/123 introduced a setting in the DuckDB SQLite extension, `sqlite_debug_show_queries`, to show the queries being sent to the SQLite database in stdout.
This PR adds documentation to the sqlite page on the DuckDB website for that.
=> Add documentation for sqlite_debug_show_queries

css/docu.scss
added css for highlighting table rows on hover in documentation like in blog posts
=> highlight table rows on hover

docs/archive/1.1/guides/performance/environment.md, docs/guides/performance/environment.md
This just fixes a small spelling mistake in the documentation.
=> chore: fix spelling mistake in documentation

docs/clients/cli/dot_commands.md
Hi there! 
I stumbled across this mega useful method for quickly getting output rows from duckdb  by calling `.once |pbcopy` - means that I can paste into other tools without having to faff around with the mouse selecting text and so on. While I'm pretty sure there's a similar method for Linux, my knowledge is out of date - same for Windows. 
Thought it's worth highlighting for other people as it's one of those small little things that turns out to be awesome for day-to-day work. My use case is testing GeoJSON + WKT outputs on maps and matching.
Thanks
Tom.
=> Add tip box: output to clipboard via .once |pbcopy

docs/clients/cli/dot_commands.md
Documents `.larger_number_rendering` CLI option introduced in 1.2 https://github.com/duckdb/duckdb/pull/15031.
I found this option super helpful and thought others might discover it better in the web docs. I took the documentation string as-is from the duckdb repository here: https://github.com/duckdb/duckdb/blob/28c95be6a97f57fedb0746b8a79cfebc5b4fd10a/tools/shell/shell.cpp#L2205. Please let me know if any changes are needed.
NOTE: sorry about the force pushes, I noticed some issues I had in the formatting/spacing of pipes, and the ordering of items.
=> Document .large_number_rendering CLI option.

docs/archive/1.0/api/julia.md
Currently the documentation for the Julia connectors is a bit limited, but there are quite good docstrings. These are available from within Julia's help system, but also build into online docs automatically on JuliaHub This PR adds a link.
=> Julia: Link to API docs generated on JuliaHub

docs/sql/functions/char.md
`1e240` looks like a floating point number. Switch to 654321 which is `9fbf1` in hex.
=> 123456 is a confusing example when formatted as hex 1e240

_data/menu_docs_dev.json, docs/guides/network_cloud_storage/fastly_object_storage_import.md
This is a fairly simple doc PR. It's possible that it falls under the "guides for third-party tools using DuckDB should not be included in the DuckDB documentation." but since you have Cloudflare R2 I thought it might be worth asking. Absolutely no problems if it doesn't meet the criteria.
If it is eligible but you'd like to test it before merging then let me know and I'll set you up test credentials or a test account on Fastly.
=> Add documentation for how to use Fastly's S3 compatible "Object Storage" Product

docs/clients/node_neo/overview.md
`runAndReadUtil` -> `runAndReadUntil` (missing `n`)
=> fix typo in `docs/clients/node_neo/overview.md`

docs/data/overview.md
Before this modification, it was hard to find out how relative paths are expanded in duckdb.
The configuration setting `file_search_path` is a "god sent" when globbing files from a directory tree and needing to reference/harmonize the root of this tree over team members and CD/CI. The added chapter should help others to find this valuable setting more easily than me :).
=> Added file loading chapter on relative paths to import overview

docs/stable/guides/meta/describe.md
=> Fix formatting for Describe Remote Tables

docs/stable/sql/functions/dateformat.md
Combining specifiers %V and %Y gives unexpected results. (always January first)
```
SELECT strptime('2024-39', '%Y-%V');
->
2024-01-01 00:00:00
```
This is because `%V` should be combined with `%G` and not with `%Y`.
Python warns for this, so I guess it would be nice for us to at least explicitly mention it in the docs.
```python
from datetime import datetime
datetime.strptime('2024-37-1', '%Y-%V-%u')
```
=> cross reference specifiers %G and %V for function strptime

docs/0.10/sql/information_schema.md, docs/0.8/sql/information_schema.md, docs/0.9/sql/information_schema.md, docs/1.0/sql/meta/information_schema.md, docs/1.1/sql/meta/information_schema.md, docs/stable/sql/meta/information_schema.md
This came up here - https://github.com/duckdb/duckdb/pull/16419
I'm not entirely sure what this field should contain, but I would say it's not the file system location of the database at least. Postgres says `Applies to a feature not available in PostgreSQL` so safe to mirror that.
=> `sql_path` in `information_schema.schemata` applies to a feature not available in DuckDB

docs/stable/sql/data_types/enum.md
Noticed a typo here while I'm reading the docs https://duckdb.org/docs/stable/sql/data_types/enum#enum-definition
=> fix typo in enum.md

docs/stable/dev/building/unofficial_and_unsupported_platforms.md
Hi, 
Based on https://github.com/duckdb/duckdb/pull/16549, it is feasible to cross-compile DuckDB to RISC-V. 
I would like to add something details to the documentation 
that may be helpful for developers who want to run DuckDB in a RISC-V environment. 
Looking forward to your feedback😉
=> Add cross-compilation instructions for DuckDB on RISC-V platforms

_posts/2024-10-11-duckdb-tricks-part-2.md
In section "Repeated Data Transformation Steps" in DuckDB Blog entry "DuckDB Tricks - Part 2", replace table name "schedule_cleaned" with "schedule".
=> Correct table name in query in "DuckDB Tricks - Part 2".

docs/stable/clients/python/dbapi.md
`duckdb.default_connection` was changed from attribute to function in duckdb 1.2.
=> `duckdb.default_connection` changed from attribute to function in duckdb 1.2

_posts/2024-12-09-duckdb-avro-extension.md, docs/stable/extensions/avro.md
Two changes:
1. Mention avro is supported in Wasm
2. Keep avro as a community extension (no redirect)
I think documentation for community extensions should stay there, without the redirect, but with some clear text saying the extensions will be moved (starting v1.2.2) to `core` extension repository AND will be auto-loadable.
Currently extension is available but not autoloadable, I think it make more sense to say:
* `<= 1.2.1`, it's a community extension
* `>= 1.2.2`, it's a core extension AND autoloadable
That trying to explain the current mix.
=> Fix avro current situation

docs/1.1/extensions/httpfs/s3api.md
Hi maintainers 👋
I'm submitting this PR because I encountered difficulties migrating from the `load_aws_credentials` function to the Secrets Manager.
The equivalent of this command:
```plsql
CALL load_aws_credentials('my-profile');
```
was not clearly explained in the S3 Secrets Manager documentation, which caused some confusion.
The main challenge was understanding how to declare a secret when the Config setup is declaring any default profile or using Environment variables `AWS_PROFILE` or `AWS_DEFAULT_PROFILE`, as the `PROFILE` parameter for S3 secrets was not listed in the Markdown table os S3 Secrets parameters.
After extensive reading and reviewing the [CPP HTML documentation](https://sdk.amazonaws.com/cpp/api/LATEST/aws-cpp-sdk-core/html/namespace_aws_1_1_auth.html#a4fd54f71cf97413fc …
=> Docs - Add migration guide from deprecated load_aws_credentials

.github/workflows/community_extension_docs.yml
See comment here: https://github.com/duckdb/duckdb-web/pull/5206#issuecomment-2788265968
This makes so extension documentations are updated, but list is not (yet)
This is a bit of a hack, and need reverting, but this might work OK for now, allowing new extensions still to have their page.
=> [community-extensions] Avoid overriding extension list

.github/workflows/build-stable-documentation.yml, .github/workflows/jekyll.yml, requirements.txt, scripts/generate_llms_txt.py
Currently, we only have [`llms.txt`](https://duckdb.org/llms.txt) at the root, which is quite minimal.
This PR adds a Python script pipeline to keep `/docs/stable` always up to date:
- `llms.txt`: list of links
- `llms-full.txt`: full content of the linked pages
**Note:**  
@szarnyasg — I noticed you pointed to the `raw.githubusercontent.com` version of the markdown URL on the root `llms.txt`. I have mixed thoughts on this. While [llmstxt.org](https://llmstxt.org) recommends using markdown-friendly URLs, relying on the raw GitHub link could reduce traffic through duckdb.org and hurt its domain authority.
As a workaround, I’ve included both the duckdb.org link and the raw markdown URL for now. Curious to hear your thoughts, @tdoehmen.
=> Add llms.txt and llms-full.txt for /docs/stable

_data/menu_docs_preview.json, docs/preview/extensions/encodings.md
Fixes #5263
We need to write about which functions are supported (e.g., `read_json`?)
To be merged when the extension becomes available
cc @pdet
=> Add page for encodings extension

docs/preview/sql/functions/blob.md, docs/preview/sql/functions/char.md, scripts/generate_sql_function_docs.py
This PR is a continuation of the functionality introduced by https://github.com/duckdb/duckdb-web/pull/5017 and https://github.com/duckdb/duckdb-web/pull/5238
- Compressed function tables.
If a function has optional arguments AND `duckdb_functions()` has the same function description for the different function_overloads there will be a single entry for these functions. Optional arguments will be in brackets: `[, ...]`
- improved examples with multiple spaces
consquitve spaces are removed by HTML rendering; symbol `␣` is used to represent a space, e.g. functions, `trim` and `bar`
`parse_dirname(path[, separator])`
|   |   |
|---|---|
| __Description__ | Returns the top-level directory name from the given `path`. `separator` options: `system`, `both_slash` (default), `forward_slash`, …
=> Compact function tables

docs/preview/data/json/loading_json.md, docs/preview/sql/functions/blob.md
@c-herrewijn in the description of the `md5` function, a repeat word "as" occurs:
```
Returns the MD5 hash of the `blob` as as a `VARCHAR`.
```
I'm not 100% where it is coming from in the DuckDB codebase, would you mind taking a look?
=> Fix repeat words

docs/stable/extensions/spatial/functions.md
Looks some of the keywords were truncated at some point
ELECT -> SELECT
REATE -> CREATE
=> Fixed typo in the ST_Read example section

faq.md
While reading the docs i noticed there's now a development roadmap. This PR adds the link to the FAQ.
Awesome project!
=> Added link development roadmap to the FAQ

docs/preview/core_extensions/overview.md
After https://github.com/duckdb/duckdb/pull/15923 this should no longer be an exception.
R I am not sure if also there they changed settings on extensions they ship.
=> Preview: TPCH no longer packaged in Python

_posts/2025-05-21-announcing-duckdb-130.md, docs/preview/sql/functions/lambda.md, docs/stable/sql/functions/lambda.md
This syntax was inspired by Python, so we should use Python-style syntax in the docs. Python is not case-sensitive, so `LAMBDA` does not work - it has to be `lambda`. 
In addition, the docs appear to be outdated when it comes to multi-parameter lambdas - they no longer require (or work with) parenthesis. This fixes the queries so they are correct again.
=> Use Python standard case-style for lambda

.github/workflows/linkchecker.yml, _data/menu_docs_stable.json, docs/stable/core_extensions/iceberg/amazon_s3_tables.md, docs/stable/core_extensions/iceberg/amazon_sagemaker_lakehouse.md, docs/stable/core_extensions/iceberg/iceberg_rest_catalogs.md, docs/stable/core_extensions/iceberg/overview.md
Describe create create and attach workflow for rest catalogs.
Also remove references to experimental and `FORCE INSTALL`
=> Update iceberg docs

docs/preview/clients/adbc.md, docs/stable/clients/adbc.md
Update to latest published version of arrow-go, now the code example works fine
=> Update adbc docs to use current arrow-go v18

docs/stable/core_extensions/httpfs/s3api.md
Clarify that the credentials for GCS and R2 should be made available as AWS credentials.
=> httpfs: clarify that credentials should be made available for AWS client

docs/1.1/sql/query_syntax/with.md, docs/preview/sql/query_syntax/with.md, docs/stable/sql/query_syntax/with.md
CTE materialization is the "opposite" of inlining. I fixed that sentence.
=> Fix bug in with.md

docs/preview/sql/functions/timestamp.md
* Document make_timestamp_ms.
* Restore erroneously removed epoch_ms(timestamp).
=> epoch_ms follies

docs/stable/sql/statements/use.md
Related https://github.com/duckdb/duckdb-iceberg/issues/324
=> explain that `use` statement uses an implicit 'main' schema if not provided explicitly

docs/preview/clients/adbc.md, docs/stable/clients/adbc.md
Context: apache/arrow-adbc#2216
DuckDB actually supports ADBC API 1.1.0, but the documentation shows the old library version (different from the API version) as 0.7, which is confusing and needs to be updated.
And, the link will be updated to point to the latest version.
=> docs(adbc): remove confusing line and update the link to the arrow adbc docs

.github/workflows/build-stable-documentation.yml, .github/workflows/lint.yml
Currently, if a PR is open and a push happens, the `Build stable documentation` workflow will start running. If, shortly after a subsequent push on the *same* PR happens, the workflow will start running again without cancelling the previous (now obsolete) run. With these changes, the first run would be cancelled, thus **saving compute resources** (see below for quantity) that can be used to **speed up your overall CI/CD**, without sacrificing functionality, since the second run will contain the changes from the first push as well. 🌱
Here is an example of the behaviour described above: the commit `85a31a5` triggered [this](https://github.com/duckdb/duckdb-web/actions/runs/15182549779/) workflow run, and shortly after the commit `425ce39`, that happened on top of the first commit, triggered …
=> [CI]: Cancel CI runs that become obsolete

docs/preview/clients/python/known_issues.md, docs/stable/clients/python/known_issues.md
https://duckdb.org/docs/stable/clients/python/known_issues.html#crashes-and-errors-on-windos
Windows was mistyped as Windos.
=> Fix Typo in Known Python Issues

docs/stable/clients/go.md
This pull request makes the following small changes to the `go.md` file:
1. Updates the reference to `go-duckdb` to use the [latest major version: v2,](https://github.com/marcboeker/go-duckdb/tree/main?tab=readme-ov-file#go-sql-driver-for-duckdb) which supports version 1.2+ of duckdb which is the oldest version available on the doc page. 
- v2.3.3 of `go-duckdb` is the only version that supports the current stable version of duckdb 1.3.2
- v2+ of `go-duckdb` changes the [arrow dependency from opt-out to opt-in](https://github.com/marcboeker/go-duckdb/tree/main?tab=readme-ov-file#the-arrow-dependency-is-now-opt-in) potentially making builds faster
- Allows for scans of JSON into `any` or the `Composite` duckdb type but removes support for scanning JSON directly into a `string` or `[]byte` …
=> Update getting started docs for go on stable version

docs/preview/clients/cli/editing.md, docs/stable/clients/cli/editing.md
Feature was implemented as part of this PR: https://github.com/duckdb/duckdb/pull/11447/
There is some current documentation of it inside of `.help` and `.help .edit` but having it in these docs seems very helpful
That PR limits this feature to linenoise compatible CLI editors. It seems like it will support windows when linenoise comes to the windows duckdb CLI.
=> Update editing.md with external editor section

docs/stable/clients/wasm/instantiation.md
It seems that the `!` postfix was too much, as with it there are errors in the browser console and in js linter. Without it seems to work.
I am missing anything from vite/js/ts or other things that made this `!` necessary?
=> Update instantiation.md by fixing typo in CDN wasm example

_data/menu_docs_preview.json, _data/menu_docs_stable.json, docs/preview/clients/cli/known_issues.md, docs/stable/clients/cli/known_issues.md, docs/stable/clients/cli/overview.md
Hi DuckDB!
This PR addresses https://github.com/duckdb/duckdb/issues/17646, there was not a super obvious place to put this note so I simply added it to the overview page with the noted workaround solution. Unclear if its worth mentioning this caveat for the small user base using WSL and the CLI concurrently, but since the issue was still open and marked for docs I wanted to give it a shot.
=> CLI WSL Memory Note

why_duckdb.md
The old domain appears to have been squatted and now redirects to some kind of Indonesian gambling site: armstrongforoakland[.]com (itself another squatted domain).
=> Fix link to Peloton DB

docs/preview/clients/python/function.md
- Add example for using pyarrow UDFs
- switch from "built-in" to "native" because that is what the function actually expects as an argument
- Explicitly import DATE, etc from `duckdb.types`, don't do a * import
- The pyarrow UDFs accept pyarrow Arrays, not Tables. So fix up that bis of misleading info.
=> Improve python function docs

docs/preview/clients/java.md, docs/preview/clients/node_neo/overview.md, docs/preview/clients/swift.md, docs/preview/clients/wasm/deploying_duckdb_wasm.md, docs/preview/clients/wasm/instantiation.md, docs/preview/core_extensions/spatial/functions.md, docs/preview/data/csv/auto_detection.md, docs/preview/dev/building/building_extensions.md, docs/preview/guides/data_viewers/youplot.md, docs/preview/guides/odbc/general.md, docs/preview/guides/performance/file_formats.md, docs/preview/guides/performance/schema.md, docs/preview/internals/overview.md, docs/preview/operations_manual/non-deterministic_behavior.md, docs/preview/sql/data_types/typecasting.md, docs/preview/sql/expressions/star.md, docs/preview/sql/meta/duckdb_table_functions.md, docs/preview/sql/samples.md, docs/preview/sql/statements/attach.md
Fixes several typos. 
[Spotted with typos-cli](https://github.com/crate-ci/typos) and manually edited (there are many false positives)
=> fix: typos

_data/menu_docs_preview.json, docs/preview/sql/statements/alter_database.md, js/preview/statements/alter_database.js
Adding `ALTER DATABASE` page per: 
- https://github.com/duckdb/duckdb-web/issues/5769 
- https://github.com/duckdb/duckdb/pull/18970. 
- This page users [ALTER TABLE](https://duckdb.org/docs/stable/sql/statements/alter_table.html) as template page and defines the newly merged `ALTER DATABASE` command which as far as I can tell only can be used to rename a database currently.
http://localhost:4000/docs/preview/sql/statements/alter_database#syntax
=> Adding Alter Database page + TOC update

docs/stable/dev/building/python.md
The previous docs were still assuming the Python extension is in-tree. This update might be a bit on the light side / not greatly structured, but at least the docs aren't incorrect anymore. Most people should be able to get going from here on out, I think.
=> Update python dev docs
