duckdb/duckdb-web

docs/api/cpp.md
Hey all,
This PR is a scratch documentation for the C++ UDF API.
=> C++ UDF API

docs/data/csv.md, docs/sql/statements/copy.md
related to https://github.com/cwida/duckdb/issues/962
=> Updated CSV docs

_data/menu.json, docs/sql/statements/create_macro.md, js/statements/createmacro.js, js/statements/drop.js
=> add macro documentation

docs/sql/functions/char.md, docs/sql/statements/select.md, js/statements/select.js
=> Format text functions, add split functions

_data/menu.json, _posts/2021-01-25-full-text-search.md, docs/sql/full_text_search.md, docs/sql/pragmas.md
Document the FTS extension and add a blog post about testing it out on TREC data.
=> FTS extension docs and blog post

docs/sql/aggregates.md
Let me know if I forgot any, and I'll be happy to add them to this PR.
=> Adding aggregation functions

docs/api/python.md
Thanks for duckdb. Just fixing a small typo I noticed.
=> Fix Minor Documentation Typo: "dat" -> "data"

_data/menu.json, docs/sql/aggregates.md, docs/sql/data_types/nested.md, docs/sql/functions/nested.md, docs/sql/window_functions.md, js/expressions/window.js
I had to read the code to figure them out.
=> Document nested functions

_data/menu.json, docs/sql/statements/alter_table.md, docs/sql/statements/create_macro.md, docs/sql/statements/create_schema.md, docs/sql/statements/create_sequence.md, docs/sql/statements/create_table.md, docs/sql/statements/create_view.md, docs/sql/statements/insert.md, js/statements/createschema.js
Documented the `CREATE SCHEMA` command, the default schema, and made some formatting improvements for other statements.
=> Document CREATE SCHEMA

_data/menu.json, benchmarks/arrow.md, benchmarks/index.md, scripts/run_benchmarks.py
This PR adds some initial benchmarking on the Arrow Integration
* Int
* Int + Null
* Strings
* Strings + Null
Let me know if I have missed something on adding the benchmark, I've tested the benchmark itself on one of the jewels and it seemed fine, not sure about the page production.
=> Arrow Benchmarks

docs/api/python.md
=> Fix Two More Minor Documentation Typos

index.html
=> Update index.html: reduce a space

index.html, js/script.js
A hack to make autodetecting the user's OS work.
=> Autodetect user's OS on opening page. Fixes #20

docs/sql/data_types/nested.md, docs/sql/expressions/comparison_operators.md
Document nested type changes, including:
* Construction syntax
* Comparisons and predicates
* Joins and aggregation
Also document the `IS (NOT) DISTINCT FROM` operators.
=> Issue #1791: Nested type operations

docs/api/overview.md, docs/api/rust.md
Close https://github.com/duckdb/duckdb/issues/949
=> add rust api

docs/sql/expressions/subqueries.md
=> Fix table formatting in subqueries page

_data/menu.json, docs/sql/aggregates.md, docs/sql/functions/date.md, docs/sql/functions/datepart.md, docs/sql/functions/interval.md, docs/sql/functions/time.md, docs/sql/functions/timestamp.md
Apply some TLC to the date function documentation.
=> Issue #600: Document temporal functions

docs/sql/aggregates.md, js/expressions/aggregate.js
Also tidy up the examples and add ORDER BY syntax.
=> Issue #1954: Implement LAST

docs/sql/pragmas.md
=> Document progress bar

_config.yml, index.html
=> Bump version, remove limitation of not handling plaintext

docs/sql/aggregates.md
Document new Median Absolute Deviation aggregate.
=> Issue #2425: Implement Moving MAD

docs/sql/functions/nested.md
@lnkuiper @Mytherin I documented the functions/macros introduced in PR https://github.com/duckdb/duckdb/pull/2520
I didn't dwell on whether something is a function or a macro, let me know if the documentation should say something about this.
=> Document list concat function, aliases and related macros

_posts/2021-12-03-duck-arrow.md
=> add apache to title

docs/sql/functions/nested.md, docs/sql/statements/create_macro.md
* Add another `CREATE MACRO` example
* Document the generate_subscripts macro introduced in https://github.com/duckdb/duckdb/pull/2576/
=> Add CREATE MACRO example and document generate_subscripts

README.md
Update the Readme for fellow Windows folks!
=> Windows Jekyll install instructions

_data/menu.json, docs/api/overview.md, docs/api/wasm.md
(Please merge this after the NodeJS docs!)
=> Bare Bones WASM Client API - just links for now

docs/sql/data_types/enum.md
I believe you wanted `DROP TYPE` not `DROP TABLE`.
=> Fixed typo

_data/menu.json, docs/sql/query_syntax/filter.md, js/expressions/aggregate.js, js/query_syntax/filter.js, js/railroad.js
I documented the FILTER clause with some verbiage, some examples, and an updated railroad diagram. I could use some help on additional use cases where we should advise folks to use it. I haven't seen a performance advantage over the CASE WHEN approach, so there are only a few situations where I would recommend the FILTER clause. 
Thanks!
=> Filter clause doc

docs/sql/pragmas.md
Documents the database_size PRAGMA. Following up on https://github.com/duckdb/duckdb/discussions/2914.
=> Document the database_size PRAGMA

docs/sql/query_syntax/with.md, docs/sql/statements/select.md
=> Add examples for recursive CTEs and document nested CTEs

docs/sql/functions/date.md, docs/sql/functions/datepart.md
Also added a few fixes to the formatting of date functions.
=> Fix function name and formatting in datetime functions

docs/sql/functions/char.md
It's currently the only cryptographic function so I put it under string (char) functions.
=> Document the MD5 hash function and sort text function table

docs/sql/functions/date.md, docs/sql/functions/time.md, docs/sql/functions/timestamp.md
We support MAKE_DATE, MAKE_TIME and MAKE_TIMESTAMP in the main code
=> Issue #166: Document MAKE_TEMPORAL functions

docs/sql/functions/nested.md
Additionally array_contains as alias for list_contains
=> Added list_contains to the documentation

docs/sql/functions/nested.md, docs/sql/functions/overview.md, docs/sql/query_syntax/unnest.md
Also, this contains all aliases for `list_contains` and `list_position`. I am not sure that the formatting is correct for the section about the `duckdb_functions`. Please check.
=> Added list_contains, list_position, unnest(null), duckdb_functions

.gitignore, _data/menu_docs_current.json, docs/sql/query_syntax/qualify.md, docs/sql/statements/select.md, js/query_syntax/qualify.js, js/railroad.js, js/statements/select.js
This also contains some changes to the select page's order and the summary of the SQL clauses.
=> Qualify clause docs and railroad diagrams

docs/archive/0.2.8/sql/data_types/nested.md, docs/archive/0.2.9/sql/data_types/nested.md, docs/archive/0.3.0/sql/data_types/nested.md, docs/archive/0.3.1/sql/data_types/nested.md, docs/archive/0.3.2/sql/data_types/struct.md, docs/sql/data_types/struct.md
- Fix a small typo in Struct examples.
=> Fix Struct example typo

docs/sql/functions/nested.md
This can be merged as soon as the PR with the new feature gets merged.
=> Documentation of the list aggregate function

docs/connect.md
Link is malformed, i believe this will fix it
=> fix broken "API docs" link

docs/sql/statements/create_table.md
minor spelling fix to create_table docs comment.
=> minor spelling fix

docs/installation/index.html
The correct address for version 0.3.3.
=> 0.3.3 client for osx - download address

_data/menu_docs_current.json, docs/guides/index.md, docs/guides/python/export_arrow.md, docs/guides/python/import_arrow.md, docs/guides/python/sql_on_arrow.md
Hi Folks!
Let me know what you think! I followed the Pandas guides as an example. 
I didn't even know about Arrow Scanners, so that's worth knowing! Quick random question for my own learning: any idea on the speed of using an Arrow Scanner vs. just querying a dataset directly with DuckDB using a where clause? Arrow mentions that they use Async IO, so I didn't know if that would have any impact.
=> Python Arrow How-To-Guides

_data/menu_docs_current.json, docs/guides/index.md, docs/guides/python/ibis.md
I based this guide somewhat on the Ibis Introduction Tutorial, but I added an example of mixing in a SQL statement with Ibis expressions. Please let me know if you have any feedback! If anyone on the Ibis side has advice that would be great as well! (copying @cpcloud) This is just meant to give a flavor of Ibis and help get folks started.
=> Ibis How-To-Guide

docs/extensions/full_text_search.md
As a follow-up of https://github.com/duckdb/duckdb/issues/3543
=> Add caveat for FTS index

docs/sql/statements/create_table.md
Enhances the create table docs a little bit. Still TODO in another PR is to document Foreign Keys. This closes #181.
=> Document Temp tables, create or replace, if not exists

docs/sql/data_types/date.md, docs/sql/data_types/timestamp.md, docs/sql/functions/date.md, docs/sql/functions/timestamp.md
Document new special values for dates and time stamps.
=> Infinite time support

_layouts/post.html
Fixes #92
I figure it makes the most sense in the post template?
=> feat: add link to atom rss feed

docs/api/cli.md, docs/api/cpp.md
Small addition to add examples of prepared syntax in the CLI and C++ API.
=> Add C++ and CLI documentation for prepared statements

docs/api/julia.md, docs/api/overview.md
mostly taken from the julia package README.md in the main duckdb repo
=> feat: add basic julia page to docs

docs/api/python/reference/index.md
=> feat: add new substrait methods to python docs

_posts/2022-01-06-time-zones.md, docs/sql/data_types/timestamp.md
The time zone name is `America/Los_Angeles`
=> Fix time zone name

.github/workflows/update-docs.yml, README.md, package-lock.json, package.json, scripts/generate_all_docs.sh
To reduce the work required everytime we change something in the other repo
=> feat: add update-docs.yml workflow

_data/menu_docs_current.json, docs/extensions/httpfs.md, docs/guides/import/s3_export.md, docs/guides/import/s3_import.md
Added some updated documentation for the httpfs extension.
=> Updated httpfs documentation

docs/sql/functions/nested.md
=> Fix typo for struct_insert description.

.github/workflows/jekyll.yml
This is a slightly modified version of https://github.com/actions/starter-workflows/blob/main/pages/jekyll.yml
=> feat: add jekyll.yml workflow

css/normalize.css, docs/sql/aggregates.md, docs/sql/window_functions.md, js/railroad.js
Also disable font ligatures for code blocks so `!=` does not render as `≠`
=> Add examples to aggregate/window functions

_data/menu_docs_current.json, docs/guides/index.md, docs/guides/python/polars.md
Mixing and matching Polars, DuckDB, Arrow, and Pandas!
=> Python DuckDB to Polars How-To-Guide

docs/data/csv.md
It's a precious thing, but still undocumented ( [#4619](https://github.com/duckdb/duckdb/discussions/4619#discussion-4363600) )
=> CSV import: I added the stdin mode

docs/extensions/substrait.md
while the repo is private, we should continue to host the docs somewhere
=> feat: restore substrait docs

why_duckdb.md
based on instructions at https://github.com/duckdb/duckdb/issues/4908#issuecomment-1271134857
=> Added to "Other Projects"

_data/menu_docs_current.json, docs/sql/data_types/timestamp.md, docs/sql/functions/date.md, docs/sql/functions/dateformat.md, docs/sql/functions/timestamp.md, docs/sql/functions/timestamptz.md
Document missing functions and string casting.
=> Issue #330: TIMESTAMPTZ Functions

_posts/2022-10-12-modern-data-stack-in-a-box.md
Current link to NBA blog post is not marked up by default. 
Add hyperlink to make the link more visible.
=> Update hyperlink to NBA blog post.

docs/sql/functions/numeric.md
Hi,
This PR fixes a minor typo in the documentation.
Best,
Philipp
=> Fix typo in documentation

_includes/installation.html
=> Remove unnecessary tabs (typo)

docs/sql/functions/char.md
See https://github.com/duckdb/duckdb/pull/5028
=> Add documentation for new _grapheme functions

docs/csv_import.md
Updated the docs with an option that was missing
=> Add documentation for the IGNORE_ERRORS option in the csv reader

docs/sql/functions/timestamp.md
=> Issue #360: Document epoch

docs/sql/indexes.md
Made the following changes:
1. a instead of an
2. corrected index name
=> corrected typing and grammar mistakes

_data/menu_docs_current.json, docs/sql/functions/enum.md, docs/sql/functions/timestamp.md, docs/sql/functions/timestamptz.md
Added documentation for enum functions (`enum_first`, `enum_last`, `enum_range`, and `enum_range_boundary`).
Also fixed fonts in functions/timestamp.md and functions/timestamptz.md.
I hope it is acceptable.
Thanks!
=> Add enum functions docs

_data/menu_docs_current.json, docs/guides/index.md, docs/guides/python/vaex.md
Adding a guild on how to use DuckDB with Vaex DataFrames via Apache Arrow. Feedback welcome.
Thanks. 
cc: @maartenbreddels
=> Python DuckDB to Vaex How-To-Guide

docs/extensions/postgres_scanner.md, docs/extensions/sqlite_scanner.md
Inline + extend the docs from the repository
=> Postgres + SQLite scanner docs

docs/api/cli.md
=> Update CLI docs

js/search.js
=> Fix infinite loop in search

_data/menu_docs_current.json, docs/extensions/sqlite_scanner.md, docs/guides/import/query_postgres.md, docs/guides/import/query_sqlite.md
Short guides about using the SQLite & Postgres extensions
=> SQLite & Postgres Scan Guides

_data/menu_docs_current.json, docs/sql/query_syntax/setops.md, js/query_syntax/setops.js
This was still missing from our documentation
=> Document Set Operations

docs/sql/data_types/map.md
Change proposed in this pull request:
* Update to 1-based index on [Retrieving from Maps](https://duckdb.org/docs/sql/data_types/map#retrieving-from-maps) example
related to
* https://github.com/duckdb/duckdb/issues/3447
=> Update to 1-based index when retrieve a map value

docs/sql/data_types/timezones.md, docs/sql/functions/timestamp.md, docs/sql/functions/timestamptz.md
AT TIME ZONE
DATE_PART structs
2022f Time zone list
=> Issue 5314: Update Timezone Documentation

docs/sql/functions/char.md
Added `starts_with` function and equivalent operator `^@`, that are marged into duckdb/duckdb feature branch.
[#5334](https://github.com/duckdb/duckdb/pull/5334)
Also fixed font in the same file.
=> Add starts_with function and operator doc

docs/api/cli.md
Added .help command results based on duckdb/duckdb master branch.
Also trimed extra spaces at the end of lines.
=> Add .help command results

_layouts/post.html, css/blog.scss, css/main.scss, css/mobilestyles.scss, news/index.html
changed blog post collection view to new layout.
=> changed blog post overview

README.md
The web site link does not work correctly.
=> Hotfix of README.md

index.html
Is still confusing people, see e.g.:
https://github.com/duckdb/duckdb/issues/77
https://github.com/duckdb/duckdb/issues/5317
=> Clarify multiprocess read/write support

docs/sql/configuration.md
=> Add RESET documentation

dev/sqllogictest/intro.md
=> Improve docs on the `unittest` binary usage

docs/sql/statements/create_macro.md
Mention table macros in the create macro doc.
Closes #248
=> Table macro

docs/sql/functions/timestamptz.md
Also collect local time operations into their own section.
=> Issue #5712: Document localtimestamp

.github/workflows/jekyll.yml, docs/sql/pragmas.md, internals/storage.md
Fixes #177 
Fixes https://github.com/duckdb/duckdb/discussions/5730
=> feat: document storage info

docs/sql/aggregates.md
Fixed incorrect function name in `bool_or` function example
=> Fix bool_or example

docs/sql/data_types/enum.md
Small update to the enum documentation so users can see how to create an enum from a `csv`, `parquet` etc. file.
=> Add documentation on how to create enums from data file

docs/extensions/postgres_scanner.md
I only found it by looking at source:
https://github.com/duckdblabs/postgres_scanner/blob/70a6eb867207599e6cb9225d22f09c55d973dd00/postgres_scanner.cpp#L1063
=> Document POSTGRES_SCAN_PUSHDOWN usage

docs/data/parquet.md, docs/sql/statements/copy.md, docs/sql/statements/export.md, js/railroad.js, js/statements/copy.js, js/statements/export.js
Added the row_group_size parameter to the parquet data import page. Also added a paragraph about how to choose what to set it to.
=> row_group_size parameter

docs/sql/aggregates.md
Adds a row for the `ANY_VALUE` aggregate added in https://github.com/duckdb/duckdb/pull/4259.
Resolves https://github.com/duckdb/duckdb-web/issues/495
=> Add ANY_VALUE aggregate to docs

docs/sql/data_types/map.md
This PR updates the information regarding MAP type.
=> Update map type docs

README.md
@kvnkho, @Mause - would this have helped with #488 ? Also removed webrick since it will be added to the gemfile by another PR.
=> Mention .ruby-version and remove webrick

docs/sql/functions/char.md
This PR adds docs on `bar` function that was merged into duckdb master branch in [PR 5993](https://github.com/duckdb/duckdb/pull/5993).
=> Add bar function docs

_data/menu_docs_032.json, _data/menu_docs_033.json, _data/menu_docs_034.json, _data/menu_docs_040.json, _data/menu_docs_051.json, _data/menu_docs_current.json, data/search_data.json, docs/api/overview.md, docs/api/wasm.md, docs/archive/0.3.2/api/overview.md, docs/archive/0.3.2/api/wasm.md, docs/archive/0.3.3/api/overview.md, docs/archive/0.3.3/api/wasm.md, docs/archive/0.3.4/api/overview.md, docs/archive/0.3.4/api/wasm.md, docs/archive/0.4.0/api/overview.md, docs/archive/0.4.0/api/wasm.md, docs/archive/0.5.1/api/overview.md, docs/archive/0.5.1/api/wasm.md
A nitpick, but I think it's better to side with the spec here: https://webassembly.github.io/spec/core/intro/introduction.html
=> Wasm capitalization

docs/extensions/json.md, docs/sql/statements/copy.md
=> Document 0.7.0 JSON functionality

_posts/2023-02-13-announcing-duckdb-070.md
=> Latest version of blog post

_config.yml
Maybe this should be part of the archive script?
=> chore: update versions

docs/api/cli.md
This PR adds descriptions about output formats like duckdox.
=> Add descriptions about output formats

js/statements/attach.js
Fixes https://github.com/duckdb/duckdb-web/issues/559
=> Add type to attach railroad diagram

docs/extensions/json.md, why_duckdb.md
=> Update JSON docs for 0.7.1 and add yyjson to shoulders of giants

docs/api/cli.md
=> CLI:stdin/stdout, duck head prompt,direct commands

_posts/2023-03-03-json.md
=> Implement some more feedback

docs/sql/functions/patternmatching.md
Add an example of using regex flag and link to more docs on RE2
=> pattern matching flag example and RE2 link

scripts/generate_config_docs.py
per
https://github.com/duckdb/duckdb-web/commit/2d9a46cfc2b8f478a0935abdfbf1c46c748f0a50
=> fix: update calendar config overrides

docs/sql/window_functions.md
Just fixed this and noticed it wasn't documented.
=> Issue #6635: Document IGNORE NULLs 

docs/sql/functions/char.md
=> Add `regexp_extract` and `regexp_extract_all`

docs/data/csv/overview.md
=> document new_line csv reader option

docs/api/wasm.md
I believe this will fix the iframe issues.
=> wasm.md: Fix CSS for iframe

docs/sql/query_syntax/from.md, js/railroad.js
And other joins too.
Also, fix railroad for CROSS JOIN.
=> Issue #3423: Document POSITIONAL JOIN

.github/linkchecker/linkchecker.conf, .github/workflows/jekyll.yml, _includes/iframe.html
This should solve a bunch of non-relevant failures (like https://cs.brown.edu/~ugur/fits_all.pdf, see https://github.com/duckdb/duckdb-web/actions/runs/4560276321).
Plus a minor change to iframe.
=> Linkchecker + minor fix on iframe

_data/menu_docs_dev.json, docs/api/odbc/macos.md
Hello, I use odbc on MacOS and I add the documentation. I only tested it with unixODBC built from homebrew.
I know there is an another solution to use odbc on MacOS but I will try later.
=> Add MacOS section for ODBC

README.md, _data/menu_docs_dev.json, docs/extensions/httpfs.md, docs/sql/functions/bitstring.md, docs/sql/functions/datepart.md, docs/sql/functions/enum.md, docs/sql/functions/interval.md, docs/sql/statements/attach.md, docs/sql/statements/call.md, docs/sql/statements/set.md, docs/sql/statements/use.md, docs/sql/statements/vacuum.md, js/statements/call.js, js/statements/set.js, js/statements/use.js, js/statements/vacuum.js
Several updates are made under this PR.
* I alphabetized a lot of the section of the docs menus. Not all as some made more sense to leave as-is (for instance the Query section).
* Documentation was added for the following statements: CALL, SET, VACUUM, USE
* Documentation was added for specifying S3 configuration values in the S3 URL
* A few other small, miscellaneous changes.
I didn't update the search files as I'm going to be lazy and let the Github action handle that.
=> Various doc updates

docs/sql/functions/timestamptz.md
=> Correct age examples

docs/sql/query_syntax/from.md
This was [confusing someone](https://github.com/duckdb/duckdb/issues/7272).
=> Document ASOF USING behaviour

docs/sql/query_syntax/from.md
Clean up the description of the ASOF variants.
=> Issue #732: ASOF USING Examples

docs/data/multiple_files/overview.md
Added some examples of how to use `**` for csv, parquet.
And added a row to the wildcard table
=> added support for ** glob

docs/data/multiple_files/overview.md
=> changed that one character

docs/sql/functions/nested.md
Add the description and example of extra parameters in array_aggr.
=> Allow extra parameters in array_aggr

docs/data/json/overview.md, docs/extensions/json.md, docs/guides/import/json_export.md
=> Update JSON docs to 8.0 functionality

docs/data/partitioning/hive_partitioning.md, docs/data/partitioning/partitioned_writes.md
replaced flag `allow_overwrite` with `overwrite_or_ignore`
added auto detection by default for hive partitioning
added flag `filename_pattern`
=> hive partitioning

docs/sql/query_syntax/from.md
Anti and semi joins are in 0.8.0 but the docs have not yet been updated. 
https://github.com/duckdb/duckdb/pull/6480
=> Update docs with semi and anti joins

_data/menu_side.json, internals/vector.md
This PR fixes #766 
Maybe this could still use a special mention of the `ArrowAuxiliaryData`
=> Add `Vector` docs

docs/sql/data_types/overview.md
The order of scale and width was inverted.
=> Fixed the doc for Decimal data type

_data/menu_docs_dev.json, docs/guides/import/excel_export.md, docs/guides/import/excel_import.md, docs/guides/index.md
This is such an awesome bonus goodie from the spatial extension! Huge thank you to @Maxxen!!
=> Excel import and export how-to-guides

docs/sql/functions/nested.md
Resolves https://github.com/duckdb/duckdb-web/issues/789
=> Add missing map functions

dev/profiling.md
Fixes https://github.com/duckdb/duckdb/issues/7704
=> Clarify file output in profiling.md

docs/sql/statements/insert.md
Should fix #600.
@Tishj , mind having a quick look?
=> Clarify when conflict_target is optional

docs/sql/functions/nested.md
PR was merged against feature, so should wait a bit more to go in.
This fixes https://github.com/duckdb/duckdb/issues/7936
This commit will have to be reverted once dev docs will map to feature.
=> Revert PR #809 on list_intersect & all

docs/sql/statements/create_macro.md
- fix missing keyword argument
=> fix macro sample

docs/sql/statements/update.md, js/statements/update.js
Should fix #686
Someone mind taking a quick look to make sure this covers what we need? Thanks!
=> update table alias and update from same table

docs/sql/statements/copy.md
=> Revert "Document parquet writer FIELD_IDS"

docs/data/partitioning/hive_partitioning.md, docs/extensions/httpfs.md, docs/sql/functions/nested.md
=> Standardize on read_parquet instead of parquet_scan

docs/sql/query_syntax/groupby.md, docs/sql/query_syntax/grouping_sets.md, docs/sql/query_syntax/orderby.md, js/railroad.js
Finally documenting this! This closes #799.
=> Group by ALL / Order by ALL

docs/sql/functions/nested.md
This reverts commit ff5de21b101b3ca16147cbf0d4d741627d0a913a.
=> Revert "Revert PR #809 on list_intersect & all" [FEATURE only]

docs/sql/statements/copy.md
Sorry for this hassle! This should only be merged once feature is merged into master.
=> Redo field_ids docs

_data/menu_docs_dev.json, docs/sql/statements/create_type.md, js/statements/createtype.js
Disclaimer that I learned all of this from the discord (thanks Elliana and __Alex__!) and trial and error, not from actually reading the source or a grammar file.
Also please feel free to cut down the railroad diagram or examples if you feel like I went a little overboard with it - I just noticed that there wasn't any mention of being able to create structs or unions elsewhere and wanted to be specific about them since the syntax is a little more involved than "just write the type identifier".
=> Add documentation for the 'Create Type' statement

.github/workflows/jekyll.yml, _plugins/duckdb_functions.rb, docs/test.md
This isn't integrated into the actual website yet, probably needs some fine tuning (and support for search index generation as well)
@szarnyasg this is in response to our conversation the other day
=> Add Jekyll plugin to render function docs

docs/sql/functions/numeric.md
I was unable to find a documentation entry for it anywhere. The example is based on the one for `ln`
=> add doc for exp

docs/sql/functions/numeric.md
=> fix: atan2

docs/api/python/dbapi.md
=> Document fetchone transaction behavior

docs/archive/0.7.1/data/csv/auto_detection.md, docs/data/csv/auto_detection.md
=> Fix csv delimiter example

docs/sql/aggregates.md
=> Add covar_samp function

docs/data/partitioning/hive_partitioning.md
=> hive_types

.github/styles/USEnglish/use-of-comma.yml, .github/workflows/vale.yml, .vale.ini
=> Add Vale to CI

_data/menu_docs_dev.json, docs/api/adbc.md
=> ADBC API documentation

docs/sql/aggregates.md
Feature is under review in https://github.com/duckdb/duckdb/pull/8471
=> Document geomean

docs/guides/data_viewers/tableau.md
Fix AppleScript example image link.
=> Issue #926: Tableau Taco Documentation

docs/guides/data_viewers/tableau.md
=> Fix taco image embed

code_of_conduct.md, dev/sqllogictest/result_verification.md, docs/api/odbc/macos.md, docs/data/csv/auto_detection.md, docs/data/multiple_files/overview.md, docs/data/partitioning/hive_partitioning.md, docs/extensions/spatial.md, docs/guides/data_viewers/tableau.md, docs/guides/data_viewers/youplot.md, docs/guides/import/s3_import.md, docs/guides/python/jupyter.md, docs/guides/python/multiple_threads.md, docs/guides/sql_features/full_text_search.md, docs/sql/aggregates.md, docs/sql/data_types/interval.md, docs/sql/duckdb_table_functions.md, docs/sql/introduction.md, docs/sql/statements/insert.md, docs/sql/statements/pivot.md, why_duckdb.md
Running the docs through Vale with spelling issues turned out a number of spelling typos
=> Fix some typos

js/statements/drop.js
From https://github.com/duckdb/duckdb/issues/8494
=> add missing rail branches for drop

requirements.txt, scripts/archive_docs.py
=> Rewrite redirect clauses in archive script. Fixes #905

_includes/menu_secondary.html
=> Secondary menu should point to stable release

docs/sql/statements/alter_table.md, docs/sql/statements/create_table.md
=> Document CHECK and FOREIGN KEY constraints

docs/sql/query_syntax/select.md, docs/sql/statements/select.md
=> Clarify DISTINCT ON's performance implications

dev/profiling.md
=> Rework Profiling page

docs/api/python/overview.md
Added a sentence to mention the minimum Python version, fixes #996.
My first PR! Any feedback welcome ^_^
=> Minimum python version documentation

_data/menu_docs_dev.json, docs/extensions/autocomplete.md
=> Add documentation for the AutoComplete extension

docs/guides/python/sql_on_arrow.md
Related to https://github.com/duckdb/duckdb/issues/7647
=> Correct link to Arrow docs

docs/sql/query_syntax/from.md
=> Fix FROM page, add TPC-H tables

_data/menu_docs_dev.json, docs/extensions/iceberg.md
=> Add Iceberg page

docs/extensions/substrait.md
I took a pass over the Substrait page. @pdet who would be a good candidate to review this PR?
The link to https://github.com/duckdblabs/substrait is currently in a comment, shall we uncomment it?
=> Rework Substrait page

docs/sql/data_types/timestamp.md
=> Add missing timestamp types

docs/guides/python/ibis.md
We got a report from a user on the Ibis issue tracker: https://github.com/ibis-project/ibis/issues/6652
The Ibis guide for DuckDB is broken and fairly outdated. I've ported over our getting started tutorial with some minor edits. Very open to any feedback!
=> docs: update Ibis guide

_data/menu_docs_dev.json, docs/sql/statements/alter_table.md, docs/sql/statements/alter_view.md
=> Add 'Alter View' page and document ALTER...NULL constraints

docs/sql/statements/pivot.md, docs/sql/statements/unpivot.md
=> Add LIMIT and ORDER BY clauses to PIVOT/UNPIVOT statements

docs/sql/query_syntax/from.md
=> Document LATERAL joins

_posts/2023-08-23-even-friendlier-sql.md
=> Even friendlier fixes

scripts/archive_docs.py
=> Archive installation page

docs/sql/expressions/comparison_operators.md
=> Fix description of 'IS DISTINCT FROM' and 'IS NOT DISTINCT FROM'

js/statements/alter.js
Fixes https://github.com/duckdb/duckdb-web/issues/1068
=> Add IF NOT EXISTS for ALTER

docs/sql/query_syntax/from.md
A small & trivial improvement.
=> Expand FROM page with SELECT t FROM t

docs/sql/query_syntax/with.md, js/railroad.js
Documents the feature introduced in https://github.com/duckdb/duckdb/pull/7126, written mostly by @kryonix.
Will fix #1067
=> Document WITH RECURSIVE ... [[NOT] MATERIALIZED]

dev/building.md
=> Extend build guide

docs/api/python/function.md
Removed repeated import and added in missing type='native'.
=> Repeated import and missing type='native'

_layouts/docu.html, css/copy_button.scss, css/docu.scss, css/main.scss, js/copy_button.js, js/script.js
- code blocks same width as tables
- Page Source button only visible in /docs/
- adjusted scroll position on hash-links
- hash-links on FAQ-page will expand the paragraph
- fixed copy button on installations page
=> design adjustments

docs/sql/functions/timestamptz.md
Cut and paste error.
Fixes #1144
=> Issue #1144: Document current_localtime

building.md
Fixes #1090. My previous PR #1097 only partially fixed the issue, this one does it properly.
=> Document Ruby installation

README.md
Use the same logo in the README as in the other repos.
=> Use logo with 'vertical' layout

README.md
=> Use SVG logo

docs/data/json/overview.md, docs/extensions/json.md
Rework the JSON pages for a consistent style.
=> JSON extension guide: Formatting

css/main.scss
=> corrected line spacing between menu items

_data/menu_docs_dev.json, docs/extensions/aws.md, docs/extensions/azure.md, docs/extensions/excel.md, docs/extensions/official_extensions.md
Add AWS and Azure pages, towards #1190
=> Add new extension pages

docs/api/r.md
We shouldn't be so mysterious...
=> R API page: Add package name

.github/workflows/jekyll.yml
=> CI: Debug link checker

docs/sql/functions/utility.md
=> Add error function to utility functions

_posts/2023-09-15-asof-joins-fuzzy-temporal-lookups.md
@hawkfish I made a few changes to the AsOf blog post: The first three are cosmetic changes / nits, the fourth commit 0ace45db81f6d05691ffbd3d0b879307fecf5d31 fixes issue #1204.
=> AsOf blog post fixes

.github/linkchecker/linkchecker.conf
=> Linkchecker ignore redirects

docs/guides/python/filesystems.md
It's been pretty stable and unchanged
=> Update filesystems.md to remove experimental warning

dev/building.md
=> Add troubleshooting step for httpfs extension and Python package

docs/sql/indexes.md
Tracks https://github.com/duckdb/duckdb/pull/9030
=> Document force_index_join PRAGMA on the indexes page

_includes/installation.html, js/script.js
=> fix: installartion -> installation

.github/workflows/jekyll.yml
Fixes https://github.com/duckdb/duckdb-web/issues/1241
=> Don't run github pages setup on forks

_data/menu_docs_dev.json, docs/api/python/spark_api.md
=> Add page stub for Spark API

docs/api/wasm/extensions.md, docs/extensions/autocomplete.md, docs/extensions/azure.md, docs/extensions/excel.md, docs/extensions/full_text_search.md, docs/extensions/iceberg.md, docs/extensions/json.md, docs/extensions/spatial.md, docs/extensions/substrait.md
=> Improve extension pages

docs/api/c/overview.md, docs/api/nodejs/overview.md, docs/api/odbc/overview.md, docs/api/overview.md, docs/api/python/overview.md, docs/api/wasm/overview.md, docs/data/csv/overview.md, docs/data/json/overview.md, docs/data/multiple_files/overview.md, docs/data/overview.md, docs/data/parquet/overview.md, docs/extensions/overview.md, docs/sql/data_types/overview.md, docs/sql/expressions/overview.md, docs/sql/functions/overview.md, docs/sql/statements/overview.md, single-file-document/concatenate_to_single_file.py
Add Pages in This Section header where applicable.
=> Pages in This Section

js/script.js
=> Drop '.html' from pathname when appending to 'Pages in This Section'

docs/data/csv/overview.md
=> Specify that the columns needs to align with the schema when COPYing to CSV

_data/menu_side.json, _data/secondarymenu.json, media.md, why_duckdb.md
=> Spin out Media section to its own page

js/script.js
Applying suggestion https://github.com/duckdb/duckdb-web/pull/1273#discussion_r1338042319
=> Scope selector

_data/menu_docs_dev.json, docs/sql/case_sensitivity.md, docs/sql/query_syntax/select.md, docs/sql/statements/select.md
=> Add rules for case sensitivity

docs/extensions/spatial.md
It was a while ago since I did this so let me know If I missed something in the workflow.
=> Update spatial docs

docs/sql/expressions/subqueries.md
Followup of #1073 which was quite shallow.
=> Document subquery as a struct in the subqueries page

docs/sql/functions/datepart.md
=> Fix description of dayofyear

docs/sql/functions/char.md
=> Document fmt syntax

docs/sql/data_types/enum.md
Fixes https://github.com/duckdb/duckdb/issues/9190 from the docs end.
=> Fix enum / DROP TYPE documentation

_includes/installation.html, css/docu.scss, css/main.scss, docs/archive/0.9.0/installation/index.html, js/script.js, why_duckdb.md
- corrected typo / class name on installation page environment/evironment
- added anchors to "Why DuckDB" page
- fixed unordered lists
- fixed font-sizes of code in headline
=> minor bug fixing

_data/menu_docs_dev.json
Moved ADBC and ODBC to the bottom.
=> Reshuffle client APIs

css/docu.scss
Described here https://github.com/duckdb/duckdb-web/issues/1343 (black text on black table background)
=> Update docu.scss - Change color on table header

_layouts/docu.html
Fixes #1328
Needs to sanitize both HTML link and the website title when pasting them to the query string of `.../issues/new`.
=> Add 'Report Issue' button

_layouts/default.html
=> Fix title on landing page

docs/sql/expressions/subqueries.md
=> Document NOT EXISTS operator

_layouts/docu.html, css/docu.scss, css/main.scss, docs/index.md, docs/sql/data_types/date.md, js/script.js
- css improvement
- make tables auto width, using <div class="narrow_table"></div> before table starts
- smaller tables will be automatically auto width
- sticky headline bar in documentation
=> minor improvements

css/docu.scss, js/script.js
- fix space, narrow table follows code
- fixed scroll position for anchor links.
=> minor fixes

_includes/installation.html
Note that registration to the winget-pkgs repo is done by someone (like microsoft/winget-pkgs#122395), but in practice this can be done semi-automatically by anyone using [Komac](https://github.com/russellbanks/Komac) or something.
=> add `winget install` to installation DuckDB Command Line for Windows

_config.yml
=> Turn off inline syntax highlighting

docs/extensions/overview.md
=> Explain 'extension_directory' configuration option in extensions overview page

docs/sql/functions/nested.md
=> Fix nested functions page

docs/sql/data_types/interval.md, docs/sql/introduction.md
Fixing this critical issue, where two headlines didn't conform to the Chicago style
=> Fix headline capitalization

_data/menu_side.json, internals/repositories.md
=> Add list of repositories

docs/api/python/overview.md
=> Add note on Pythn context manager (with)

docs/sql/statements/create_sequence.md, js/statements/createsequence.js
=> Add examples to CREATE SEQUENCE and improve its railroad diagram

docs/guides/python/jupyter.md
=> Document JupySQL native connection

docs/api/python/data_ingestion.md, docs/data/csv/overview.md, docs/data/csv/tips.md, docs/data/parquet/overview.md, docs/guides/data_viewers/youplot.md, docs/guides/import/csv_import.md
=> Use load/read/import for CSV

docs/sql/statements/vacuum.md
Fixes #1331 for the time being
=> Update documentation on VACUUM

internals/storage.md
=> Add storage approximation

docs/sql/data_types/text.md
=> Add note on escaping single quote characters

_includes/menu_secondary.html, css/main.scss, css/mobilestyles.scss
- added star counter to the nav-bar
- small text color fix on mobile
=> github star counter on nav bar

docs/sql/data_types/map.md
=> Update Retrieving from Maps examples in Maps page

docs/api/java.md
=> document streaming results with jdbc

css/blog.scss, css/docu.scss
- allow narrow tables in blog posts
=> narrow tables in blog posts

docs/api/python/overview.md, docs/guides/python/jupyter.md
=> Python and Jupyter updates

docs/sql/statements/pivot.md
Always on the lookout for critical issues
=> Nits 2023 11 04

docs/api/wasm/data_ingestion.md, docs/api/wasm/extensions.md
=> Note limited httpfs wasm support

docs/api/python/data_ingestion.md
This PR fixes #1458 
Feel free to audit the PR as much as needed 👍
=> Add docs for Python object -> DuckDB conversion

docs/sql/data_types/numeric.md
Fixes #1449, merge once https://github.com/duckdb/duckdb/pull/9441 hits DuckDB main.
=> Change HUGEINT's minimum value

_includes/installation.html, js/script.js
- added url parameter to installation page. so you can send links to exact installation instructions.
=> added url parameter to installation page

CONTRIBUTING.md, docs/api/adbc.md, docs/api/python/dbapi.md, docs/data/insert.md, docs/data/json/overview.md, docs/data/overview.md, docs/extensions/json.md, docs/guides/odbc/general.md, docs/guides/python/datafusion.md, docs/guides/python/polars.md, docs/guides/sql_features/full_text_search.md, docs/sql/data_types/timestamp.md, docs/sql/expressions/collations.md, docs/sql/introduction.md, docs/sql/query_syntax/with.md, docs/sql/window_functions.md
=> Adjust indentation and avoid "click here"-style links

docs/guides/import/excel_import.md
=> Rework Excel import guide

docs/sql/statements/attach.md, js/statements/attach.js
=> Document ATTACH IF NOT EXISTS

docs/api/cli.md, docs/api/python/overview.md, docs/sql/functions/timestamptz.md
=> Document getenv() function in CLI

docs/guides/import/http_import.md
=> Add concrete examples to HTTPS/Parquet import

docs/guides/python/relational_api_pandas.md
=> Sync title with menu entity

dev/sqllogictest/result_verification.md, docs/sql/aggregates.md
Fixes a few nits and fixes #1494
=> Add listagg function alias

docs/sql/data_types/interval.md
Fixes #1518, only merge once https://github.com/duckdb/duckdb/pull/9643 hits `main`.
=> Improve documentation on intervals

docs/api/cpp.md, docs/api/python/relational_api.md, docs/extensions/httpfs.md, docs/guides/data_viewers/tableau.md, docs/guides/data_viewers/youplot.md, docs/guides/python/datafusion.md, docs/guides/python/vaex.md, docs/sql/aggregates.md, docs/sql/data_types/nulls.md, docs/sql/expressions/star.md, docs/sql/expressions/subqueries.md, docs/sql/query_syntax/groupby.md, docs/sql/query_syntax/grouping_sets.md, docs/sql/query_syntax/having.md, docs/sql/query_syntax/limit.md, docs/sql/query_syntax/select.md, docs/sql/statements/create_macro.md, docs/sql/statements/pivot.md, docs/sql/statements/select.md, docs/sql/window_functions.md
* Aggregation functions (`min`, `max`, `count`, `avg`, `median`, ...)
* Functions related to null handling (`coalesce`, `ifnull`)
=> Spell function names as lowercase

docs/sql/aggregates.md
=> Fix the return type of the histogram function

docs/extensions/excel.md
=> Fix issues on the Excel extension page

docs/sql/data_types/timezones.md
=> Drop offset from time zones page

docs/sql/statements/create_table.md
=> Add info on how to disambiguate temp tables

_data/menu_docs_dev.json, docs/sql/indexes.md, docs/sql/statements/create_index.md
=> Move CREATE INDEX to its own statement page

docs/sql/statements/create_macro.md
Add an example of using a macro argument as a list
=> Add an example of using a macro argument as a list 

docs/sql/data_types/array.md, docs/sql/data_types/overview.md, docs/sql/functions/nested.md
Embed ARRAYs a bit better into the docs.
=> Add info on arrays into related pages

dev/building.md, docs/api/python/known_issues.md
Inspired by https://github.com/duckdb/duckdb/issues/8101
=> Building and running DuckDB on Windows 

_layouts/docu.html, css/foundation.scss, css/main.scss, css/mobilestyles.scss
- fixed docs header
- arrow position on foundation page
=> small improvements

_data/menu_docs_dev.json, docs/extensions/excel.md, docs/extensions/postgres_scanner.md, docs/extensions/sqlite_scanner.md, docs/guides/import/query_postgres.md, docs/guides/meta/duckdb_environment.md, docs/guides/meta/explain.md, docs/guides/meta/list_tables.md
Fixes #1550 along with a few other things I discovered while working on this.
=> Meta guides

docs/sql/functions/char.md
=> Add format_bytes to string functions table

docs/guides/meta/describe.md, docs/guides/meta/list_tables.md
=> Move text between describe/list_table pages

docs/sql/functions/char.md
Some minor changes I made while reviewing issue #1177.
=> Revamp similarity functions table

docs/data/csv/auto_detection.md, docs/sql/functions/nested.md
=> Markdown fixes

docs/sql/statements/update.md
=> Elaborate on using joins in updates

docs/archive/0.9.0/extensions/tpch.md, docs/archive/0.9.1/extensions/tpch.md, docs/archive/0.9.2/extensions/tpch.md, docs/extensions/aws.md, docs/extensions/httpfs.md, docs/extensions/json.md, docs/extensions/mysql.md, docs/extensions/tpch.md
=> Revise installation/loading instructions for extensions

docs/sql/statements/copy.md
=> Add documentation for COPY FROM DATABASE statement

docs/sql/pragmas.md
=> Document user_agent and metadata_info

docs/sql/functions/char.md
=> Add tables and examples for format specifiers (printf, fmt)

Gemfile.lock, docs/api/python/data_ingestion.md, docs/data/parquet/overview.md
While working on #1592, I found some missing examples. I added these and bumped Rouge.
=> Improve Parquet documentation

docs/data/parquet/metadata.md
Fixes #1603, only merged after https://github.com/duckdb/duckdb/pull/9793 has been merged to mainline.
Fixes #1652
=> Add description of parquet_file_metadata and parquet_kv_metadata

docs/extensions/tpcds.md, docs/extensions/tpch.md
=> Add TPC-H data generator parameters

docs/api/nodejs/overview.md, docs/extensions/overview.md, docs/extensions/working_with_extensions.md
Fixes #848
(sorry for the noise on the Node.JS page, I just made a few minor edits while I was there)
=> Review documentation for extensions

docs/sql/aggregates.md
Inspired by https://github.com/duckdblabs/duckdb-internal/issues/737
=> Clarify using explicit ordering in aggregate functions

docs/guides/meta/duckdb_environment.md, docs/sql/duckdb_table_functions.md
=> Document duckdb_optimizers table function

docs/sql/statements/copy.md
Made possible by the fix https://github.com/duckdb/duckdb/pull/9810
=> Simplify macro example for CREATE FROM DATABASE

docs/extensions/tpch.md
=> Adjust table header

css/docu.scss
This makes e.g., the Go page look nicer.
=> Set tab size to 4

_data/menu_side.json, dev/benchmark.md
=> Add benchmark instructions page

docs/extensions/overview.md, docs/extensions/working_with_extensions.md
This fixes some current inaccuracies and reflect the status post work on custom_extension_repository.
Fixes https://github.com/duckdb/duckdb-web/issues/1670.
Documents duckdb/duckdb#9818.
=> Another round of extension docs, depends on duckdb/duckdb#9818

docs/sql/functions/interval.md
Fixes #1607
Only merge after https://github.com/duckdb/duckdb/pull/9796 has been merged
=> Document to_weeks, to_decades, to_centuries, and to_millenia functions

docs/api/python/overview.md, docs/archive/0.9.2/api/python/overview.md
=> Python: Add note on using a new cursor for each thread

_data/menu_docs_dev.json, docs/api/cli.md, docs/api/python/dbapi.md, docs/sql/query_syntax/prepared_statements.md
=> Document prepared statements in query syntax

_data/menu_docs_dev.json, docs/sql/statements/drop.md, docs/sql/statements/profiling.md, docs/sql/statements/transactions.md
=> Document DROP TYPE statement and statements for transaction handling

docs/api/swift.md, docs/sql/statements/transactions.md
=> Add Swift page

docs/sql/query_syntax/select.md
=> Add example for using quotes in SELECT statement

docs/extensions/official_extensions.md
=> Document built-in extensions

docs/data/csv/auto_detection.md
Do not merge until https://github.com/duckdb/duckdb/pull/9522 is merged.
Fixes #1461
=> Document sniff_csv function

docs/api/go.md
This PR fixes the Go example in the docs.
=> Fix Go example

docs/sql/statements/pivot.md, js/statements/pivot.js
=> Add ORDER BY and LIMIT clauses to the PIVOT railroad diagrams

docs/extensions/httpfs.md
=> ALLOW_OVERWRITE -> OVERWRITE_OR_IGNORE

_data/menu_docs_dev.json, docs/guides/performance/benchmarks.md, docs/guides/performance/environment.md, docs/guides/performance/file-formats.md, docs/guides/performance/how-to-tune-workloads.md, docs/guides/performance/indexing.md, docs/guides/performance/my-workload-is-slow.md, docs/guides/performance/overview.md, docs/guides/performance/schema.md
...and a bunch of other things in the performance guide.
=> Fix trailing comma

_data/menu_docs_dev.json, docs/extensions/mysql.md, docs/extensions/postgres.md, docs/guides/import/query_mysql.md, docs/guides/import/query_postgres.md, docs/guides/import/query_sqlite.md, docs/guides/index.md
=> Add MySQL guide

docs/sql/functions/dateformat.md
Fixes #1707
Fixes #1723
@hawkfish this is what you had in mind for documenting this or are there more details I should add?
=> Clarify week number of the year modifiers, %U and %W

docs/sql/statements/checkpoint.md
=> Document VACUUM changes

docs/guides/performance/file-formats.md, docs/guides/performance/how-to-tune-workloads.md, docs/guides/performance/my-workload-is-slow.md, docs/sql/pragmas.md
=> Add out-of-core capabilities to performance guide

docs/sql/statements/insert.md
The columns in "do update set" does not support the parenthesis.
=> correct typo in DO UPDATE SET

.github/workflows/jekyll.yml
Apply the changes of #1771 and #1772 in one PR.
=> Update upload-artifact and download-artifact GitHub Actions plugins

dev/building.md
Edit (Gabor): followup of #1778
=> Update building.md with pip

docs/sql/aggregates.md
=> Document sum_no_overflow

_posts/2023-09-15-asof-joins-fuzzy-temporal-lookups.md, docs/sql/query_syntax/from.md
=> AsOf examples: Quote keywords

_data/menu_docs_dev.json, docs/sql/functions/lambda.md, docs/sql/functions/nested.md
=> Add lambda functions page

robots.txt
Fixes https://github.com/duckdb/duckdb-web/issues/1806
~~Might be worth updating our search index generation as well~~
=> generate robots.txt to exclude old archives from being indexed

docs/guides/performance/how-to-tune-workloads.md, docs/sql/configuration.md, docs/sql/duckdb_table_functions.md, docs/sql/pragmas.md, docs/sql/statements/checkpoint.md, docs/sql/statements/set.md, js/statements/set.js
Rework PRAGMA and related pages.
=> Rework PRAGMAs page

docs/sql/aggregates.md
=> Aggregate functions: emphasize which functions are affected by ordering

docs/sql/pragmas.md
I added a remark on the memory limit.
=> Add remark on memory limit

docs/sql/aggregates.md
=> Improve documentation on ORDER BY clause for functions and add example

docs/sql/statements/insert.md
=> Add missing column name

docs/sql/functions/lambda.md
All examples now have separate snippets for the query and the result
=> Cosmetic Lambda Rework

single-file-document/bluloco-light.theme, single-file-document/pandoc-configuration.yaml, single-file-document/sql-duckdb.xml, single-file-document/templates/eisvogel2.tex
It now uses (almost) the same set of keywords/function names and (almost) the same color scheme.
=> Improve syntax highlight in PDF

docs/extensions/json.md
=> Add remark on 0-based indexing for the JSON data type

docs/sql/data_types/typecasting.md, docs/sql/expressions/cast.md
This fixes issue https://github.com/duckdb/duckdb-web/issues/1837
=> Issue 1837 crosslink typecasting documentation pages

docs/data/csv/overview.md, docs/sql/statements/copy.md
=> Document 'file_size_bytes'

docs/guides/performance/indexing.md
=> typo: Minor typo in indexing docs

docs/guides/performance/how-to-tune-workloads.md, docs/sql/aggregates.md
=> Document holistic aggregates

docs/sql/data_types/overview.md
=> Remove repetition

docs/sql/functions/char.md, docs/sql/functions/utility.md
=> Issue 1846: hash() return value

dev/sqllogictest/loops.md, docs/api/python/types.md, docs/sql/data_types/numeric.md, docs/sql/data_types/overview.md
Also fixes the table for `foreach` in sqllogictest/loops.md, as I noticed it was broken.
=> Adding the `UHUGEINT` type

why_duckdb.md
=> Add Tom Ebergen's MSc thesis on query optimziation

docs/sql/functions/char.md, docs/sql/functions/utility.md
Fixes https://twitter.com/mlafeldt/status/1746928152612417953
=> Add SHA-256 hash function, sha256()

docs/sql/functions/lambda.md
Fixes https://github.com/duckdb/duckdb-web/issues/1850.
=> Lambda scoping documentation and other small fixes

internals/storage.md
=> Document that compression is only applied for persistent DBs

js/search.js
=> Tweak search tokenisation

docs/sql/statements/copy.md
=> Document the ability to use double quotes / omit quotes in the COPY ... TO statement

docs/data/csv/overview.md
=> Add note to CSV reader on character encoding

docs/sql/window_functions.md
I think Qualify should be featured as part of the window functions section. Adding a link
=> Adding Qualify section to the window functions docs

BUILDING.md
Updated the site build guide based on feedback by @chrisiou
=> Update site build guide

dev/benchmark.md
=> Remove duplicate env var

docs/data/csv/overview.md
=> CSV reader: Reintroduce 'parallel' option

docs/sql/data_types/overview.md
=> Move DECIMAL alias to its correct place

docs/data/json/overview.md
=> JSON reader: Add 'convert_strings_to_integers' option

scripts/README.md, scripts/generate_all_docs.sh
=> Scripts: update documentation on how to run generation scripts

.github/workflows/update-docs.yml, scripts/README.md
=> Update 'Update docs' script and script generation instructions

docs/archive/0.9.0/extensions/httpfs.md, docs/archive/0.9.1/extensions/httpfs.md, docs/archive/0.9.2/extensions/httpfs.md, docs/extensions/httpfs.md, docs/sql/aggregates.md, docs/sql/functions/nested.md
Fixes #1466
Merge once https://github.com/duckdb/duckdb/pull/9545 is merged & deployed in nightly
=> Document kurtosis_pop

_data/menu_docs_dev.json, docs/sql/keywords-and-identifiers.md, docs/sql/query_syntax/select.md, docs/sql/statements/select.md
=> Add page on keywords and identifiers

docs/sql/keywords-and-identifiers.md, docs/sql/statements/attach.md
=> Add note on database identifiers

docs/sql/keywords-and-identifiers.md
=> Document the usage of underscores in numeric literals

docs/extensions/azure.md
Hello team!
Some of the feature that I'm describing in the documentation still need to be merged (cf [PR#31](https://github.com/duckdb/duckdb_azure/pull/31)) but for the renaming part they are already present in the main branch of the [duckdb_azure repository](https://github.com/duckdb/duckdb_azure).
@samansmink as you are reviewing the other PR can you take a look on this ?
Regards,
Quentin
PS: fill free to update the PR directly as english is not my native language
=> Update azure documentation

docs/extensions/postgres.md
=> Update Postgres page

docs/extensions/json.md
=> Update JSON page

docs/sql/statements/copy.md
=> Rework COPY TO section

_includes/installation.html
=> Add ODBC macOS package on installation page

docs/api/java.md, docs/api/python/dbapi.md, docs/api/python/expression.md, docs/api/python/function.md, docs/extensions/azure.md
=> Formatting improvements

_data/menu_docs_dev.json, docs/extensions/versioning_of_extensions.md, docs/extensions/working_with_extensions.md
@carlopi LMK if this looks good
=> Add page on versioning of extensions

docs/extensions/json.md
=> Improve JSON documentation, add maximum_sample_files option

docs/sql/pragmas.md
=> Document errors_as_json PRAGMA

css/foundation.scss, css/main.scss, foundation/index.html, js/script.js
- buttons on foundation page
- JetBrains font without "NL"
- fix on installation page
=> small fixes

_plugins/seo_description.rb
Fixes https://github.com/duckdb/duckdb-web/issues/2018
=> patch jekyll-seo-tag to provide page contents as description

docs/extensions/iceberg.md
Inpsired by the discussion at https://www.reddit.com/r/DuckDB/comments/1ai4pig/r_duckdb_and_iceberg/
=> Update Iceberg page

docs/sql/data_types/map.md
=> Map page: Rework MAP creation examples

docs/sql/expressions/comparison_operators.md
=> Rework between page

docs/guides/performance/file_formats.md
=> Fix link to zonemaps

docs/sql/functions/nested.md
=> Fix nested page

docs/api/cli/editing.md
=> Document new CTRL+X behavior

docs/data/parquet/overview.md, docs/data/parquet/tips.md, docs/sql/query_syntax/filter.md, docs/sql/statements/export.md
Merge before v0.10 is released
=> Utilize underscore (_) as number separator for large 10^k numbers

_config.yml, docs/sql/functions/nested.md
=> Add new struct_extract for tuples, rework struct functions

docs/sql/duckdb_table_functions.md
=> Add duckdb_memory table

CONTRIBUTING.md, docs/api/julia.md, docs/api/python/data_ingestion.md, docs/api/python/dbapi.md, docs/api/python/expression.md, docs/api/python/function.md, docs/api/python/known_issues.md, docs/api/python/types.md, docs/data/csv/tips.md, docs/data/json/overview.md, docs/data/parquet/tips.md, docs/guides/python/export_arrow.md, docs/guides/python/jupyter.md, docs/guides/python/sql_on_arrow.md, docs/guides/sql_editors/dbeaver.md, docs/sql/configuration.md, docs/sql/duckdb_table_functions.md, docs/sql/expressions/comparison_operators.md, docs/sql/functions/bitstring.md, docs/sql/statements/create_table.md
In most places, these manual line breaks look bad. I removed them and added a note in the contributor's guide to ask contributors to avoid them.
=> Remove (manual) hard line breaks, and ask contributors to avoid them

_data/menu_docs_dev.json, docs/api/go.md, docs/api/rust.md, docs/data/appender.md
cc @maiadegraaf @taniabogatsch
=> Document Go appender

docs/sql/keywords_and_identifiers.md
=> Document rules for deduplicating identifiers

Gemfile.lock, _data/menu_docs_dev.json, docs/data/parquet/encryption.md, docs/data/parquet/overview.md, docs/data/parquet/tips.md
=> Document Parquet encryption

_layouts/post.html
=> Hide excerpt in the News page

docs/guides/python/ibis.md
=> Fix example on Ibis page

_data/menu_docs_dev.json, docs/sql/statements/comment_on.md, js/statements/comment.js, js/statements/copy.js
=> Document COMMENT ON

docs/sql/pragmas.md
=> Add info on profiling_mode PRAGMA

docs/guides/performance/indexing.md
Suggested by @ktk in https://github.com/duckdb/duckdb/discussions/10583#discussioncomment-8454000
=> Performance guide: Cross-link indexing section from schema

_config.yml, _includes/menu_secondary.html, _includes/menu_sidebar.html, _layouts/docu.html, index.html
=> Bump version to 0.10

internals/storage.md
differtn -> differnt, can you please patch it @szarnyasg? thanks!
=> Update storage.md: backward incompatible error message

docs/sql/statements/delete.md
=> Document TRUNCATE keyword

docs/api/adbc.md, docs/api/nodejs/overview.md, docs/api/python/data_ingestion.md, docs/api/swift.md, docs/api/wasm/overview.md, docs/data/parquet/overview.md, docs/extensions/json.md, docs/extensions/overview.md, docs/guides/import/query_parquet.md, docs/guides/odbc/general.md, docs/guides/performance/file_formats.md, docs/guides/performance/schema.md, docs/sql/pragmas.md
...also eliminate redundant `.html` extensions
=> Replace absolute URLs and drop extensions where applicable

docs/archive/0.9.2/sql/functions/timestamptz.md, docs/sql/functions/timestamptz.md
=> Fix output of localtime function

docs/api/java.md
=> Document JDBC batch writer

_posts/2022-10-28-lightweight-compression.md, _posts/2024-02-13-announcing-duckdb-0100.md, internals/storage.md
=> Documenting compression

docs/sql/statements/copy.md
=> Update COPY configuration option

docs/sql/statements/create_macro.md
=> Document macro limitations

docs/data/appender.md
Fixes #2017, see the issue for details on reproducing the experiment.
=> Document appender behavior on conflicts

js/railroad.js
=> Syntax: Add alias to join clause in railroad diagram

docs/sql/window_functions.md, js/expressions/window.js, js/railroad.js
=> Document EXCLUDE clause for window functions

_data/menu_docs_dev.json, docs/sql/data_types/literal_types.md
=> Document literal types

internals/storage.md
=> Add info on storage compatibility (forward compatibility and backward compatibility)

docs/guides/meta/describe.md, docs/guides/meta/summarize.md
=> Update SHOW/REMOTE/SUMMARIZE table pages

_data/menu_docs_dev.json, docs/guides/import/read_file.md, docs/guides/index.md, docs/sql/functions/utility.md
=> Add guides and utility function entires for read_blob and read_text

_layouts/default.html, _layouts/docu.html, _layouts/post.html
=> Add meta headers to force https upgrade

css/docu.scss, css/main.scss, faq.md, js/script.js
- new design for FAQ section in docs
=> redesign of FAQ section

js/noteboxes.js
=> Do not trim first word for default note boxes

Gemfile.lock, _data/menu_docs_dev.json, docs/guides/import/s3_express_one.md, docs/guides/index.md, docs/sql/statements/create_secret.md
=> Document S3 Express One Performance

docs/guides/performance/how_to_tune_workloads.md
=> Update how_to_tune_workloads.md - minor typo

_includes/installation.html, _sass/variables.scss, css/docu.scss, css/main.scss, css/mobilestyles.scss, css/railroad.css, css/syntax_highlighting.scss
- updated installation page to new design
- changed link color in general
- made some small improvements and css bug fixes
=> installation page

_includes/installation.html
- intro text
- ODBC link
- Java/Maven snippets
- Python pip install instruction
Followup of #2202
=> Update installation page

_layouts/docu.html, docs/api/go.md, docs/api/r.md, docs/api/swift.md, docs/extensions/arrow.md, docs/extensions/aws.md, docs/extensions/azure.md, docs/extensions/iceberg.md, docs/extensions/mysql.md, docs/extensions/postgres.md, docs/extensions/spatial.md, docs/extensions/sqlite.md, docs/extensions/substrait.md
...and render it in the bottom box ("About this page")
=> Add github_repository value to frontmatter

_layouts/post.html, css/blog.scss, css/docu.scss, css/main.scss, js/noteboxes.js
- note boxes in blog posts
- height of italic code snippets
- css variables
=> small adaptions

_data/menu_docs_dev.json, docs/guides/import/overview.md, docs/guides/index.md, docs/index.md
=> Add data import overview

css/blog.scss, css/docu.scss, css/main.scss
Reverts duckdb/duckdb-web#2222
=> Revert "CSS Finetuning"

css/blog.scss, css/docu.scss, css/main.scss
Re-applying the changes of #2222 with a minor fix
=> PR #2222 followup

docs/api/python/data_ingestion.md, docs/api/python/relational_api.md, docs/data/parquet/overview.md, docs/data/parquet/tips.md, docs/sql/functions/char.md
Sprinkle some underscores on long numbers.
=> Improve formatting of numbers

.github/workflows/jekyll.yml
=> Use 'gh api' call for retrieving star count

docs/sql/query_syntax/from.md
Add an example of a table alias, as there does not appear to be one currently included
=> from.md: Add example of a table alias

.github/workflows/jekyll.yml
=> Use gh api call for star count

_includes/breadcrumbs.html
Traverse the menu tree along the slug's parts (crumbs) #2274
=> Rework breadcrumb

docs/sql/functions/patternmatching.md
=> RE2 updates

_includes/breadcrumbs.html
=> Breadcrumb fixes

Dockerfile, scripts/docker-build.sh, scripts/docker-serve.sh
Fix missing header (linux/limits.h)
Fix wrong permission (cannot write Gemfile.lock)
=> Fix docker local build

docs/sql/functions/patternmatching.md
from https://github.com/duckdb/duckdb-web/pull/2280#issuecomment-1961870459 /fyi @szarnyasg
=> Update patternmatching.md; use E'...' escape strings
