duckdb/duckdb-web

docs/sql/data_types/text.md
=> Document escape strings

docs/extensions/versioning_of_extensions.md
small bit on extension versions
=> bit on extension versions

docs/api/cli/overview.md, docs/api/odbc/linux.md, docs/api/odbc/macos.md, docs/api/python/types.md, docs/extensions/azure.md, docs/extensions/full_text_search.md, docs/extensions/httpfs/s3api-legacy-authentication.md, docs/extensions/httpfs/s3api.md, docs/extensions/spatial.md, docs/extensions/versioning_of_extensions.md, docs/guides/data_viewers/tableau.md, docs/guides/data_viewers/youplot.md, docs/guides/import/cloudflare_r2_import.md, docs/guides/import/gcs_import.md, docs/guides/import/http_import.md, docs/guides/import/s3_export.md, docs/guides/import/s3_express_one.md, docs/guides/import/s3_iceberg_import.md, docs/guides/import/s3_import.md, docs/guides/performance/how_to_tune_workloads.md, docs/sql/aggregates.md, docs/sql/data_types/array.md, docs/sql/keywords_and_identifiers.md, docs/sql/pragmas.md, docs/sql/statements/pivot.md, docs/sql/statements/profiling.md, docs/sql/statements/unpivot.md
=> Use left and right angle brackets as placeholder

docs/sql/functions/nested.md
Fix typo `generate_subscript` -> `generate_subscripts`
=> Fix typo nested.md

docs/sql/data_types/literal_types.md, docs/sql/data_types/text.md
=> Document dollar-quoted string literals, move related stuff to string literals page

docs/guides/performance/how_to_tune_workloads.md
some basics of optimizing queries on remote files
=> Add bit on remote file performance

docs/sql/aggregates.md
=> Document the effect of ordering on arg_min and arg_max

docs/sql/statements/pivot.md, docs/sql/statements/unpivot.md
=> Document the use expressions in UNPIVOT statements

_posts/2024-02-13-announcing-duckdb-0100.md
=> Remove note from release blogpost

docs/sql/functions/char.md, docs/sql/functions/regular_expressions.md
Fixes #2352
Pending on the merge of https://github.com/duckdb/duckdb/pull/10898
=> Document regexp_split_to_table

_posts/2023-09-26-announcing-duckdb-090.md, docs/configuration/overview.md, docs/connect/concurrency.md, docs/guides/performance/how_to_tune_workloads.md
=> More fixes, add redirect

docs/api/odbc/linux.md
=> Update ODBC Linux packages

docs/guides/performance/schema.md, docs/sql/data_types/numeric.md, docs/sql/functions/utility.md
=> Improve the documentation on UUIDs

_includes/installation.html, js/script.js
Now using userSelection and currSelection JS variable instead of HTML state
=> Rework selection logic

_includes/installation.html, index.html, js/script.js
This was broken in #2381 due to using a shared JS function between the landing page and the larger installation page.
=> Fix installation box in landing page

js/script.js
=> Landing page: Fix language/API selector

docs/api/cli/overview.md, docs/connect/overview.md, faq.md
=> Further elaborate on persistence FAQ entry

_includes/landing-page/r/sql-query.r
This reverts commit 778269cb551cd521a0b87456439043101d74ff27.
=> Revert "use raw string for R example"

_includes/landing-page/r/sql-query.r
=> Use single-quotes to define string in R example

js/statements/createschema.js
=> Fix CREATE SCHEMA syntax diagram

docs/extensions/postgres.md
Fix MD formatting here: https://duckdb.org/docs/extensions/postgres.html#create-schema--drop-schema
=> Fix formatting in postgres.md

docs/extensions/httpfs/s3api.md, docs/guides/import/s3_export.md, docs/guides/import/s3_import.md
=> Document workaround for AWS endpoint issues

_layouts/post.html, _sass/variables.scss, css/docu.scss, css/main.scss, css/mobilestyles.scss, js/noteboxes.js, js/script.js
CSS fixes and search feature on the landing page.
=> various style fixes

docs/data/appender.md
=> Document the Appender's default commit frequency

docs/sql/statements/attach.md
How to use an in-memory database to DETACH from the default database
=> Add more details on DETACH

_includes/installation.html, css/docu.scss, css/main.scss
- added css for SHA-512 button on installation page. See commented example line #138
=> added SHA-512 button styles for installation page

_data/authors.yml, _layouts/post.html
Primarily for this: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md#author-information
and also used for the avatar thing
=> Populate authorship map

docs/sql/functions/char.md
=> Add 'greatest' function to character functions page

docs/data/csv/overview.md
This PR fixes #2457 
`delim` only takes a single character
=> string -> character

docs/sql/data_types/timestamp.md
=> Fix TIMESTAMP alias

css/home.scss, index.html, js/script.js
- added banner element to home, added script to hide this banner.
=> added banner element to home

css/foundation.scss, css/home.scss
=> css improvements

docs/sql/expressions/star.md
Fixes #2251
Merge this around the release of v0.10.1.
=> Update the output of queries using the COLUMNS expressions

scripts/generate_config_docs.py
=> Add temp_directory name in configuration table generation script

docs/sql/statements/create_table.md
=> Document foreign key limitations

docs/sql/data_types/literal_types.md
=> Document backslash escape sequences

docs/extensions/postgres.md
=> Add instructions to copy the entire database from Postgres

_layouts/default.html, css/main.scss, foundation/index.html, trademark_guidelines.md
- the new page head can now be defined and added via frontmatter: pagehead:
- "Page Title"
- "bg2"
=> updated page: trademark guidelines

docs/extensions/postgres.md
=> Fix detach example

docs/guides/sql_features/friendly_sql.md
=> Extend Friendly SQL page

.github/workflows/jekyll.yml
=> Link Checker CI fixes

dev/building.md
=> Document OVERRIDE_GIT_DESCRIBE

css/home.scss, js/script.js
- disabled default system behavior of select box on landing page to fit the design
=> updated the select options on landing page

css/home.scss
- updated select styles to meet new design
=> updated select styles

css/docu.scss
these tables can be used for function tables
* Description: …
* Example: …
* Result: …
HTML-Code must be placed right before the markdown table: <div class="nostroke_table"></div> to apply styles.
=> added another table style: nostroke_table

_includes/banner_docversion.html, _layouts/docu.html, css/docu.scss, css/home.scss, css/main.scss, js/script.js
- banner will be shown on outdated and nightly docs
=> added info banner to outdated / nightly viewed docs

_includes/banner_docversion.html
- needed to remove some code. Please merge asap :) @szarnyasg
=> correction – outdated version

_config.yml
Due to https://github.com/duckdb/duckdb/issues/11244
=> Set current Java version to v0.10.0

docs/data/parquet/overview.md, docs/guides/performance/file_formats.md, single-file-document/sql-duckdb.xml
=> Document LZ4 and LZ4_RAW compression

docs/guides/performance/schema.md
=> Clarify the effect of primary keys

docs/archive/0.6/installation/index.html, docs/archive/0.7/installation/index.html, docs/archive/0.8/installation/index.html, docs/archive/0.9/installation/index.html
=> Fix archive installation pages

docs/extensions/mysql.md
=> Add COPY FROM DATABASE to MySQL page

docs/sql/information_schema.md
Partial resolution towards #2559
=> Information schema: Add views

docs/configuration/overview.md
@Tishj I added the scope column, is there anything else missing?
Fixes #2547
=> Configuration example: Add scope column

docs/sql/query_syntax/unnest.md
=> Document max_depth parameter for unnest

docs/guides/python/relational_api_pandas.md
=> Relational API on Pandas: Add missing where clause

_includes/installation.html
Related to https://github.com/duckdb/duckdb/issues/11244
=> Point to currentjavaversion for Maven direct link

docs/sql/statements/insert.md
=> ON CONFLICT ... DO UPDATE: Document restriction

docs/sql/functions/char.md
=> Fix regexp_split_to_table example

_posts/2024-03-29-external-aggregation.md
Uploaded file to S3 and finished TODO
=> Aggregation post nitpicks

docs/dev/release_calendar.md
=> Add releases v0.1 to v0.2.1 to release calendar

docs/data/csv/overview.md
=> CSV Options: extract 'auto_type_candidates'

docs/sql/window_functions.md
=> Format window function table

docs/sql/query_syntax/with.md
Add Fibonacci example for developers unfamiliar with CTEs, so they could see CTEs being used to solve a problem they're already familiar with.
=> with.md: Add Fibonacci example

_posts/2024-03-29-external-aggregation.md
=> Add paper link

docs/sql/functions/nested.md
=> Fix default sort order for NULLs

docs/sql/statements/create_index.md, js/statements/indexes.js
=> Add custom indexing options

docs/sql/statements/drop.md
=> Improve Drop page

docs/sql/functions/regular_expressions.md
=> regexp_extract: Clarify that idx must be a constant value

docs/sql/functions/char.md
=> Add and fix examples for array_slice function

docs/sql/functions/nested.md
=> Rework nested examples

docs/api/python/expression.md, docs/sql/expressions/in.md
=> Improve Python Expression page and add isnull/isnotnull expressions

docs/api/python/overview.md
=> Python: Document dataframe limitations

docs/api/odbc/windows.md
=> ODBC: Fix script

js/statements/createview.js
=> Add NOT EXISTS to CREATE VIEW syntax diagram

docs/sql/functions/nested.md
=> Rework description of range functions

docs/data/csv/overview.md
=> CSV reader: Document nullstr list

docs/sql/data_types/struct.md
=> Document nested NULL comparison

docs/data/multiple_files/overview.md
=> Document string option for filename configuration

docs/connect/concurrency.md
=> Add note on optimistic cc

docs/extensions/sqlite.md
Resolves https://github.com/duckdb/sqlite_scanner/issues/82.
=> Documented concurrency considerations for the SQLite extension

_includes/installation.html
=> Add MSVC to Python installation

docs/sql/query_syntax/prepared_statements.md
=> Document DEALLOCATE statement

docs/sql/query_syntax/from.md
=> Add example for positional join

docs/sql/statements/transactions.md
=> Fix name on transactions page

docs/sql/statements/call.md
In hindsight it was obvious, but initially it was unclear how to get a subset of rows and columns. This should make it clearer.
=> Add another example to show table functions really work as tables

_includes/installation.html, docs/dev/building/troubleshooting.md
=> Link troubleshooting page for R installation

docs/extensions/postgres.md
=> Add missing space

docs/extensions/substrait.md
I'd never heard of substrait before.  Is this the best link for it?
=> link to substrait.io

docs/sql/functions/bitstring.md, docs/sql/functions/blob.md, docs/sql/functions/char.md, docs/sql/functions/date.md, docs/sql/functions/enum.md, docs/sql/functions/nested.md, docs/sql/functions/numeric.md, docs/sql/functions/overview.md, docs/sql/functions/utility.md
=> Add redirects for test function pages

docs/data/csv/reading_faulty_csv_files.md
=> Hide unsupported flag 'rejects_recovery_columns'

_includes/installation.html
=> Add note on separate update

docs/sql/data_types/timestamp.md
=> Remove duplicate word

docs/sql/introduction.md
=> Add note on Postgres-compatibility

docs/sql/statements/insert.md
See tests here: https://github.com/duckdb/duckdb/pull/12084/files
=> Update on conflict do update limitations

docs/sql/data_types/list.md
=> Duplicate key

docs/extensions/excel.md
=> Update Excel extension's repository

Gemfile.lock, docs/sql/data_types/literal_types.md, docs/sql/data_types/numeric.md, docs/sql/data_types/text.md, docs/sql/keywords_and_identifiers.md
Fix https://github.com/duckdb/duckdb-web/issues/2877
Fix https://github.com/duckdb/duckdb-web/issues/2878 
Fix https://github.com/duckdb/duckdb-web/issues/2879
Fix #2869
=> Fixes 2877, 2878, 2879

docs/sql/expressions/subqueries.md
=> Fix https://github.com/duckdb/duckdb-web/issues/2881

docs/guides/file_formats/excel_export.md
=> Excel export: Remove deprecated warning

docs/sql/functions/char.md, docs/sql/functions/regular_expressions.md
=> Remove use of visible space characters

docs/data/json/overview.md
=> Fix JSON compression options

CONTRIBUTING.md, docs/sql/functions/regular_expressions.md
=> Add link to regex options

_config.yml
Fixes https://github.com/duckdb/duckdb-java/issues/17
=> Fix java snapshot version

_data/menu_docs_dev.json, docs/sql/introduction.md, docs/sql/postgresql_compatibility.md
=> Add page on Postgres compatibility

docs/extensions/azure.md, docs/extensions/httpfs/s3api.md, docs/extensions/json.md
=> Fix S3 API secrets page

_data/menu_docs_dev.json, docs/sql/query_syntax/limit.md, docs/sql/statements/select.md, js/railroad.js
=> Syntax diagram: Make ORDER BY optional; document OFFSET

docs/guides/network_cloud_storage/duckdb_over_https_or_s3.md
IIUC this limitation has been lifted since then?
=> rm a limitation that has been lifted since

_data/menu_docs_dev.json, docs/archive/0.10/guides/python/import_numpy.md, docs/archive/0.10/guides/python/import_pandas.md, docs/guides/glossary.md, docs/guides/overview.md, docs/guides/python/import_numpy.md, docs/guides/python/import_pandas.md, faq.md
=> Add Glossary of Terms page

index.html
The demo works again, so this PR reverts duckdb/duckdb-web#2954
=> Revert "Disable spatial demo"

_config.yml
Once 1.0.0 is uploaded to https://mvnrepository.com/artifact/org.duckdb/duckdb_jdbc
=> Bump Java/JDBC package version to 1.0.0

docs/archive/0.10/configuration/secrets_manager.md
=> Fix: which_secret in v0.10 is a scalar function

_posts/2024-06-10-delta.md
cc @samansmink 
We should merge this once https://github.com/delta-io/delta-rs/issues/2577 has been resolved
=> Delta blog post: Drop package version

docs/sql/functions/dateformat.md, docs/sql/functions/timestamp.md
=> Add try_strptime and add fixes in the documentation

docs/api/overview.md
=> Add Elixir client

docs/archive/0.10/data/multiple_files/overview.md, docs/data/multiple_files/overview.md
To be supported in v1.1
Fixes #3063
=> Remove unsupported feature read_csv(..., filename = VARCHAR)

docs/api/cli/output_formats.md
Provide additional information on usage and default values
=> Update output_formats.md: add default value

docs/guides/sql_features/friendly_sql.md
=> Fix error on Friendly SQL page

docs/data/overview.md
=> Add examples using the COPY statement to the data overview page

docs/extensions/httpfs/https.md, docs/extensions/httpfs/s3api.md
=> Link to partial reading from the httpfs extension's documentation

docs/sql/data_types/interval.md
Had copied that from previous version, but it seems to have been outdated.
=> Interval from decimal string

scripts/archive_docs.py
=> Update link tag in archived pages

_config.yml, css/docu.scss, docs/data/csv/reading_faulty_csv_files.md, docs/data/json/overview.md, docs/extensions/json.md, docs/extensions/spatial.md, docs/sql/expressions/subqueries.md
=> Add monospace_table style

docs/sql/query_syntax/from.md
=> Add NATURAL JOIN to documentation

docs/guides/sql_features/asof_join.md
I had a hard time understanding the warning on USING and being explicit about the parameters. I reworded it and added an extra example
=> Clarifying  USING and ASOF Join

_config.yml
To be merged... in a week, I guess? 😎
=> Bump default star count

docs/guides/sql_features/friendly_sql.md
=> Add OLAP features to friendly SQL page

docs/sql/functions/utility.md
=> Add getenv function

docs/sql/functions/utility.md, js/railroad.js
=> Add parenthesized version of select-node to CTE railroad diagram

docs/guides/network_cloud_storage/cloudflare_r2_import.md
Minor update to clarify account ID format for users.
=> docs; Update cloudflare_r2_import.md

docs/extensions/working_with_extensions.md
Fixes https://github.com/duckdb/duckdb-web/issues/3204
=> Fix typo in query

docs/extensions/postgres.md
=> Postgres scanner: Document pg_use_ctid_scan

docs/dev/building/build_instructions.md
=> Building: Add instruction to clone the whole repository

_data/menu_docs_dev.json, docs/api/cli/overview.md, docs/extensions/working_with_extensions.md, docs/guides/using_duckdb/files_created_by_duckdb.md, docs/guides/using_duckdb/gitignore_for_duckdb.md
=> Add gitignore and files created by DuckDB pages

_config_exclude_archive.yml, scripts/serve.sh
https://stackoverflow.com/a/43299367/3580502
=> Use 'bundle' binary consistently

docs/extensions/community_extensions.md, docs/operations_manual/footprint_of_duckdb/gitignore_for_duckdb.md
This needs to be auto-generated, for now needed light editing and I think it will do for a bit.
=> Add current list of community extensions

docs/data/csv/overview.md, docs/sql/dialect/order_preservation.md
Fix https://github.com/duckdb/duckdb-web/issues/3266
WARNING: I'm experiencing doc build issues, and I can't view the site locally on my machine anymore.
I recently upgraded to win11, that may be the cause.
I hope the commit is ok - apologies if there's an issue.
=> Fix https://github.com/duckdb/duckdb-web/issues/3249

_data/menu_docs_dev.json, _layouts/community_extension_doc.html, documentation.md, faq.md, list_of_extensions.md
Minor fixes, and expanded on descriptor.yml fields and how documentation gets generated.
=> More docs community

Gemfile.lock, css/blog.scss, css/foundation.scss, css/home.scss
See https://sass-lang.com/documentation/breaking-changes/mixed-decls/
=> CSS Sass deprecation fixes

docs/data/csv/auto_detection.md, docs/data/csv/overview.md
crosslinks re. auto type detection between overview and auto detection pages.
=> Fixes https://github.com/duckdb/duckdb-web/issues/3327

docs/sql/statements/create_index.md
Add link to index types in CREATE INDEX doc
=> Add link to index types in CREATE INDEX doc

docs/data/appender.md
=> Add link to Julia appender

docs/api/adbc.md
I've been collaborating with Matthew Topol (@zeroshade) who I believe wrote much of this doc page, on building a Go PoC for working with DuckDB & Arrow. Having succeeded with this prototype, I'm adding a working example here.
=> Add Go Example to ADBC section

index.html
To be merged on the day of DuckCon #5
=> Remove DuckCon 5 banner

docs/api/python/dbapi.md
Mention named in-memory connections and reorder some of the information regarding connections and the different types of connections there are.
=> Update the dbapi.md page

docs/sql/dialect/postgresql_compatibility.md, docs/sql/expressions/subqueries.md
=> Document how scalar subqueries work

docs/guides/data_viewers/tableau.md
=> Update taco link

docs/api/cpp.md
=> Fix: The source distribution no longer contains an amalgamated source code

_includes/footer.html, docs/index.md
=> Fix URLs in footer

docs/sql/functions/lambda.md
=> Update lambdas page

_includes/installation.html, css/main.scss, css/mobilestyles.scss, js/installation.js, js/script.js
- pre-selection for users OS
- line break of environment names
=> small bug fixes

docs/sql/query_syntax/from.md
=> Rework semi and anti joins

docs/api/cli/dot_commands.md
=> Add .singleline and .multiline dot commands

docs/sql/expressions/star.md
=> COLUMNS expression: Eliminate contradiction

Gemfile.lock, docs/data/parquet/overview.md, docs/sql/statements/copy.md
=> Update COPY parameters, add COMPRESSION_LEVEL for zstd-compressed Parquet

docs/sql/meta/information_schema.md
=> Rework information catalog page

docs/sql/meta/duckdb_table_functions.md
=> Fix links to information schema page

docs/api/wasm/overview.md
=> Add some Wasm limitations

docs/sql/constraints.md, docs/sql/indexes.md
=> Improve documentation on constraints

docs/sql/statements/attach.md
=> Update documentation on ATTACH

docs/data/parquet/overview.md
=> Add more Parquet metadata examples

docs/extensions/json.md
=> Document json_extract

docs/dev/building/troubleshooting.md
Formatting/wording improvements for titles and add instructions for Python.
=> Extend on troubleshooting guide

docs/internals/overview.md
The algorithm name should be `DPccp`.
=> Fix a typo in duckdb internal doc

docs/data/parquet/overview.md
Closes https://github.com/duckdb/duckdb-web/issues/3502
=> write parquet kv metadata example

docs/api/wasm/instantiation.md
The bundle name should be MANUAL_BUNDLES.
=> Update WASM instantiation.md

docs/extensions/working_with_extensions.md
Made the page a bit more streamlined
=> Cleanup 'Working with extensions' page

docs/dev/building/build_instructions.md
=> Document CORE_EXTENSIONS flag

docs/sql/functions/numeric.md
=> Update info on random function

_data/menu_docs_dev.json, docs/operations_manual/non-deterministic_behavior.md
=> Add non-determinstic behavior page

docs/api/python/known_issues.md
As pointed out here, this is not a notebook issue but a generic Python one: https://github.com/duckdb/duckdb/issues/13195
=> Python: Adjust profiling newline issues

_posts/2022-01-06-time-zones.md, _posts/2023-09-15-asof-joins-fuzzy-temporal-lookups.md, docs/configuration/pragmas.md, docs/data/parquet/overview.md, docs/data/partitioning/hive_partitioning.md, docs/extensions/overview.md, docs/extensions/spatial.md
Fixes https://github.com/duckdb/duckdb/issues/12325
=> Fix default value for hive_partitioning flag

docs/sql/data_types/struct.md, docs/sql/statements/select.md
=> Rework struct page

scripts/generate_config_docs.py
=> Configuration options: Add manual override for 'enable_progress_bar'

docs/api/cpp.md
=> Add note that C++ API is internal

docs/extensions/json.md
=> Document json_exists and json_extract

_data/menu_docs_dev.json, docs/sql/dialect/friendly_sql.md, docs/sql/statements/attach.md, docs/sql/statements/export.md, docs/sql/statements/set.md, docs/sql/statements/set_variable.md, js/statements/setvariable.js
* Make the `/` separator more airy
* Document `SET VARIABLE`. Fixes #3300
=> Document SET VARIABLE

docs/sql/meta/duckdb_table_functions.md
Fixes #3448
Note: Variables themselves should also be documented, which is a separate issue, #3300
=> Document duckdb_variables() metadata function

docs/sql/dialect/postgresql_compatibility.md
=> Remove Postgres-incompatibility that was fixed in v1.1

docs/extensions/tpch.md
=> Update TPC-H documentation

docs/sql/functions/list.md, docs/sql/functions/map.md
=> list_position and map_contains_*

docs/guides/network_cloud_storage/duckdb_over_https_or_s3.md, docs/sql/statements/attach.md
=> Document changes in ATTACH over HTTP/S3

docs/configuration/pragmas.md
=> Document non-integer literal ordering option

docs/sql/functions/list.md
=> Add n-ary lambda example

scripts/get_calendar.py
The release calendar can currently display a release among both the past and the future releases:
This PR fixes this.
=> Filter old releases from future releases in release calendar

Gemfile.lock, docs/extensions/mysql.md, docs/extensions/postgres.md
Fixes https://github.com/duckdb/duckdb-web/issues/2739
And also documents some new config settings introduced in this release (https://github.com/duckdb/postgres_scanner/pull/259, https://github.com/duckdb/postgres_scanner/pull/255, https://github.com/duckdb/duckdb_mysql/pull/85)
=> Add secret information and new configuration flags for Postgres/MySQL

docs/sql/functions/char.md
Adds docs examples for feature introduced in https://github.com/duckdb/duckdb/pull/12717
=> Adds examples for thousand separators

data/installation-data-1.1.yml
...and also remove Win/Arm64 variant which is currently not supported
=> Installation page: Bump ODBC version

scripts/generate_search.py
=> Add .html extension to URLs in search data

.github/workflows/jekyll.yml
Reverts duckdb/duckdb-web#3619
=> Revert "CI: Use Pandoc 3.1.z.w"

.github/workflows/jekyll.yml, scripts/offline_docs_replace.py
=> replace necessary strings before zip offline package #3605

docs/sql/data_types/text.md
The target page is named "Text functions"
=> Change link text to "Text functions"

docs/archive/1.0/dev/repositories.md, docs/dev/building/build_instructions.md, docs/dev/repositories.md
Add rpi build instructions as suggested in https://github.com/duckdb/duckdb/issues/13855#issuecomment-2341539339
=> Raspberry Pi build and minor fixes

docs/dev/building/build_instructions.md
=> Refine wording

docs/sql/indexes.md
=> Link R-trees in the indexing page

docs/data/csv/overview.md
Fix: https://github.com/duckdb/duckdb/issues/13859
=> Clarify new_line option from the CSV Reader

index.html
Demo: https://shell.duckdb.org/#queries=v0,%20%20-Load-CSV-file%2C-auto%20detecting-column-name-and-types%0ACREATE-TABLE-stations-AS%0A----FROM-'https%3A%2F%2Fblobs.duckdb.org%2Fnl_stations.csv'~,%20%20-Sample-10-stations-using-replacement-sample%0AFROM-stations-USING-SAMPLE-10~,%20%20-Compute-some-property-on-the-stations-table%0ASUMMARIZE-stations~
=> Fix link, now nl_stations.csv

docs/sql/dialect/friendly_sql.md
Minor grammar edit in first line
=> Minor Update on First Line of friendly_sql.md

Gemfile.lock, docs/sql/statements/create_macro.md, js/statements/createmacro.js
=> Add documentation for macro overloads

docs/sql/expressions/star.md, js/railroad.js
=> Add documentation for `*COLUMNS`

docs/sql/expressions/star.md
=> New example for unpacked columns

Gemfile.lock, css/blog.scss, css/home.scss, css/main.scss
=> Fix Jekyll deprecation warning

data/installation-data-1.1.yml
=> Remove MSVC warning

docs/sql/meta/information_schema.md
(towards the resolution of #3753)
=> Document `information_schema.constraint_column_usage` view

_sass/variables.scss, css/docu.scss, css/syntax_highlighting.scss
- green underline on function-links inside code
- defined h5 headline
=> documentation css

docs/data/csv/overview.md
=> Document CSV options

docs/data/csv/overview.md
Sorry, I didn't remove the extra brackets in my last edit.
=> Remove the extra closing bracket

_posts/2024-10-04-duckdb-user-survey-analysis.md, images/blog/survey/clients.svg, images/blog/survey/data-formats.svg, images/blog/survey/dataset_sizes.svg, images/blog/survey/environments.svg, images/blog/survey/most_liked_features.svg, images/blog/survey/platforms.svg, images/blog/survey/roles.svg, images/blog/survey/server-premises.svg, images/blog/survey/server-sizes.svg
Analysis of https://www.linkedin.com/posts/duckdb_duckdb-user-survey-activity-7171178010375655424-NJkD/
=> Add survey results

docs/sql/functions/array.md
`array_cosine_distance` is not equal to one minus itself!
=> array_cosine_distance = 1 - array_cosine_similarity

css/darkmode.scss, css/docu.scss, css/syntax_highlighting.scss
- fixed some colors in dark mode
=> darkmode color fixes

js/railroad.js, js/statements/createtype.js
=> Include the catalog+schema in Create Type and Create Table railroad diagram

docs/configuration/pragmas.md, docs/dev/profiling.md
=> Update profiling docs

css/darkmode.scss, css/docu.scss, js/script.js
- toc menu headline
- version switch
=> visual adjustments

docs/dev/building/build_instructions.md
=> Add note on musl libc support

docs/dev/sqllogictest/loops.md
=> sqllogictest: Use repeat function

docs/extensions/azure.md, docs/extensions/delta.md
=> Delta extension: Document Azure support

docs/sql/dialect/friendly_sql.md, docs/sql/statements/insert.md
=> Add INSERT OR IGNORE/REPLACE to Friendly SQL page

docs/sql/dialect/postgresql_compatibility.md
=> Postgres-compatibility: Document lack of support for to_date

docs/extensions/azure.md
=> Azure: Document trailing slash requirement in SCOPE

docs/extensions/jemalloc.md
=> Update jemalloc documentation

docs/dev/sqllogictest/overview.md, docs/extensions/sqlsmith.md, why_duckdb.md
=> Link SQLsmith

_data/menu_docs_dev.json, docs/data/data_sources.md, docs/data/overview.md
=> Add Data sources page

.github/workflows/update-docs.yml, scripts/generate_function_json.py
=> generate_function_json.py: Handle NaN value separately

community_extensions/extensions/sheetreader.md
Preview seems to be working, but for this one that I somehow touched
=> Fix image preview link

docs/extensions/aws.md
=> aws extension: Add more explanation about deprecation

_posts/2024-10-25-topn.md
Make sure the tables look nicer
=> Blog post touchups

docs/sql/query_syntax/with.md
Just updating a spelling typo.
=> Fix typo in CTE materialization section

docs/sql/functions/blob.md
=> Document hex(blob) function

docs/sql/functions/aggregates.md
=> Change sample variance/coveriance to population covariance/covariance for regr_* functions

community_extensions/download_metrics.md, community_extensions/faq.md, community_extensions/index.md
* Shuffling of text in the main page
* More powerful table query to get the extensions
* Add FAQ on SQL extensions
New macro gives something like:
```
┌───────────────┬────────────┬────────────┬────────────┬────────────┐
│   extension   │ 2024-10-06 │ 2024-10-13 │ 2024-10-20 │ 2024-10-31 │
│    varchar    │   int64    │   int64    │   int64    │   int64    │
├───────────────┼────────────┼────────────┼────────────┼────────────┤
│ bigquery      │            │        173 │        276 │        217 │
│ chsql         │        165 │        175 │        159 │        133 │
│ crypto        │        162 │        157 │        142 │        120 │
│ duckpgq       │            │        197 │       1563 │        417 │
│ evalexpr_rhai │        492 │        416 │        326 │        298 │
│ faiss         │ …
```
=> Community extensions cleanup text

docs/sql/functions/char.md, docs/sql/functions/list.md
Fixes https://github.com/duckdb/duckdb/issues/14663
=> Update concat_list(), concat(), and || docs

docs/sql/functions/regular_expressions.md
Fixes https://github.com/duckdb/duckdb/issues/14697
=> Regex: Document limitations

_layouts/community_extension_doc.html, _layouts/default.html, _layouts/docu.html, _layouts/post.html, js/script.js, js/search.js
- defer javascripts
- search_data.json will be loaded only when activating search
- home typing animation faster
=> speed adjustments

_data/menu_ce.json, _includes/menu_sidebar_ce.html, docs/sql/statements/update_extensions.md
This is to be reviewed by the design team.
=> [Community Extensions] Random selection of extension (decided by jekyll sample) on the bar

docs/api/python/overview.md
=> Fix Python documentation

docs/data/json/loading_json.md
updating docs to include `map_inferance_threshold`
pr:  https://github.com/duckdb/duckdb/pull/11285
issue: https://github.com/duckdb/duckdb-web/issues/4055
discord: https://discord.com/channels/909674491309850675/921125471905787944/1305689816020549754
=> add `map_inference_threshold` docs

_posts/2024-11-14-optimizers.md
=> Add blog post

_posts/2024-11-14-optimizers.md, css/blog.scss
Also proposed usage in optimizers blogpost, @Tmonster
=> Add small_code_block css helper

_layouts/post.html, css/blog.scss
- events date
- mobile view corrections
=> small adjustments

css/copy_button.scss, css/main.scss, events/index.html, index.html, news/index.html
- blog posts and events are now clickable on the entire tile
- copy button color correction on start page
=> improvements and small bug fixes

docs/api/overview.md
Added Erlang DuckDB client library to the overview.
=> Add Erlang client library to the overview

docs/data/csv/overview.md, docs/sql/dialect/order_preservation.md
=> Document order preservation

docs/sql/samples.md
=> Fix sampling method

docs/dev/building/build_instructions.md
Requires https://github.com/duckdb/duckdb/pull/14923 to be merged
=> Add Android build instructions

docs/dev/repositories.md
add https://github.com/suketa/ruby-duckdb to repositories.md as Ruby client
=> Add ruby-duckdb client

docs/sql/constraints.md
=> Update FK example

_data/secondarymenu.json, _sass/variables.scss, css/docu.scss, css/home.scss, css/main.scss
- added prefixes to css
- improved url to media page
- corrected some colors
=> css prefixes, color corrections

docs/sql/query_syntax/where.md
=> Explain ILIKE

_includes/recent_posts_section.html, css/blog.scss, css/docu.scss, css/main.scss, css/mobilestyles.scss, js/script.js
- footer z-index fix
- better colors for button borders in menu bar
- link to media with trailing slash (other media link)
=> small design fixes

docs/data/csv/auto_detection.md
=> Update CSV sniffer result table

js/script.js
- prevent FAQ entries from closing to easily. Now you need to click on the arrow or headline to close again.
=> closing FAQ entries

docs/api/rust.md
Serves me right for using the GitHub web UI the first time 😓
=> Fix my own typos

_includes/menu_secondary_ce.html
Because I keep opening too many windows
(Random nit from my end @carlopi)
=> Open extension list in same window if navbar item is clicked

docs/operations_manual/limits.md
See https://github.com/duckdb/duckdb/issues/15174#issuecomment-2527065203
=> Operations manual: Elaborate on memory_limit

_layouts/community_extension_doc.html, _layouts/community_extension_sql_screenshot.html, _layouts/default.html, _layouts/docu.html, _layouts/post.html, _layouts/postarchive.html, css/mobilestyles.scss, css/search.scss
- recent posts margin-bottom added
- disabled hover states on touch device on options buttons in menu bar
- no zoom in on ios when using input field
=> small design corrections

.github/workflows/community_extension_docs.yml
See https://github.com/cli/cli/discussions/5792 for context
=> Avoid community_extension_docs to fail on PR already opened

js/installation.js
Fixes https://github.com/duckdblabs/duckdb-internal/issues/3755
=> Installation page: Fix regex for syntax highlighting

docs/data/json/json_type.md, docs/sql/data_types/typecasting.md
=> Fix: casted -> cast

css/blog.scss, css/darkmode.scss, css/main.scss
- will get back again to it after talking with Jonathan. But for now a quick fix.
=> quick fix for headline issue

css/blog.scss, css/docu.scss, css/home.scss, js/script.js
- Implemented a custom “fitRows” layout for Isotope to ensure equal height for post tiles.
- Adjusted padding on the landing page
- Adjusted margins for sequential post headlines
=> small corrections

docs/dev/profiling.md
=> Add links to profiling pages

BUILDING.md
=> Document downgrading Ruby

data/installation-data-1.1.yml
=> Use curl instead of wget in download script

docs/sql/data_types/interval.md, docs/sql/functions/date.md
Referring to this [Github issue](https://github.com/duckdb/duckdb/issues/15572)
=> Updated docs around arithmetic operations around INTERVAL and DATE types

docs/sql/data_types/struct.md, docs/sql/data_types/typecasting.md
Fix https://github.com/duckdb/duckdb-web/issues/4448
=> Struct cast changes

docs/sql/data_types/struct.md, docs/sql/data_types/typecasting.md
Reverts duckdb/duckdb-web#4491
=> Revert "Struct cast changes"

Gemfile.lock, _posts/2024-01-26-multi-database-support-in-duckdb.md, docs/archive/0.10/data/parquet/overview.md, docs/archive/0.10/extensions/httpfs/https.md, docs/archive/1.0/extensions/httpfs/https.md, docs/configuration/secrets_manager.md, docs/data/parquet/overview.md, docs/extensions/httpfs/https.md
=> HTTP secret

Gemfile.lock, docs/extensions/httpfs/https.md
=> Document HTTP proxies

community_extensions/development.md
Toward addressing https://github.com/duckdb/community-extensions/issues/223
=> Add description on DuckDB release process for community-extensions

docs/sql/statements/copy.md
=> Document lenience in parsing COPY statements

_posts/2025-01-10-union-by-name.md
=> Streamline result in blog post

docs/sql/functions/window_functions.md
=> Windowed DISTINCT Aggregates

data/installation-data-1.1.yml
Should be a NOP for now but there are new links
=> Update ODBC links

docs/data/csv/overview.md, docs/sql/statements/copy.md
Part of: https://github.com/duckdblabs/duckdb-internal/issues/3641
=> Adding docs on missing CSV Options

.github/workflows/lint.yml
Required to be compatible with python 3.12
=> bump version of black (linting)

docs/data/csv/overview.md
Clarifies https://github.com/duckdb/duckdb/issues/15763
=> Clarify filename option

docs/sql/functions/time.md
Simple change to remove the extra `'`.
=> docs: remove the extra redundant single quote

docs/data/json/loading_json.md
=> Issue #4465: Improve description for read_json() behavior when types for subset of columns are specified

docs/configuration/pragmas.md
=> Fix pragma call

docs/data/csv/overview.md
=> CSV params: Fix comment

docs/sql/functions/timestamp.md
current_localimestamp -> current_localtimestamp
=> Minor docs typo

docs/extensions/working_with_extensions.md
See https://github.com/duckdb/duckdb/pull/16020
=> Add redirect from troubleshoot to working_with_extensions

docs/extensions/working_with_extensions.md
More an issue than a PR.
I am not sure even this works, question would be, how to make:
https://duckdb.org/docs/extensions/troubleshooting/?version=061967287d&platform=osx_arm64&extension=iamnotexisting
work.
=> Fixup troubleshooting redirect

docs/sql/statements/copy.md
Fixes https://github.com/duckdb/duckdb-web/issues/4662
=> Remove index copy notice

docs/dev/building/overview.md
=> Add linux_amd64_musl platform

docs/configuration/pragmas.md
This PR fixes https://github.com/duckdb/duckdb-web/issues/4592
=> Add `force_compression` and `disabled_compression_methods` to the list of pragmas, under the Checkpointing section

docs/sql/statements/attach.md
Reverts duckdb/duckdb-web#4467
=> Revert "Document ATTACH OR REPLACE"

_posts/2024-06-26-benchmarks-over-time.md
=> Small fixes in the H2O blog post

_includes/installation.html, css/main.scss, data/installation-data-1.2.yml, js/installation.js
if SHA 512 hash is available it adds a button on the installation page after the link.
=> Add SHA-512 button to link

data/installation-data-1.2.yml
=> Fix Linux AMD64 download links

_includes/quick_installation.html, data/installation-data-1.2.yml
This reverts commit 3d88beb19c0b664b8d5b96dc819ad41861dc809a.
=> Revert "Simplify curl command"

docs/dev/building/build_configuration.md
This matches with what's in https://github.com/duckdb/duckdb-web/blob/main/docs/dev/building/building_extensions.md#building-extensions and should work as expected. I tested locally just in case.
=> Fix CORE_EXTENSIONS in build config.

docs/sql/indexes.md
=> Document ART indexes better

docs/sql/functions/date.md, docs/sql/functions/time.md
=> Update current date/time functions

docs/data/csv/overview.md
=> Move CSV writing to the bottom of the CSV import page

docs/sql/functions/utility.md
=> Fix query_table examples

_posts/2023-02-13-announcing-duckdb-070.md, _posts/2024-01-26-multi-database-support-in-duckdb.md, docs/guides/database_integration/mysql.md, docs/guides/database_integration/postgres.md, docs/guides/database_integration/sqlite.md
=> Spell database names consistently

docs/extensions/iceberg.md
=> Fix Iceberg example

docs/data/parquet/overview.md
=> Document BROTLI compression

docs/sql/statements/select.md
=> Rework row ids description

docs/archive/1.1/sql/functions/aggregates.md, docs/sql/functions/aggregates.md
=> Fix function name

docs/data/parquet/overview.md
Pending on https://github.com/apache/parquet-site/pull/104
=> Link Parquet site

_posts/2024-06-10-delta.md, docs/dev/building/overview.md, docs/extensions/delta.md, docs/extensions/overview.md, docs/extensions/working_with_extensions.md, docs/guides/meta/duckdb_environment.md
Reverts duckdb/duckdb-web#4917
=> Revert "Remove _gcc4 except in the legacy/experimental table"

docs/stable/sql/data_types/overview.md, docs/stable/sql/indexes.md
=> Add known foreign key limitation

docs/stable/guides/performance/my_workload_is_slow.md
replaced `intenstive` with `intensive`
=> Fixed typo in my_workload_is_slow.md

js/0.8/statements/alter.js
=> Add SET/DROP NOT NULL to ALTER COLUMN syntax diagram

docs/stable/sql/functions/aggregates.md
=> Reword sentence on ignoring NULLs

docs/stable/dev/building/linux.md, docs/stable/dev/building/overview.md
=> Rework build page

_posts/2025-03-06-gems-of-duckdb-1-2.md, docs/stable/internals/storage.md, docs/stable/sql/statements/attach.md
=> Add info on explicit storage versions

docs/stable/sql/statements/copy.md
=> List compression formats

docs/stable/sql/query_syntax/with.md, images/examples/using-key-graph-example-dark.svg, images/examples/using-key-graph-example.svg, js/stable/query_syntax/with.js, js/stable/railroad.js
Documentation for USING KEY - https://github.com/duckdb/duckdb/pull/12430
=> Add USING KEY documentation

_posts/2024-05-31-analyzing-railway-traffic-in-the-netherlands.md
=> Add max_by alternative to blog post

Gemfile.lock, css/syntax_highlighting.scss
=> Update placeholder handling

_data/menu_docs_stable.json, docs/stable/operations_manual/logging/overview.md
=> Document logging

docs/stable/data/parquet/overview.md
=> Document custom dictionary size for Parquet files

docs/stable/sql/dialect/postgresql_compatibility.md, docs/stable/sql/functions/pattern_matching.md
=> Document regex matching operators

docs/stable/sql/functions/list.md
=> Document the repeat function

js/stable/railroad.js
=> Add GROUPS framing for window functions

docs/stable/sql/functions/regular_expressions.md
=> Document that regexp_replace doesn't perform global operations by default

docs/stable/data/data_sources.md
=> Add text and blob files

docs/stable/data/json/overview.md
=> Document JSON quoting

single-file-document/concatenate_to_single_file.py
=> Strip comments from Markdown docs

docs/stable/sql/functions/utility.md
=> Add link to ICU sort key

docs/stable/clients/cli/safe_mode.md, docs/stable/operations_manual/securing_duckdb/overview.md
=> Document enable_external_access

Gemfile.lock, docs/stable/dev/profiling.md
=> Document EXPLAIN [ANALYZE] (FORMAT ...)

Gemfile.lock, docs/stable/extensions/httpfs/s3api.md
=> Document SSE via KMS on S3 feature

docs/stable/data/parquet/metadata.md
=> Document Bloom filters

docs/stable/operations_manual/securing_duckdb/overview.md
=> Document allowed* options

docs/stable/clients/cli/dot_commands.md, docs/stable/clients/cli/output_formats.md
=> Document .large_number_rendering with examples

docs/stable/sql/functions/utility.md
=> Fix utility functions page

_includes/searchoverlay.html, _layouts/postarchive.html, css/main.scss, js/search.js, news/index.html, scripts/generate_search.py
- add "type" to search_data.json to be able to distinguish between blog and documentation content
- skip images in search index
- search based on page type (all, blog, docs)
Fixes #3797
=> improved search (blog & docs)

docs/stable/data/json/json_functions.md
=> Update JSON selector syntax

docs/stable/data/json/loading_json.md
=> Revise JSON page

docs/stable/clients/python/function.md
Fixes https://github.com/duckdb/duckdb-web/issues/4154 and https://github.com/duckdb/duckdb-web/issues/4058
=> fix: add partial and null handling in Python function

docs/stable/data/partitioning/partitioned_writes.md
=> Clarify OVERWRITE options

docs/stable/clients/node_neo/overview.md
Bring the duckdb.org docs for Node Neo up-to-date with the latest on [NPM](https://www.npmjs.com/package/@duckdb/node-api).
@szarnyasg
=> node neo docs updates

index.html
=> Swap adjectives

_data/versions.csv
=> Add 'stable' to version selector

_config.yml, data/installation-data-1.2.yml, docs/stable/clients/odbc/linux.md, docs/stable/clients/odbc/macos.md, docs/stable/clients/odbc/windows.md
=> Revert to DuckDB v1.1.0 links for ODBC

docs/stable/extensions/spatial/functions.md
This will be the full function list once v1.2.2 releases.
=> update spatial function reference

docs/stable/data/parquet/overview.md
=> Remove unsupported feature

docs/stable/dev/sqllogictest/overview.md
https://github.com/duckdb/duckdb/tree/main
=> "main" branch

_config.yml
@Maxxen please drop a line once the new Rust package is out. Thanks!
=> Bump Rust package version to 1.2.2

css/blog.scss, css/docu.scss, css/mobilestyles.scss, js/script.js
- fixed issue with inline highlighted text
- set max-width for videos in posts
- fixed firefox menu issues
- changed colors for "Preview" flag
=> general improvements

community_extensions/download_metrics.md
Following @lnkuiper suggestion
=> Update download_metrics.md: Use union_by_name

docs/preview/data/parquet/overview.md
=> Document STRING_DICTIONARY_PAGE_SIZE_LIMIT

docs/preview/internals/storage.md, docs/stable/internals/storage.md
=> Add new storage version

docs/preview/extensions/aws.md
=> Update AWS extension page

docs/preview/sql/functions/date.md
=> Fix return value of date_add

_data/menu_docs_preview.json, _data/menu_docs_stable.json, docs/preview/extensions/troubleshooting.md, docs/stable/extensions/troubleshooting.md
=> Add Troubleshooting page for extensions

.github/workflows/community_extension_docs.yml
This reverts commit 04f9d24686f6dde869591b82fc43e44ed8efdf8a.
=> Revert "Avoid overriding extension list"

docs/preview/sql/data_types/numeric.md, docs/preview/sql/functions/utility.md
=> Document UUIDv7 and helper functions

scripts/rename_page.py
=> Rework rename_page.py script

_layouts/docu.html, css/blog.scss, css/mobilestyles.scss
- more padding when preview or outdated banner is shown
- toc menu now auto height
=> small design adjustments

docs/preview/clients/python/relational_api.md, scripts/generate_python_relational_docs_examples.py
Fixes https://github.com/duckdb/duckdb-web/issues/4445
=> fix: add additional information py relational join

docs/preview/data/csv/overview.md
See: https://github.com/duckdb/duckdb/pull/17220
=> Add thousands option (CSV Reader) to preview

docs/preview/clients/python/relational_api.md, scripts/generate_python_relational_docs.py, scripts/generate_python_relational_docs_examples.py
Fixes https://github.com/duckdb/duckdb-web/issues/5245
=> fix: add aliases to py relational api docs

_sass/mixins.scss, css/main.scss, css/mobilestyles.scss, js/copy_button.js
=> footer logo fix

docs/stable/sql/data_types/nulls.md
I wanted to use simpler language than eg `semantics`.
=> Add notes on IN/NOT IN to nulls.md, and simplify prose

docs/preview/clients/python/conversion.md
Fixes https://github.com/duckdb/duckdb-web/issues/4268
=> fix: add conversion with udf details

docs/preview/sql/statements/create_table.md, docs/stable/sql/statements/create_table.md, js/preview/statements/createtable.js, js/stable/statements/createtable.js
=> Document WITH NO DATA

Gemfile.lock, docs/preview/sql/meta/duckdb_table_functions.md
=> Document duckdb_prepared_statements

docs/preview/clients/python/expression.md
Fixes https://github.com/duckdb/duckdb-web/issues/4933
=> fix: add SQLExpression examples

docs/preview/clients/python/relational_api.md, scripts/generate_python_relational_docs_examples.py
Fixes https://github.com/duckdb/duckdb-web/issues/5055
=> fix: document fetchone and fetchmany behavior on aggregate

docs/preview/clients/python/relational_api.md, scripts/generate_python_relational_docs.py, scripts/generate_python_relational_docs_details.py
Fixes https://github.com/duckdb/duckdb-web/issues/1786
=> fix: add parameter description to Python relational API

docs/preview/guides/python/jupyter.md
Fixes https://github.com/duckdb/duckdb-web/issues/5091, https://github.com/duckdb/duckdb-web/issues/4928, https://github.com/duckdb/duckdb-web/issues/4731
=> fix: fix jupyter example and add extra desc

docs/preview/core_extensions/iceberg/overview.md, docs/stable/extensions/iceberg/overview.md
Mention that iceberg extension can be used together with the azure extension
=> docs: mention that iceberg extension can be used together with the azure extension

docs/preview/sql/functions/lambda.md
Fixes #5294
cc @taniabogatsch 
Pending on PR https://github.com/duckdb/duckdb/pull/17235
=> Update lambda page with new syntax

docs/preview/sql/indexes.md, docs/stable/sql/indexes.md
For context: https://github.com/duckdb/duckdb/discussions/17455
=> Expand known limitation workaround section

docs/preview/clients/python/relational_api.md, scripts/generate_python_relational_docs.py, scripts/generate_python_relational_docs_details.py
Fixes https://github.com/duckdb/duckdb-web/issues/5375
=> fix: add parameter description for Python rel API output methods

docs/preview/sql/meta/duckdb_table_functions.md
Partially addresses #4374
cc @samansmink
=> Add more DuckDB_ tables

docs/preview/sql/data_types/typecasting.md, docs/preview/sql/functions/utility.md
Towards https://github.com/duckdblabs/duckdb-internal/issues/4825
=> Document missing functions

_posts/2025-05-14-sorting-for-fast-selective-queries.md
Small tweak to the "Sorting on Insert for Fast Selective Queries" blog post!
=> Only first 8 bytes in varchar zone maps

docs/preview/sql/functions/blob.md, docs/preview/sql/functions/text.md, scripts/generate_sql_function_docs.py
minor fixes for text and blob functions.
Based on  
- `duckdb` sha: https://github.com/duckdb/duckdb/pull/17132/commits/826231ecc6002a1129066e1bb8cd6dce03df2857
- `duckdb` PR: https://github.com/duckdb/duckdb/pull/17132
=> Fix link and space displaying

docs/preview/clients/python/relational_api.md, scripts/generate_python_relational_docs_details.py
Fixes https://github.com/duckdb/duckdb-web/issues/5372
=> fix: add param details to Python rel API definition

docs/preview/dev/building/python.md, docs/stable/dev/building/python.md
This commit updates the Python package development documentation to provide complete guidance on building from source, setting up development environments, and troubleshooting common issues. Includes new sections for debugging, IDEs and building with extensions, and moves snippets previously in the Python package README.
Related to duckdb/duckdb#17483
=> docs: comprehensive update to Python package development docs

_config.yml, data/installation-data-1.3.yml
@staticlibs please let me know when this is good to be merged
https://github.com/duckdb/duckdb-odbc/releases/tag/v1.3.0.0
=> Bump ODBC version to v1.3

docs/stable/dev/profiling.md
Fixes https://github.com/duckdb/duckdb-web/issues/5411#issuecomment-2900758436
=> Document new profiling metrics

scripts/archive_docs.py
=> Fix archive script

docs/stable/guides/meta/list_tables.md
Fixes https://github.com/duckdb/duckdb-web/issues/5034
=> fix: add link to use schema docs

docs/stable/sql/dialect/sql_quirks.md
Fixes https://github.com/duckdblabs/duckdb-internal/issues/4871
=> Add explanation on INT8 vs UINT8

docs/stable/operations_manual/logging/overview.md
First version to remove outdated logging docs, this is to be updated for v1.4 which will have an improved UX to interact with the logging config
=> first version of improved logging docs

_posts/2025-06-06-advanced-sorting-for-fast-selective-queries.md
Howdy folks! This is part 2 of 2 in the approximate sorting post series. 
I made a few changes to try and improve readability. I inlined the content from the appendix into expand/collapse sections (collapsed by default). I also added some intro and conclusion content so that this post could stand on its own. 
I also re-focused the post onto the dashboarding use case. The experiments focused on a dashboard already, so it felt like a natural way to make the post more useful to a broader set of folks. As I think about it, should the title be re-sorted (ha!) to "Faster Dashboards with Multi-Column Approximate Sorting" ? (Edit: Changed the title!)
I am open to feedback! I've got some time to make adjustments before we publish, so just let me know!
Here is a PDF for the collapsed version, and …
=> "Faster Dashboards with Multi-Column Approximate Sorting" post

docs/stable/sql/statements/copy.md
Add missing doc for PARQUET_VERSION in COPY TO Parquet options.
=> Add PARQUET_VERSION

docs/preview/sql/query_syntax/with.md
Update documentation to changes done in https://github.com/duckdb/duckdb/pull/17459
=> Adapt documentation of CTE materialization/inlining

docs/stable/core_extensions/azure.md
Corrected a couple of English grammar mistakes and typos for Azure extension
=> chore: fix azure docs english typos

docs/preview/sql/statements/attach.md, docs/stable/sql/statements/attach.md, js/preview/statements/attach.js, js/stable/statements/attach.js
=> Pr4739 followup: ATTACH OR REPLACE

docs/preview/data/parquet/metadata.md, docs/stable/data/parquet/metadata.md
This is also a followup for https://github.com/duckdb/duckdb/pull/18294
=> Add parquet metadata fields

_sass/components/_copy_button.scss, _sass/components/_faq.scss, _sass/layout/_responsive.scss
color adjustments
Docs-Logo longer visible (responsive)
=> Small CSS adjustments

docs/preview/clients/adbc.md
Update Go example on ADBC Client docs page to use high-level ingest API. Closes #5660
=> refactor(go-example): Update Go example on ADBC Client docs page

docs/preview/guides/file_formats/read_file.md
https://github.com/duckdb/duckdb/pull/18706
=> Document read_blob and read_text supporting Hive partitioning.

_includes/installation.html, _sass/pages/_installation.scss, js/install.js
=> new install page updates

_sass/pages/_docs-content.scss, _sass/pages/_ducklake.scss, _sass/themes/_darkmode.scss, _sass/utilities/_helpers.scss
Extended .darkmode-img and .lightmode-img so it works also for video elements.
=> video elements in dark and light mode

_includes/checksum_inline.html, _includes/installation.html, _sass/base/_syntax_highlighting.scss, _sass/pages/_duckdblabs.scss
- hashes will be displayed now for java and odbc
=> added hashes for odbc and java

_includes/installation.html, js/install.js
- added data attributes for storing the current versions
- added function to update version number on installation instructions
=> show correct java and odbc version on installation page

docs/stable/internals/storage.md, docs/stable/sql/statements/attach.md
=> Document database encryption

docs/stable/sql/statements/attach.md, docs/stable/sql/statements/checkpoint.md
=> Update checkpointing and attach pages

docs/stable/guides/python/export_arrow.md
fixes https://github.com/duckdb/duckdb-python/issues/95
=> update arrow guide

docs/preview/core_extensions/aws.md, docs/stable/core_extensions/aws.md
also tweak incorrectly tagged literals in examples
=> describe aws validation usage
